modflowpy/flopy

flopy/utils/binaryfile.py
Please take a look at the create3D function that I changed.  It was setting the entire array to 0 and then summing any values in that cell.  I changed it to use and return a masked array.  It was much easier for me to be able to assume a masked array and not have to strip out all zero values downstream in `modflow2netcdf`.  However, if you don't like the change, I can manage!
=> Small improvements and bug fixes to support modflow2netcdf

flopy/utils/mfreadnam.py
commit message: Added a getfiletypeunit function to mfreadnam to allow a user to pass in a NamData dictionary and filtype and return the unit number associated with it. That way, filenames for packages can be pulled from the namefile rather than needing to be specified outside that world.
=> Added function to mfreadnam to return unit associated with a filetype from a namefile

flopy/mt3d/mtbtn.py
Small fix which I noted after seeing the same number for nrow and ncol in line 3 of the btn written by flopy.
=> fix ncol set to nrow in BTN setmodflowvars

flopy/modflow/mflmt.py
Because of this mix-up the output unit was actually the format, which crashed when it had to be written to the file as an integer.
=> fix writing output unit and format to LMT package

examples/Notebooks/flopy3boundaries.ipynb
There were missing some commas in the comments of stress periods parameters.
Now the number of array elements consists with the documentation.
=> Update comments in flopy3boundaries.ipynb

flopy/modpath/mpsim.py
This fixes the writing of zone information to the .mpsim file.
=> Fix zones in simulation file

flopy/modflow/mfsfr2.py
When ISFROPT==0, sfr.write_input() writing uninitialized values when stress period = 1; and not enough terms are written when stress period > 1.  The problem is shown in the attached screen shot...the three variables highlighted by the red box were not being written when stress period > 1.  ISFROPT gets set equal to zero by default when the keyword Reachinput is not used.
=> Minor cleanup in sfr.write_input() for the case when ISFROPT==0

flopy/utils/formattedfile.py
Fixed bug reading formatted files with get_ts.  The reader was stopping one column early when the column being read was immediately after a line wrap.  In the code the outer while loop was checking for the column incorrectly but the inner for loop check is/was correct.  The conditional in the while loop has been updated to agree with the for loop.
=> FormattedHeadFile get_ts bug

flopy/modflow/mfsfr2.py
this wasn't happening before, so the channel cross section and flow information was no longer referencing the correct segments after renumbering.
=> bug fix: renumber sfr channel data

flopy/utils/zonbud.py
For a steady state calculation, the list of cbc_times is empty, therefore the totim cannot be obtained using kstpkper. See #221.
=> check for empty list of cbc_times in _build_empty_record

flopy/utils/zonbud.py
I updated the logic which compares the shape of the input zone array against the model. If the input array is 2-D (or single layer 3-D) and has matching row/column dimensions, the zones are now applied to all layers. An exception is raised in the case where other odd shaped arrays are encountered (i.e. not a single-layer 3-D array and number of layers does not match number of layers in the model).
=> Allow for use of 2-D zone array for all layers

flopy/modflow/mfmnw2.py
If no pumping specified in MNW2 package for stress period 0, a `KeyError` will be thrown. Instead can use first available dictionary key to check if "k" in `dtype.names`.
=> MNW2 load: KeyError raised if no pumpage specified for stress period 0

flopy/modflow/mfupw.py
Default behavior for the module is that ipakcb=0. No code was changed, the correct default value is listed in similar packages (mfriv.py, mfghb.py).
=> Fixed docstring for "ipakcb"

autotest/t031_test.py, flopy/modflow/mfdis.py, flopy/modflow/mfsfr2.py, flopy/utils/modpathfile.py, flopy/utils/postprocessing.py, flopy/utils/recarray_utils.py, flopy/utils/util_array.py
Recent builds pass autotests ([e.g.](https://travis-ci.org/modflowpy/flopy/jobs/363188376)), but their logs reveal many warnings from numpy (RuntimeWarning and FutureWarning). While some of these are annoying, they do indicate some functionality will break in not-too-distant numpy versions.
I've made several modifications to resolve some of these issues, and generally there are two kinds of fixes:
* Use masked arrays to handle invalid values. Masked arrays are essentially what MODFLOW does with an IBOUND array, so I find it surprising to not see them used in flopy. To me it seems wrong to use `np.nan` values in arrays for this purpose, as it may cause invalid value issues.
* Use structured arrays rather than recarrays. Recarrays are essentially structured arrays, but with [extra …
=> Resolve several numpy warnings

autotest/t011_test.py, flopy/utils/mflistfile.py
Similar to #317, clean up a few warnings/errors with recent numpy releases, such as `FutureWarning`s (mostly on recarrays), and a few `AttributeError`s on numpy's nan.
=> Tidy up more warnings/errors with recent numpy versions

autotest/t009_test.py, autotest/t020_test.py, autotest/t502_test.py, autotest/t503_test.py, autotest/t504_test.py, autotest/t505_test.py, flopy/__init__.py, flopy/mbase.py
Flopy's "which" doesn't always work as good as other implementations of similar utilities. For instance, it does not find "mf2005.exe" on Windows computers with an input of "mf2005". This means that most of `t012_test.py` is effectively skipped on Windows computers. While other tests (e.g. `t020_test.py`) adjusted the executable before testing with "which".
This PR replaces "which" with the Python 3.3 built-in [shutil.which](https://docs.python.org/3/library/shutil.html#shutil.which), which is agnostic to Windows executable file extensions (i.e. `.exe`). Older Python versions can use [distutils.spawn](https://docs.python.org/2/distutils/apiref.html#module-distutils.spawn) for the same functionality. Also, `flopy.is_exe` is removed, as it wasn't used anywhere else. I've also removed …
=> Replace "which" with built-ins / distutils.spawn

flopy/pakbase.py
Specifically, force `field_name` to be a string, and simpler append of new data types. Also add missing docstring for this method.
This fixes an issue reading some package files with Python 2.7, where this method was raising "TypeError: data type not understood".  This was introduced in 3964672 for #248, which uses `io.open` to read text files, which returns Unicode objects instead of string objects (like `open` does). While this may seem harmless, it causes issues with Numpy's structured arrays, basically trying to do `np.dtype([(u'iface', np.float32)])`, which is a no no.
=> Improve flopy.pakbase.Package.add_to_dtype

flopy/utils/util_list.py
Stress data written by flopy inflates floating point precision, rather than preserving the native precision of the data type. This is due to a C-formatter tucked deep within flopy/utils/util_list.py. For example, a flux rate from a well package that is originally -8773.9 is effectively written by flopy as -8773.9004, introducing a difference of 0.0004. The good news is that these differences do not matter to single-precision floats (i.e. REAL or float32), but they are visually different when formatted, or used in double precision (or float64).
```python
import numpy as np
x = np.float32(-8773.9)
print(str(x))  # -8773.9
print(' %15.7E' % (x,))  # '  -8.7739004E+03'
print(' %15s' % (x,))  # '         -8773.9'
```
As shown above (and in this PR), the suggested fix is to just format a string …
=> Change MfList.fmt_string for floats to use numpy's string formatter

flopy/modflow/mfgage.py
FloPy was previously resetting negative gage output unit numbers (UNIT) to absolute values before writing package file. 
From MODFLOW-NWT docs:
> UNIT 
Unit number for output file. Specify negative value of unit number to invoke reading of optional parameter OUTTYPE for listing additional information for lakes.
Previously:
autotest t047_test.py wasn't catching this but was writing the gage package incorrectly as:
> 2
-1 26
-2 27
This fix(?) removes line that sets gage_data['unit'] [n] to the absolute value. 
After this change FloPy in writes:
> 2
-1 -26 1
-2 -27 1
Unit numbers in the .nam file are still positive and correct.
=> Allow negative unit number to be written to Gage package input

flopy/modflow/mflmt.py
The link to the Modflow-Guide returned an 404-Error.
This PR fixes the URL.
=> Updates mflmt.py documentation

autotest/t044_test.py, flopy/modflow/mfbas.py
There are actually two related bugs addressed in this PR (one for each commit):
1. Loading: option lines like `FREE, SHOWPROGRESS` (see examples/data/pcgn_test/MNW2.bas) were not correctly parsed, since `split()` would get `FREE,`, rather than `FREE` (see the comma?). The fix is to replace most non alphanumeric characters with a space before `split()`
2. Writing: the hnoflow was not correctly written for fixed-formats, making MODFLOW think -999.0 was 0.0
=> BUG: BAS6 free reading, fixed writing

autotest/t004_test_utilarray.py, flopy/utils/util_array.py
This is essentially a minor extension of #386 which rewrote a few of the load methods.
* Add a few unit tests for each array load method
* Tidy an unnecessary data cast in load_block
* Allow load_bin's file_in to open a filename, as with other array loaders
* A previous integer binary file was moved up into test_load_bin
* As a bonus, load_bin is already set to read DOUBLE PRECISION (aka float64) without any additional effort
=> Add tests for Util2d load methods

flopy/mt3d/mtbtn.py
Also use Util2d.load_txt to read timprs and tslngh fixed 1-D arrays; read1d_fixed no longer needed.
=> BUG: laycon needs fixed format read

examples/Notebooks/flopy3_WatertableRecharge_example.ipynb, examples/Notebooks/flopy3_sfrpackage_example.ipynb, examples/Notebooks/flopy3_shapefile_export.ipynb, examples/Notebooks/flopy3_working_stack_demo.ipynb
I noticed that Travis CI's Python 3.6 builds were failing due to a few errors in the example notebooks. This attempts to fix them.
Errors were either using `% matplotlib inline` instead of `%matplotlib inline`, or not having `from __future__` at the top.
=> Fix a few "[NbConvertApp] ERROR" from Python 3.6

code.json, pre-commit.py
This helps minimize numbers of lines changed after pre-commit.py, as dictionaries are inherently not ordered. This change uses an OrderedDict to maintain the order in code.json. Note that content of code.json has not changed, and has non-working URLs. It is only ordered more naturally:
```
['name',
'description',
'organization',
'contact',
'version',
'status',
'date',
'permissions',
'homepageURL',
'repositoryURL',
'downloadURL',
'disclaimerURL',
'vcs',
'languages',
'tags',
'laborHours']
```
=> Maintain order of items in code.json

flopy/modflow/mfgage.py, flopy/modflow/mflak.py, flopy/utils/flopy_io.py
I found when creating or modifying a LAK package with flux_data input as
a numpy array that ModflowLak would die on td[k] = value[k, :].aslist().
I could find no reference to this numpy array method, so not sure where
it comes from. I changed .aslist() to .tolist() (https://docs.scipy.org/
doc/numpy/reference/generated/numpy.ndarray.tolist.html), which works.
I subsequently encountered the same error in other files (flopy_io and
mfgage), and hence altered the .aslist() calls in those too.
=> Fix(Numpy array .aslist() calls)

flopy/modflow/mf.py
The load function should be able to import exotic/classic MODFLOW models that don't use a `.nam` extensions for the NAM file (Visual MODFLOW Classic, GMS, probably others). These changes in this PR mimic the behavior of the MODFLOW command, where a `.nam` extension is added only if the file does not exist.
And if neither of these files exist, a `IOError` is raised.
=> Only add .nam extension if needed

flopy/modflow/mflpf.py, flopy/modflow/mfupw.py
Use `read1d` to read LAYTYP, LAYAVG, CHANI, LAYVKA, and LAYWET, which can span more than one line.
This was essentially lifted from mflpf.py
=> BUG: UPW's data sets 2 to 6 can span several lines

examples/scripts/flopy_swi2_ex1.py, examples/scripts/flopy_swi2_ex2.py, flopy/mt3d/mtcts.py, flopy/mt3d/mtlkt.py, flopy/mt3d/mtsft.py
Found a few instances where a module calls `sys.exit` while in verbose mode. This is a Python no-no, and I've rewritten these instances to raise a ValueError.
However, `sys.exit` should be used in scripts where `__name__ == '__main__'` so the success code is returned to the shell.
=> Improper uses of sys.exit

autotest/t007_test.py, flopy/modflow/mf.py, flopy/utils/util_array.py
This PR allows loading a MODFLOW model with an incomplete BAS6 package, e.g. where STRT is an EXTERNAL reference to a file that does not exist. Previously, a vague error would be raised in this instance:
> TypeError: coercing to Unicode: need string or buffer, NoneType found
as loading BAS6 in full was required.
Changes in this PR first show a better exception when attempting to load an array from an EXTERNAL file that does not exist, e.g.:
> IOError: cannot read unit 630, filename: ./starting.hds
And secondly, BAS6 is loaded under the same `forgive` / `load_only` options as the other packages, as it doesn't require any special treatment beyond finding the "FREE" option, as is already done if the file is present. This allows loading of MODFLOW models with incomplete BAS6 packages.
=> Forgive loading models with an incomplete BAS6 package

autotest/t032_test.py, examples/Notebooks/flopy3_shapefile_features.ipynb, flopy/export/shapefile_utils.py, flopy/utils/reference.py, requirements.travis.txt, requirements2-34.travis.txt
The previous implementation stored user data within a Python module in a platform specific location, which is problematic on many levels.
For instance, on platforms that don't use `site-packges`, this is the error:
```
File "../flopy/utils/reference.py", line 1812, in __init__
sp = [f for f in sys.path if f.endswith('site-packages')][0]
IndexError: list index out of range
```
Furthermore, often this directory is not user-writable, therefore many of the tricks to read/write epsgref.py would not work without root privileges. And there are too many workarounds required to make a Python module behave as hashable and human-readable database (e.g. reload(), deleting .pyc, etc.).
I think it's better to store the user data using [appdirs](https://pypi.org/project/appdirs/), which effortlessly …
=> Refactor epsgRef to use JSON file in platform independent location

flopy/utils/gridgen.py, flopy/utils/util_array.py
This change ensures that external files of 1-D arrays written by `Util2d.write_txt` and `Gridgen.to_disu6` are written on one line (i.e. row output). For example, previously an open/close file for delr would have been written on one line in delr.ref, but some subtle changes from #386 changed this behavior to write this external file with column output, i.e. one line per number. This is because [numpy.savetxt](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.savetxt.html) writes 1-D arrays as column output.
(It is also because the array's fortran_format changed from a default `(nplE15.6)` format from a numpy array constructor to a `(FREE)` fortran_format from a Util2d array constructor. Specifically [here](https://github.com/modflowpy/flopy/pull/386/files#diff-5a7ded6d95d11 …
=> Ensure external 1-D arrays are written like 2-D arrays

docs/version_changes.md, flopy/export/vtk.py, flopy/utils/reference.py
htop can now be passed into the vtk writer. htop should be the top of the cell or the head, whichever is lower. Also refactored the shared_vertex option so that when the ibound filter is used, only the points for the active cells are included in the vtk point list. Prior to this change, all of the vertex points for the grid were included in the vtk file, which resulted in very large vtk files.
=> feat(vtk): Added new htop argument to vtk writer

flopy/modflow/mfsfr2.py
Missing comma in mfsfr2.py get_default_reach_dtype for unstructured option.
=> Fix 'tuple not callable' error in SFR

flopy/mf6/modflow/mfsimulation.py
Absolute path imports of flopy in the mf6 part of flopy have all been changed to relative path imports.  However, there still are a few places in the original flopy code that use absolute path imports of flopy (in export/utils.py, plot/plotutil.py, utils/datafile.py, utils/util_array.py, and utils/util_list.py).  In these cases I am not sure if this was intentional or not, so I did not change it.
=> fix(import): mf6 absolute path imports changed to relative path imports

.travis.yml, autotest/autotest_notebooks.py, autotest/autotest_scripts.py, requirements27.travis.txt
Python 3.4 is a few weeks from it's end-of-life https://devguide.python.org/#branchstatus
Python 3.7 was released half a year ago, so it makes sense add this to the Travis CI mix.
I've also dropped 3.6-dev, as 3.7-dev was already there.
Note that some of these changes were in place from a3822baa79bacbf326fd651c93a9bdd7d106ebfd but reverted.
=> ci(.travis.yml): Drop Python 3.4, add Python 3.7

flopy/modflow/mfstr.py
=> Fix(mfstr):  Fix for ModflowStr.load() crash when data identifiers/comments are present

autotest/t017_test.py, flopy/utils/binaryfile.py, flopy/utils/datafile.py
This feature provides a more useful error message when attempting to read an empty file. For example, if a mt3dms simulations crashes (e.g. #466), it leaves an empty `file.ucn` file and this is the error:
```
ucnobj = flopy.utils.UcnFile('file.ucn')
```
> IndexError: index 0 is out of bounds for axis 0 with size 0
The new message should now be:
> OSError: datafile error: file is empty: file.ucn
which is intended to help the user sort out their issue. This message is used for:
- `flopy.utils.UcnFile`
- `flopy.utils.FormattedHeadFile`
- `flopy.utils.HeadFile` (with/without auto-precision detection)
- `flopy.utils.CellBudgetFile`
=> feat(datafile): Raise IOError when attempting to read empty files

flopy/plot/plotutil.py
changed top.shape from (nlay, ncpl) to (ncpl,) to fix multi-layered model support
issue #486
=> Fix(plotutil.py): saturated_thickness() method.

flopy/discretization/grid.py, flopy/export/netcdf.py, flopy/modflow/mf.py, flopy/seawat/swt.py
* added units property to Grid base class
* added support for either string or int lenuni parameter input for Grid class
* updated mf.Modflow.modelgrid property to pass integer lenuni to modelgrid
* updated swt.Seawat.modelgrid property to pass integer lenuni to modelgrid
issue #489
=> Fix(grid.py): lenuni stored as integer in Grid

autotest/t003_test.py, flopy/modflow/mfoc.py
Add additional error trapping for passed `nper`, `nstp`, and `nlay`.
Add error trapping for the length of `nstp` relative to `nper`.
Closes #518
=> fix(oc): fix oc load when ext_unit_dict is None

autotest/t062_test_intersect.py, examples/Notebooks/flopy3_mf6_vertex_plotting.ipynb, flopy/discretization/grid.py, flopy/discretization/structuredgrid.py, flopy/discretization/unstructuredgrid.py, flopy/discretization/vertexgrid.py, flopy/utils/geometry.py
I have implemented the intersect-method for a VertexGrid (disv). This intersect method is set up in the same way as in a StructuredGrid, where you pass floats `x` and `y` and optionally a variable called `local`, and you get a cell2d-number in return (instead of row,col).
This method first checks which cells are likely to intersect with the point (x,y), to speed things up. Then it uses the Path.contains_point method from matplotlib. It should work for any type of geometry (rectangles, triangles, etc.). When the point is on the edge between two cells, the lowest cell2d-number is returned.
I have added some lines in flopy3_mf6_vertex_plotting.ipynb, so that the code is tested. Please let me know it this is not the way to go.
=> Implement intersect method for VertexGrid

autotest/t041_test.py, flopy/modflow/mfhob.py
Due to binary representation of base-10 floats in Python, floats read from text can have high decimal place values added to them. This can cause an error when reading in an HOB with multilayer observations. The sum of the mlay must equal 1; however, the sum could be calculated as 0.9999999 and raise an error. This relaxes the criteria for the sum of mlay to 0.99999 < sum < 1.00001. It also changes the error message to include the observation name where the error occurred.
Resolves #528. Didn't cause any additional failures or errors during the autotest. I called Travis to pass it by him, but he didn't answer.
=> Relax HOBs mlay Sum Criteria

autotest/t007_test.py, autotest/t032_test.py, flopy/discretization/unstructuredgrid.py, flopy/mbase.py, flopy/mf6/utils/reference.py, flopy/modflow/mfdis.py, flopy/utils/reference.py
In some flopy modules the default projection for model grids is [EPSG:4326](http://epsg.io/4326) (a.k.a. WGS 84 or World Geodetic System 1984), which is a geodetic coordinate system with units of degrees of latitude and longitude.
MODFLOW grids do not support length units in degrees. Generally, it should only support projected coordinate reference systems with units in meters, feet, etc. as defined in various UTM zones, State grids, national grids, locally-defined grids for a site, etc.
This PR changes the default projection to None (i.e. undefined). The NAM file would show just `proj4_str:` with an empty value. This is more-or-less already done with `discretization/grid.py`, but there were a few other modules that needed attention.
=> Change default proj4 from EPSG:4326 to None

autotest/t003_test.py, flopy/mbase.py, flopy/mt3d/mt.py
Attempting to load a mt3d model that does not exist (e.g. `foo.nam`) raises a confusing message:
> TypeError: can only concatenate str (not "NoneType") to str
This PR changes the behavior to split the extension a bit cleaner to make a `str` type, regardless if the file exists or not, and allow a more useful message to be shown:
>Exception: error loading name file entries from file:
> Could not find .\foo.nam in directory .
=> bug(mt3d): ensure namefile_ext is str type

autotest/t504_test.py, autotest/t505_test.py, flopy/mf6/data/mfdataarray.py, flopy/mf6/data/mfdatalist.py, flopy/mf6/data/mfdatastorage.py, flopy/mf6/modflow/mfsimulation.py
Auxiliary variables now accept any data formats in any order. Integrated better better test coverage of aux variables into our current tests. get_data() now returns transient data as a dictionary.
=> Auxiliary variable fix (#533)

flopy/modflow/mfsfr2.py, flopy/utils/mflistfile.py
adding a return to `m.sfr.renumber_segments()` to return segment mapping dict
deal with \'*\' abutting strings in mflist
=> minor (hopfully) fairly inconsequential mods

autotest/t004_test_utilarray.py, flopy/utils/util_list.py
Modification of `util_list.get_dataframe()` method to deal with multiple
Deal with multiple wells (or list entries) in model nodes when constructing the pandas DataFrame.
Method is now to aggregate such wells in the dataframe.
Added some tests for this method too - couldn't find elsewhere.
Also think `squeeze` option is safer with a fillna or diff from NaN
picks up no changes.
=> Cleaned-up PR for util_list.get_dataframe() method

autotest/t024_test.py, flopy/modflow/mfoc.py
This will catch situation where (e.g.) `period 1 step 2` is defined (from `stress_period_data={0, 1}`) with steady state models with only one stress period/step. Modflow will ignore these entries in the OC file, so a Warning is appropriate for checking.
=> refactor(oc): add check method

autotest/t504_test.py, flopy/mf6/data/mfdataarray.py, flopy/mf6/data/mfdatastorage.py, flopy/mf6/data/mffileaccess.py, flopy/mf6/modflow/mfsimulation.py, flopy/utils/datautil.py
The write_simulation method now has a silent parameter to write simulations silently:
sim.write_simulation(silent=True)
This behaves the same as setting the verbosity level to quiet before calling write_simulation and then setting it back to its previous value after the write_simulation call.
Retrieving mf6 data has also been optimized to run faster.
=> Write Simulation Silent Option (#552) + Retrieving Data Optimization (#553)

flopy/modflow/mfbcf.py
patched `bcf.write()` to always write both digits of `ltype` and respect fixed vs free format
=> Fix bcf ltype, closes #74

flopy/mbase.py, flopy/modflow/mf.py, flopy/modflow/mfdis.py
- Show one "xul/yul have been deprecated" warning message if both were provided (e.g. in older .nam files)
- [inspect.getargspec()](https://docs.python.org/library/inspect.html#inspect.getargspec) is deprecated since Python 3.0; use inspect.getfullargspec()
- Ignore DeprecationWarning when creating `dis._sr`
There are pile of other warnings that I haven't touched yet, but anyone interested can see them by setting the environment variable `PYTHONWARNINGS=always::DeprecationWarning` from a shell, or in a script:
```python
import warnings
warnings.simplefilter('always', category=DeprecationWarning)
```
=> refactor: silence a few DeprecationWarning messages

autotest/t505_test.py, examples/Notebooks/flopy3_mf6_tutorial.ipynb, flopy/discretization/structuredgrid.py, flopy/discretization/unstructuredgrid.py, flopy/discretization/vertexgrid.py, flopy/mf6/coordinates/modeldimensions.py, flopy/mf6/data/mfdata.py, flopy/mf6/data/mfdatastorage.py, flopy/mf6/data/mffileaccess.py, flopy/mf6/mfmodel.py
Feature allows for the reading and writing of MF6 external binary files. Interface allows user to create a binary file from existing data, specify an existing binary file to use, and access binary data from an existing MF6 simulation.
=>  Reading and Writing of MF6 Binary Lists

autotest/t007_test.py, flopy/plot/map.py, flopy/plot/plotutil.py, flopy/plot/vcrosssection.py, flopy/utils/geometry.py
* updates to PlotMapView.contour_array() and _VertexCrossSection.contour_array() to allow nan to be passed in the array #587 
* added test_tricountour_NaN() to t007_test.py 
* updates to PlotMapView.contour_array() and plot_array() to drop extra dimension from head array with using vertex model grid #588
* updates to UnstructuredPlotUtilities, added irregular_shape_patch() as patch for cross section drawing of vertex and unstructured modelgrids that include multiple geometries (bug fix #588)
* update to geometry.transform() to set x and y dtypes to float (bug fix #588)
=> Fix(plotting): Bug fixes for issues #587 and #588

flopy/utils/reference.py
When `proj4_str` is `None`, `SpatialReference` throws errors about not being able to parse units. Seems a meaningless error for instructive cases that are not projected.
=> suppressing error when proj4_str is None

autotest/t023_test.py, flopy/mt3d/mtbtn.py
This is a tiny one: 
When writing btn obs, flopy adds 1 to the k,i,j values bringing us nicely from a python world to a mt3d world; this makes sense. However, when loading a mt3d model we weren't subtracting 1. The result was a systematic migration of observation locations in 3D space when loading and writing. Quick fix, subtract 1 when loading.
=> fix creep of btn obs locations when reading and writing mt3d model

autotest/t041_test.py, flopy/modflow/mfflwob.py, flopy/modflow/mfhob.py
Changes to `ModflowHob` and `ModflowFlwob` to treat variables `irefsp`, `layer`, `row`, and `column` uniformly as zero-based integers. Addresses issue #586.
=> Zero-based integers for select ModflowFlwob variables

autotest/t007_test.py, flopy/export/utils.py, flopy/utils/geometry.py
Required fixing flopy.utils.geometry so that the Polygon.pyshp_prts handled holes correctly for multiple shapefile versions.  The exterior ring and interior rings need to have vertices sorted in the proper clockwise order.
=> feat(export_contourf): export filled contours to shapefile

flopy/discretization/grid.py, flopy/mbase.py, flopy/modflow/mf.py, flopy/utils/util_list.py
These are a few changes that relate only to the output whitespace, and should not change any behavior:
* The discretization line in the NAM file had an awkward `..lenuni:2;  ;start_datetime...` (with a gap), which is tidied up to a more common delimited style
* Also with the NAM file, there was trailing whitespace after package source file, i.e. `freyberg.dis `.
* On Windows (only), the MFList outputs (e.g. WEL, etc.) had a mixture of CRLF and LF endings, as this file used a mixture of binary and non-binary open modes while appending output. This is now changed so that the write mode only changes to binary if the data is binary.
=> refactor whitespace in NAM file and MFList output files

autotest/t032_test.py, flopy/mbase.py
Supersedes #621
I don't fully understand the issue, except that there are various issues issues (e.g. [here](https://bugs.python.org/issue7213)) related to Popen's `close_fds` parameter for Python 2.7 on non-Windows. My guess is the file descriptors get too full and no more memory can be allocated to hold the buffers. Setting `close_fds=True` fixes the issue for this scenario. I'm not sure if it should be a general default for Popen.
And also, Python 2.7 is [nearly dead](https://pythonclock.org/) and I'd suggest dropping support for this soon, as most other Python projects have already done, e.g., numpy's release from last week is Python 3.5+ only.
Other improvements to `normal_msg` docstring and handling.
=> Fix "Cannot allocate memory" error for Python 2.7 on non-Windows

autotest/t007_test.py, flopy/export/shapefile_utils.py, flopy/utils/reference.py
Identified a bug while exporting a netCDF file where a `UnboundLocalError` was raised for `datum` and/or `ellps`.
=> Resolve UnboundLocalError with crs property

flopy/export/utils.py
A local variable `i` was used twice in different scopes, which seems to be an issue for Python 2.7 only.
This should put the green light back on the Travis CI tests.
=> Tidy local variable use for Python 2.7 test

flopy/utils/util_list.py
A modification from #622 broke writing MFList outputs (WEL, etc.) for users with numpy < 1.14.0
With these older numpy versions, `np.writetxt` needed to be opened with `b` mode.
Note that I've carefully checked this behaviour change between these two numpy releases.
=> Older numpy needs opened file in binary mode for writetxt

autotest/t505_test.py, flopy/discretization/grid.py, flopy/mbase.py, flopy/mf6/data/dfn/gwf-disu.dfn, flopy/mf6/data/mfdatastorage.py, flopy/mf6/mfmodel.py, flopy/mf6/modflow/mfsimulation.py, flopy/utils/datafile.py
Added a rename_all_packages method to the mf6 model and simulation classes which renames all the packages to a single name with a unique extension. If extensions are not unique, a suffix is added to the name to make the full file name unique.
Also added support for copy of mf6 simulation/model/package/data objects. Copy works for all objects but deepcopy sometimes does not always copy subpackages correctly. This problem may be a bug with how deepcopy handles multiple references being kept around to a single object.
=> feat(mf6 rename all packages method + copy support)

autotest/t011_test.py, examples/data/mfusg_test/03B_conduit_unconfined/ex3B.nam, examples/data/mfusg_test/03B_conduit_unconfined/ex3B.wel, examples/data/mfusg_test/03B_conduit_unconfined/output/ex3B.lst, flopy/utils/mflistfile.py
Adds a method to the ListBudget class to read in data from the list file on automatic reductions to WEL extractions. This method supports both NWT and USG list files. Adds auto tests for both success and failure. I couldn't find any included data sets with reductions written to the LST, so I updated a USG data set to allow for the auto test.
=> Read WEL Reductions from List File

flopy/seawat/swtvdf.py
Default densemin and densemax set to zero, which means they are not active.
=> refactor(vdf): shut off density limiters as default

autotest/t012_test.py, flopy/mt3d/mtbtn.py
* Pass options from load method to class constructor
* Correct case for "ALTWTSORB" case
* Show verbose message for optional keywords
* Add a unit tests to check options
=> fix(mtbtn): options from load method ignored

examples/Tutorials/Tutorial02/tutorial02.py
=> fix(tutorial2): zorder keyword in clabel no longer supported

autotest/t007_test.py, flopy/mbase.py, flopy/modflow/mfdis.py
=> Fix(SpatialReference): fix coordinate information being passed to SpatialReference

autotest/t017_test.py, flopy/modflow/mfsfr2.py, flopy/utils/binaryfile.py
Here are the primary changes in this PR, related to the Head/CellBudget file readers:
* Allow Head/CellBudgetFile to be opened/closed in a ['with' statement](https://docs.python.org/3/reference/compound_stmts.html#with) which closes the file automatically when done or if an exception is raised
* Raise TypeError if CellBudgetFile.get_data() is called without arguments -- previous behavior raised a different and distracting exception
* Document and test idx as either an int or list of integers -- this is not a new behavior
* Close a few file handles in the test suite
An unrelated commit fixes a typo for a variable name in a docstring for ModflowSfr2
=> Add feature to allow 'with' context statement to read Head/CellBudget files

autotest/t011_test.py, flopy/utils/gridintersect.py, flopy/utils/mflistfile.py
While Python 2 is still supported, fix this issue:
```
Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 15:42:17) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import flopy
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "flopy\__init__.py", line 33, in <module>
from . import modflow
File "flopy\modflow\__init__.py", line 1, in <module>
from .mf import Modflow
File "flopy\modflow\mf.py", line 14, in <module>
from ..mbase import BaseModel
File "flopy\mbase.py", line 24, in <module>
from flopy import utils, discretization
File "flopy\utils\__init__.py", line 48, in <module>
from .gridintersect import GridIntersect,ModflowGridIndices
File "flopy\utils\gridintersect.py", line 7, in <module> …
```
=> fix(Python 2): use a few aliases for exceptions

.travis.yml, travis/before_script.sh, travis/install.sh, travis/script.sh
* Replace `TVER` with `RUN_TYPE` with either "test" or "misc" (for other tests, like pylint and notebook tests)
* Remove Python 3.7-dev and leave commented-out 3.8-dev, when ready
* Move/refactor version showing to `before_script` hook
* Move pylint to script section, with pylint-exit to handle exit code
* `PATH` already has `$HOME/.local/bin` but this directory needs to be created
The `install.sh` script installs the dependencies, which are different for the different build types and Python version. The `before_script.py` shows the paths and much of the version numbers of various components. The main part of the testing is in `script.sh`. Currently, `after_success` is a single command to `coveralls`.
A few other minor details are that "export CXX="g++"", "NO_NET=1" and "python-pip" are …
=> refactor(travis): use script files rather than awkward YAML file

.flake8, travis/install.sh, travis/script.sh
This PR reviews Python errors and code styles, and shows them in the "misc" Travis CI build (now done before Notebook tests). This complements pylint checks also done in that build.
This highlights obvious bugs like:
./flopy/modflow/mfde4.py:274:24: F821 undefined name 'tline'
it also shows many other non-bugs like whitespace warnings. Most of these are ignored, in the `.flake8` file, as they aren't that important. Currently, this tool does not fail the build, via `--exit-zero`.
Anyone can run this locally too, just type `flake8` from the base source directory.
Some other minor adjustments in this PR is to fine-tune the `pip install` commands to install components quicker. Also, pylint can now fail a build (currently it does not).
=> Check Python code with flake8

autotest/t013_test.py, autotest/t022_test.py, flopy/mf6/utils/generate_classes.py, flopy/modflow/mfde4.py, flopy/modflow/mfsms.py, flopy/modflow/mfstr.py, flopy/mt3d/mtphc.py, flopy/utils/mflistfile.py
This PR fixes a collection of bugs related to flake8's F821 error class, which is often a cause of bugs while running Python code. Where feasible, tests are added or adjusted. Individual commits describe each fix.
=> Resolve bugs related to F821 undefined name 'name'

autotest/t007_test.py, autotest/t031_test.py, autotest/t044_test.py, autotest/t045_test.py, autotest/t046_test.py, autotest/t048_test.py, autotest/t049_test.py, flopy/pest/__init__.py
This PR fixes a collection of bugs related to flake8's F811 error class.
```
$ flake8 --select=F811
./flopy/pest/__init__.py:4:1: F811 redefinition of unused 'Util3dTpl' from line 1
./autotest/t007_test.py:1217:1: F811 redefinition of unused 'test_export_array' from line 304
./autotest/t048_test.py:39:9: F811 redefinition of unused 'pymake' from line 9
./autotest/t046_test.py:37:9: F811 redefinition of unused 'pymake' from line 8
./autotest/t031_test.py:27:1: F811 redefinition of unused 'ra_slice' from line 14
./autotest/t049_test.py:37:9: F811 redefinition of unused 'pymake' from line 9
./autotest/t044_test.py:38:9: F811 redefinition of unused 'pymake' from line 9
./autotest/t045_test.py:37:9: F811 redefinition of unused 'pymake' from line 8
```
For example, in `t007_test.py` there were …
=> Resolve bugs related to F811 redefinition of unused 'name'

autotest/t027_test.py, autotest/t066_test_copy.py, flopy/export/utils.py, flopy/mbase.py, flopy/modflow/mf.py, flopy/modflow/mfsfr2.py, flopy/mt3d/mt.py, flopy/seawat/swt.py, flopy/utils/check.py, flopy/utils/util_list.py
Changes to attribute handling that allow most flopy object instances to be copied with `copy.deepcopy()`. Mostly resolves issue #591, except for the caveats that @spaulins-usgs [mentioned](https://github.com/modflowpy/flopy/issues/591). Copying may work in python 2.7 but is not supported.
=> support for copy.copy() and copy.deepcopy() with python 3.5+

flopy/utils/gridintersect.py
This should allow flopy to be loaded even if shapely isn't installed.
Closes #697
=> refactor(gridintersect): wrap shapely imports in try/except

flopy/modflow/mfsfr2.py, flopy/mt3d/mtlkt.py, flopy/mt3d/mtsft.py, flopy/mt3d/mtuzt.py, flopy/utils/check.py, flopy/utils/flopy_io.py, flopy/utils/mtlistfile.py
Some of these fixes were to LaTeX in docstrings or paths to directories in the examples, which were updated to somewhat work with the current structure of directories and file names.
This will also remove a warning:
> DeprecationWarning: invalid escape sequence \s
>    raise Exception("MfList error: '\str\' type found it dtype." + \ ...
=> fix(flake8 code W605): invalid escape sequence '\s' (or similar)

autotest/t032_test.py, flopy/export/shapefile_utils.py
This is largely a re-do of #422, but for the (now) supported `EpsgReference` class, which was untested and had several bugs that limited it's operation as expected.
t032_test.py swaps from `epsgRef` (now deprecated) with `EpsgReference`, with a few more checks to ensure all the methods are working.
=> fix(EpsgReference): complete methods for expected operation

autotest/t009_test.py, flopy/utils/sfroutputfile.py
* Detect names for column 16 and beyond (checked against gwf2sfr7_NWT.f), which adds either 'gradient' or 'Qwt', 'delUzstor', sometimes 'gw_head'; note that this may affect users that used (e.g.) df.col16.values
* Remove methods that are used once: get_skiprows_ncols and _set_names, as this logic is best handled in the class constructor
* Add notes to docstring to indicate which columns have indexing starting at one or zero
* Expand docstring for parameters, verbose and geometry are ignored
* Flake8's F841 variable assigned but never used for 'per' and 'timestep'
* Flake8's F402 import 'np' from line 1 shadowed by loop variable
* Resolve sfroutputfile.py:170: RuntimeWarning: invalid value encountered in less: newper = df.segment.diff().values < 0
* Expand t009_test.py to check attributes: …
=> refactor(SfrFile): detect other column names, remove methods

autotest/t066_test_copy.py, autotest/t504_test.py, autotest/t505_test.py, examples/data/mf6/test005_advgw_tidal/AdvGW_tidal.ghb, flopy/mf6/data/mfdata.py, flopy/mf6/data/mfdatalist.py, flopy/mf6/mfpackage.py, flopy/mf6/modflow/mfsimulation.py
feat(#694): When stress packages have data for periods beyond nper flopy now issues a warning message (flopy use to raise an exception).
feat(#704): Allow user to set simulation name file options while initializing a simulation.
=> Allow Stress Periods Beyond Nper (#694) and Allow Setting Simulation Name File Options on Init (#704) 

flopy/modflow/mfsfr2.py
This PR is related to #313 but using `'{:.8g}'` to format floats for older NumPy versions (prior to version 1.14.0). The motivation behind this is to get similar sfr files (and result files) between different versions of NumPy. Modern NumPy versions still use `'{!s}'` and should not see any differences. Older NumPy is inconsistent, so use 8 digits of precision (based on [~7.2 decimal digits](https://en.wikipedia.org/wiki/Floating-point_arithmetic) for single precision floats).
Also, a global `mfsfr2.default_float_format` now exists, which is automatically set by the version of NumPy, but can be redefined by the user to (e.g.) write all floats with 16 decimal digits:
```python
import flopy
flopy.modflow.mfsfr2.default_float_format = '{:16g}'
```
=> refactor(mfsfr2): format floats as '{:.8g}' with older NumPy versions

flopy/mf6/data/mfdatastorage.py, flopy/mf6/data/mffileaccess.py, flopy/mf6/data/mfstructure.py, flopy/mf6/modflow/mfsimulation.py
MFList data structure now loads faster in more special cases where the data is adequately simple to code a faster load routine. Also optimized data verification code and added option to not verify data on load.
=> fix(#707): Loading Optimized for MFLists in Special Cases

autotest/t007_test.py, flopy/discretization/grid.py
This re-adds #622 refactor to remove the `; ` gap found in the metadata on the second line of the nam file. Also, values are formatted as native strings with `str()`, which generally does "the right thing".
E.g., before:
#xll:0; yll:0; rotation:0; units:undefined; lenuni:0; ; start_datetime:1-1-1970
after:
#xll:0.0; yll:0.0; rotation:0.0; units:undefined; lenuni:0; start_datetime:1-1-1970
=> refactor(namefile): format values as native strings and remove extra "; "

flopy/mf6/data/mffileaccess.py
fix(mflist optimization): The mflist optimization code crashed when a line contained a word that only contained quote characters. Fix implemented to handle this case.
=> MFList Crash Fix

autotest/t050_test.py, examples/Notebooks/flopy3_vtk_export.ipynb, flopy/export/utils.py, flopy/export/vtk.py
Flopy vtk export for array 2d/3d export, package export, model export, heads, cell by cell file.
export interface change added fmt option to specify 'vtk'
added examples/Notebooks/flopy3_vtk_export.ipynb a notebook for vtk export
created vtk tests in autotest/t050_test.py
=> feat(vtk) updated vtk export capabilities in flopy.  

flopy/mf6/utils/binaryfile_utils.py, flopy/mf6/utils/mfobservation.py, flopy/utils/gridintersect.py, flopy/utils/util_array.py, flopy/utils/util_list.py
Furthermore, with Python 3.8 raises `SyntaxWarning` as [seen with a Python 3.8 test](https://travis-ci.org/modflowpy/flopy/jobs/614263195#L1659), e.g.:
> flopy/flopy/mf6/utils/binaryfile_utils.py:360: SyntaxWarning: "is" with a literal. Did you mean "=="?
elif dtype is 'V':
...
this Python 3.8 warning is resolved with this PR.
=> fix(flake8 code F632): use '==' instead of 'is'

autotest/t007_test.py, flopy/modflow/mfdis.py
=> fix(ModflowDis.sr): rotate model prior to calculating xll and yll from xul and yul

flopy/modflow/mfmnw2.py
Resolves issue where mnw2 itmp list didn't include zeros for when a stress period had no discharge assigned. The "continue" advanced to the next iteration, missing the line where zero would be added to the itmp list. This was causing issues when rewriting a mnw2 file.
=> mnw2 missing itmp when zero

autotest/t021_test.py, flopy/utils/util_list.py
=> fix(mflist): fixed record shape in get_empty; test add_record

autotest/t505_test.py, flopy/mf6/data/mffileaccess.py
Fixed problem where boundnames did not get loaded for simple fast loads. Added test to catch problems similar to this in the future.
=> fix(boundnames): Fixed problem loading boundnames

flopy/mf6/data/dfn/gwf-csub.dfn, flopy/mf6/data/dfn/gwf-disu.dfn, flopy/mf6/data/dfn/gwf-lak.dfn, flopy/mf6/data/dfn/gwf-npf.dfn, flopy/mf6/data/dfn/sim-nam.dfn, flopy/mf6/modflow/__init__.py, flopy/mf6/modflow/mfgwfcsub.py, flopy/mf6/modflow/mfgwfdisu.py, flopy/mf6/modflow/mfgwflak.py, flopy/mf6/modflow/mfgwfnpf.py, flopy/mf6/modflow/mfims.py, flopy/mf6/modflow/mfnam.py, flopy/mf6/utils/createpackages.py
Please check that these dfn updates are ok. Also running the `update_flopy.py` script in mf6/autotest/ wanted to make change in `mfgwf.py`
Not sure if something needs to be modifies on the flopy side to retain the `load_only` keyword in the `mfgwf` class.
=> fix(dfns): update MODFLOW 6 dfns for next flopy (3.3.0) and mf6 (6.1.0) releases

autotest/t060_test_lkt.py, autotest/t068_test_ssm.py, flopy/mt3d/mtssm.py, flopy/pakbase.py, flopy/utils/util_list.py
Mflist did not allow a stress_period_dictionary to have None or -1 as a valid entry for a stress period.  But MODFLOW and MT3D do allow this.  Mflist was refactored so that a stress period dictionary could be spd = {0: None, 1: -1} or other combinations on this.  This is necessary for the mt3d ssm package, but it also was necessary for loading a valid well file that might have ITMP = -1 for all stress periods.  This would be a strange case for MODFLOW, but ITMP values of -1 for the first stress period of a wel package is valid for MODFLOW.
* cleanup of t060_test_lkt.py
*  cleanup of t068_test_ssm.py
* new test added to t068_test_ssm.py
=> fix(Mflist): allow None as a list entry

flopy/mf6/mfmodel.py
When a second package of the same type is added to a model, the model now checks to see if the package type supports multiple packages. If it does not it automatically removes the first package before adding the second (#767).
=> fix(replace package): fix for issue #767

autotest/t505_test.py, flopy/mf6/mfpackage.py, requirements.travis.txt
Repeating blocks with the same block name but different header were not being read correctly in some cases of the observation package's continuous block. Flopy now properly distinguishes between these repeating blocks.
Additionally, requirements.travis.txt changed to exclude netcdf v.1.5.3 from all versions of python.
=> fix(repeating blocks)

flopy/utils/gridgen.py
* added a more robust method for determining cell centers for rotated grids
* closes #782
=> fix(gridgen): x, y center was not correct for rotated grids

autotest/t007_test.py, autotest/t012_test.py, flopy/export/utils.py, flopy/modflow/mf.py, flopy/pakbase.py, flopy/plot/map.py, flopy/plot/plotbase.py, flopy/plot/plotutil.py
* fixed bug with mf2k loading #802 
* added shapefile support for output_helper #807 
* updated test cases
=> Update(plot_bc): Updated for advanced packages in MF6

examples/Notebooks/flopy3_MT3DMS_examples.ipynb
In the MT3DMS manual, constant heads are specified along the top and bottom boundaries, not just the sides within problem 10 (see pg 158 of manual)
=> fix(flopy3_MT3DMS_examples.ipynb): match constant heads to original 

examples/Notebooks/flopy3_MT3DMS_examples.ipynb
4th plot of p10 was showing concentration @ 750 days for layer 4, not concentration @ 1,000 days for layer 3 as labels indicate
=> fix(flopy3_MT3DMS_examples.ipynb): incremental change to 4d np array indices swapped

autotest/t006_test.py, autotest/t007_test.py, autotest/t009_test.py, autotest/t015_test.py, autotest/t070_test_spedis.py, examples/Testing/testunitcbc.py, flopy/discretization/grid.py, flopy/discretization/structuredgrid.py, flopy/discretization/unstructuredgrid.py, flopy/discretization/vertexgrid.py, flopy/mbase.py, flopy/mf6/modflow/mfgwfnpf.py, flopy/modflow/mffhb.py, flopy/modflow/mflpf.py, flopy/modflow/mfoc.py, flopy/plot/map.py, flopy/plot/plotbase.py, flopy/plot/plotutil.py, flopy/utils/postprocessing.py
One may want to allow flow through boundaries instead of treating boundary stresses as an internal source/sink (behavior until now). This is made possible by new post-processing and plotting functions.
The idea is best illustrated with a simple example from tutorial 1. Until now, plotting the specific discharge would give:
Notice that the arrows in the first and last columns are half of the other ones; this is because boundary faces are implicitly always treated as no flow. With what I developed, we can assign the flow from/to constant head cells to boundary faces, and thus get:
The essential lines to get the latter figure with the new functions are:
```python
consthead_ifaces = []
xlow_iface = 1
xhigh_iface = 2
for row in range(nrow):
consthead_ifaces.append([0, row, 0, xlow_iface]) …
```
=> Budget and specific discharge when stresses applied along boundaries

flopy/export/netcdf.py, flopy/utils/reference.py
Fixes a pyproj regression that appeared in version 2.6.0 (spotted in #836). It seems that the `errcheck` keyword option is not used, despite being documented. It is probably best left out.
Note this is a basic patch to get past the new error. There are several other improvements that could be implemented using pyproj versions >= 2.2.0, which support a CRS class, better transformation pipelines, among other improvements. The old `Proj` class is getting stale.
=> fix(pyproj): pyproj.Proj's errcheck keyword option not reliable

autotest/t050_test.py, flopy/discretization/grid.py, flopy/discretization/structuredgrid.py, flopy/export/utils.py, flopy/export/vtk.py
I implemented the export of data to ImageData (.vti) or RectilinearGrid (.vtr) formats when possible, instead of always UnstructuredGrid (.vtu), since this can greatly reduce file volume and speed up subsequent operations (e.g. in Paraview). The user can also choose to force an export to a specific format (e.g., .vtu) by using the new parameter vtk_grid_type (by default = 'auto').
I made significant improvements to the vtk export code and fixed a number of issues along the way. These are in fact beneficial regardless of my initial intention. For better readability, I arranged my contribution into two commits: the first one only contains independent code improvements and fixes, and the second one actually contains the new feature. If possible, I think it would be better to keep the two …
=> vtk export: .vti and .vtr formats (#833), code improvements and fixes

autotest/t050_test.py, flopy/export/vtk.py
This PR contains two commits.
The first commit fixes a few issues related to nan values and type cast.
The second commit implements the possibility to export vectors (e.g. hydraulic gradient, groundwater velocity...) to vtk (new function vtk.export_vector).
=> vtk export: a few fixes and a new functionality (export vector)

flopy/modflow/mflmt.py
redo of #839, but this time PR'ing on dedicated branch
=> fix(mflmt.py): Clean up docstring for package_flows argument in LMT

flopy/export/netcdf.py
This was mentioned in #837 to use some modern features of pyproj versions, which I've declared as version 2.2.0 when the parameter `always_xy` was added.
With older pyproj versions, continue to use the older Proj class, which has limitations best described with the [PROJ docs](https://proj.org/development/migration.html#background). This may result in some coordinate transformation discrepancies between versions, but probably too small to discern with most groundwater models.
Currently, pyproj is only used for netcdf exports. More integration with pyproj should be done in flopy/utils/reference.py which can be done later.
=> feat(netcdf): use modern features from pyproj>=2.2.0

flopy/modflow/mfchd.py
Loading a mf-model, the CHD.chk file was always written, also wich the check-variable set to false.
For this reason the check-parameter is now added to the mfchd.load method and passed to the Package.load method.
=> Update mfchd.py, prevent write chk-file always

flopy/mf6/data/mfdatastorage.py, flopy/utils/datautil.py
MFArray aux variable now always returned as an numpy.ndarray. Fixed problem with PyListUtil not fully supporting numpy.ndarray type.
=> fix(#886): MFArray aux variable fix

flopy/__init__.py, flopy/utils/gridintersect.py, flopy/version.py, release/make-release.py, setup.py
Import of __version__, __name__, and __author__ from flopy caused
failure of setup.py because of dependency of flopy on numpy with
python installations that did not already have numpy installed. Moved
all information needed by setup.py to version.py and update
make-release.py to retain __name__, __author__, and __author_email__
information in file after updating version numbers. Removed unintended
unmanaged dependency on matplotlib in gridintersect.py by wrapping
import in a try and except. In the case that matplotlib is not installed
and methods that depend on matplotlib are called then a
ModuleNotFoundError exception is issued.
Closes #892
=> fix(setup.py): read package name, version, etc. from version.py

setup.py
Make installable in a clean environment. Before `flopy.__init__.py` was implicitly loaded and leads to an import of numpy (which could be not installed before installation) See #892
=> fix building in clean env

flopy/mf6/modflow/mfsimulation.py
A recent change was made to allow case insensitive model names to be added to IMS solutions.  This change broke some previous functionality.  This PR simply checks to make sure that .lower() is not applied to None.
=> fix(mfsimulation): repair change for case insensitive model names

README.md, flopy/version.py, release/make-release.py
=> refactor(make-release): Software citation developed from version.py

flopy/mf6/utils/generate_classes.py
Currently when flopy is imported, a message is printed to stdout: `flopy is installed in /path/to/flopy`.
Normally, Python packages do not print messages to stdout when they are imported, so this PR removes this behaviour.
Anyone that would like to show this message in their workflow can use the following:
```python
import os
import flopy
print('flopy is installed in ' + os.path.dirname(flopy.__file__))
```
=> Remove message "flopy is installed in ..."

flopy/export/utils.py, flopy/utils/gridintersect.py
Fixes #932 using the "easy" option, keeping Python 3.5 compatibility.
`ModuleNotFoundError` [was introduced for Python 3.6](https://docs.python.org/3/whatsnew/3.6.html#other-language-changes), and is a subclass of `ImportError`.
When flopy sets a minimum version of Python 3.6+, these can be renamed back to `ModuleNotFoundError`.
=> Restore Python 3.5 compatibility (ModuleNotFoundError→ImportError)

flopy/mf6/data/mfdataarray.py, flopy/mf6/data/mfdatalist.py, flopy/mf6/data/mfdatascalar.py, flopy/mf6/data/mffileaccess.py, flopy/utils/datautil.py
Speeds up performance when a large number of time series are used by a single stress package.
Fixes problem where partially commented line is not read correctly by flopy.
=> fix(time series slowness): time series data speed up

flopy/mf6/data/dfn/gwf-evta.dfn, flopy/mf6/data/dfn/gwf-rcha.dfn, flopy/mf6/data/mfdata.py, flopy/mf6/modflow/mfgwfevta.py, flopy/mf6/modflow/mfgwfrcha.py, flopy/mf6/utils/createpackages.py
fix for issue #941.  also changed createpackages.py to always produce python scripts with unix-style line endings.
=> fix(rcha and evta): irch and ievt arrays now zero based

flopy/modflow/mfsfr2.py
``find_path()`` uses recursion to trace a path through the SFR network (possibly not the best approach, but it works). We don't want it to produce side effects on the input routing dictionary, but we also don't want it to make a copy with every call, which is what it was doing. This was severely impacting performance for large SFR networks, for the routing checks and probably other uses as well.
=> wrap mfsfr2.find_path() so that the routing dictionary won't be copied with every recursive call

autotest/t504_test.py, flopy/mf6/data/mfdatautil.py, flopy/mf6/data/mffileaccess.py, flopy/mf6/mfpackage.py
* flopy does no longer errors on extraneous package data, instead it is stored as comments
* flopy no longer errors on jagged data in a list with size zero
=> fix(extraneous blocks and zero length data in a list) 

flopy/utils/gridintersect.py
=> Quick fixes for gridintersect using linestrings and structured grid

autotest/t073_test_cvfd.py, flopy/utils/cvfdutil.py
The modflow6 disv constructor in flopy needs a list of vertices and cell2d information.  The flopy.util.cvfdutil package was updated to include a new method that takes a list of flopy.discretization.structuredgrid.StructuredGrid objects and   stitches them together to create a dictionary of arguments that can be passed info flopy.modflow6.ModflowGwfdisv.  For nested grids, idomain must be set to zero in any parent grids in order for the child grid to be patched in properly.  This new tool can be used to construct vertices and cell2d information needed to make disv nested grids.
=> feat(cvfdutil): capability to create disv nested grids

autotest/t006_test.py, autotest/t007_test.py, autotest/t009_test.py, autotest/t031_test.py, autotest/t061_test_gridgen.py, autotest/t504_test.py, autotest/t505_test.py, autotest/t550_test.py, flopy/export/shapefile_utils.py, flopy/utils/geometry.py, flopy/utils/gridgen.py
* With `flopy.export.shapefile_utils.import_shapefile`, add argument `check_version` (with default `True`). Functions that only need `shapefile.Reader` can have `check_version=False`, but `shapefile.Writer` needs pyshp version 2 (or later). `ImportError` is raised if shapefile module is not found, or major version is less than 2 (with `check_version=True`). Also, a better message is shown to help issues like #1000
* Skip tests that require pyshp>=2
=> refactor(shapefile): add check_version for pyshp>=2; skip tests

autotest/t007_test.py, flopy/export/netcdf.py, flopy/utils/reference.py
This is a minor extension to #840 that is mainly for the benefit of users with pyproj<=1.9.6, which needs "+init=" to be prepended to (e.g.) "epsg:4326" (otherwise the error is "RuntimeError: b'no arguments in initilization list'"). It is harmless for pyproj>=2.0.0 to 2.2.0, but this syntax is now deprecated, which is why it's not used with newer pyproj versions.
Some other related changes added in this PR:
* For `test_dis_sr`, remove use of deprecated SpatialReference object which cannot parse "us-ft" units from older pyproj versions. This test works fine with supported StructuredGrid module.
* And for deprecated reference module, tidy up one "to_meter" error
=> refactor(pyproj): for versions before 2.2.0, prepend "+init=" to epsg ids

flopy/discretization/structuredgrid.py
This patches the flip function for numpy versions before 1.15.0 (released 24 Jul 2018). The modern `np.flip(m, axis=None)` function signature is used in a few recent flopy modules, which raise 13 errors in the autotest suite with older numpy releases (either "TypeError: flip() missing 1 required positional argument: 'axis'" or "TypeError: list indices must be integers or slices, not list"). These errors are resolved with the patched function.
For reference, compare `np.flip` when it was changed:
* https://github.com/numpy/numpy/blob/v1.14.6/numpy/lib/function_base.py#L202-L210
* https://github.com/numpy/numpy/blob/v1.15.0/numpy/lib/function_base.py#L228-L238
=> refactor(numpy): patch modern flip function for versions older than 1.15.0

autotest/t506_test.py, flopy/modflow/mflpf.py
Add writing of IKCFLAG to mfusg unstructured models' LPF package.
This was not previously written, which resulted in all flavours of mfusg
throwing an error on LPF load for unstructured models, if any keywords were
specified. No other model types are affected by this change.
Add test to existing t506_test.test_mfusg.
=> fix(modflow/mflpf) mfusg unstructured lpf ikcflag addition

flopy/discretization/structuredgrid.py, flopy/utils/utils_def.py
Two unrelated NumPy DeprecationWarnings are fixed in this PR:
* Passing None into shape arguments as an alias for () is deprecated. See [NumPy 1.20.0 Release Notes](https://numpy.org/devdocs/release/1.20.0-notes.html#passing-shape-none-to-functions-with-a-non-optional-shape-argument-is-deprecated).
* tostring() is deprecated. Use tobytes() instead. See [NumPy 1.19.0 Release Notes](https://numpy.org/devdocs/release/1.19.0-notes.html#numpy-ndarray-tostring-is-deprecated-in-favor-of-tobytes).
=> fix(DeprecationWarning): related to numpy

flopy/mf6/mfbase.py
The main fix addresses an upcoming change:
```
/path/to/flopy/flopy/mf6/mfbase.py:680:DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
if not isinstance(load_only, collections.Iterable):
```
The other change is just to simplify an import from a related module.
=> Re-organize imports from collections and collections.abc

.flake8, flopy/mf6/data/mfstructure.py, flopy/mf6/modflow/mfgwf.py, flopy/mf6/modflow/mfgwfgwf.py, flopy/mf6/modflow/mfgwflak.py, flopy/mf6/modflow/mfgwfmaw.py, flopy/mf6/modflow/mfgwfnam.py, flopy/mf6/modflow/mfgwfnpf.py, flopy/mf6/modflow/mfgwfsfr.py, flopy/mf6/modflow/mfgwfsto.py, flopy/mf6/modflow/mfgwfuzf.py, flopy/mf6/modflow/mfgwt.py, flopy/mf6/modflow/mfgwtnam.py, flopy/mf6/modflow/mfims.py
This tidies up a few DeprecationWarning messages from docstrings, and expand LaTeX commands like `\mf` to MODFLOW 6.
Flake8's W605 can be removed.
=> fix(createpackages): avoid creating invalid escape characters

autotest/t007_test.py, flopy/plot/plotutil.py
Previous behavior assumed that `.plot()` on a util3d object had as many layers as `model.modelgrid.nlay`. However, this isn't always correct, e.g. with BCF's vcont dataset, which is `nlay - 1`:
https://github.com/modflowpy/flopy/blob/aca1446da05728d3119da195dde8ef87055dfe57/flopy/modflow/mfbcf.py#L209-L217
this would cause `ml.bcf6.vcont.plot()` (or `ml.plot()`) to raise "IndexError: list index out of range"
---
Also improved `test_model_dot_plot` to complete in ~2ish seconds instead of ~22 seconds (compare 20 plots in a smaller model to previous 226 plots from a more complex model). The return object from `.plot()` is also checked, as this is either a list or plt.Axes object, depending on the number of plots.
=> fix(plotutil): number of plottable layers should be from util3d.shape[0]

autotest/t505_test.py, flopy/mf6/data/mfdatalist.py
Fix for issue #1080.  MFList's get_file_entry no longer includes "None" text for empty stress periods when an aux variable is present.
=> fix(get_file_entry): "None" text removed from empty stress period data with aux variable (#1080)

flopy/modpath/mp7particledata.py
change dtypein comparison against dtype variable. dtypein was being compared against itself thus partlocs dtype didn't update
=> fix(mp7particledata): update dtype comparison for unstructured partlocs

flopy/utils/geospatial_utils.py, flopy/utils/gridintersect.py
Shapely 1.8 is in the pre-release stage, and has several deprecation warning messages. Some of these are in preparation for shapely 2.0, which has some breaking changes.
This PR aims to fix the ones that are revealed from the autotest suite. The context manager `ignore_shapely_warnings_for_object_array` is used to silence false-positive warnings when assigning shapely geometries to object arrays. It shouldn't be used for other legitimate deprecation warnings.
=> fix(shapely): handle deprecation warnings from shapely 1.8

autotest/t009_test.py, flopy/modflow/mfsfr2.py
* blank lines were previously written to file in the case of isfropt = 2 or 3 and icalc >= 2
* updated t009_test.py to check for this issue
=> Fix(mfsfr2.py): dataset 6b and 6c write routine, remove blank lines

flopy/plot/crosssection.py, flopy/plot/map.py, flopy/utils/rasters.py
This is a re-do of #1052 for changes from #1078.
=> fix(numpy): aliases of builtin types is deprecated

autotest/t049_test.py, flopy/plot/crosssection.py, flopy/plot/plotutil.py
* fix for mulitlayer grids
* added test_pathline_plot_xc to t049_test.py
#1108
=> fix(plot_pathline): update modpath intersection routines 

autotest/t007_test.py, flopy/discretization/grid.py, flopy/discretization/structuredgrid.py, flopy/discretization/unstructuredgrid.py, flopy/discretization/vertexgrid.py, flopy/plot/map.py
*changed plotting routines to use QuadMesh and PathCollection 
*fixed get_coords() issue with integer arrays
#1117 #1113
=> fix(map.py): fix slow plotting routines 

flopy/discretization/grid.py, flopy/plot/plotutil.py
* update docstrings in Grid() class
#1132 
#1119
=> fix(plotutil.py, grid.py): fix .plot() method using mflay parameter

autotest/t007_test.py, autotest/t031_test.py, autotest/t550_test.py, examples/Notebooks/flopy3_modpath7_structured_example.ipynb, examples/Notebooks/flopy3_shapefile_features.ipynb, flopy/discretization/unstructuredgrid.py, flopy/export/shapefile_utils.py, flopy/mbase.py, flopy/modflow/mfdis.py, flopy/modflow/mfdisu.py, flopy/modflow/mfsfr2.py, flopy/utils/__init__.py, flopy/utils/binaryfile.py, flopy/utils/datafile.py, flopy/utils/mfgrdfile.py, flopy/utils/modpathfile.py, flopy/utils/postprocessing.py, flopy/utils/reference.py, flopy/utils/util_array.py, flopy/utils/util_list.py, flopy/utils/zonbud.py
The following from `flopy.utils.reference` have been deprecated since flopy 3.2.11, and are planned to be removed in version 3.3.5:
* Classes: `SpatialReference`, `SpatialReferenceUnstructured`, `epsgRef`, `crs`
* Functions: `getprj`, `get_spatialreference`, `getproj4`
Edits related to these deprecation include:
* Document deprecation in docstrings / sphinx directives
* Remove or limit imports to the deprecated classes/functions, including from `flopy.utils` module
* Use functions from `.modelgrid` instead of `.sr`, where appropriate
* Fix `AttributeError` while attempting to get non-existing `.modelgrid.sr` or `.mg.sr`
* Tidy/update docstrings that incorrectly referred to 'sr'
* Remove stale commented code that uses `SpatialReference` objects
* Update `flopy3_shapefile_features.ipynb` …
=> refactor/fix: further enforce deprecations from flopy.utils.reference

autotest/t016_test.py, flopy/modflow/mf.py, flopy/modflow/mfbas.py, flopy/modflow/mfdisu.py, flopy/pakbase.py, flopy/utils/__init__.py, flopy/utils/check.py
mfusg file checking did not previously work
* add get_neighbors function clause for mfusg unstructured grids (in check class, but not mf6check)
* add modflow/mfdisu/_get_neighboring_nodes function
* fix pakbase/_check_flowp hk and vka for unstructured cases
* modify modflow/mfbas/check function to cater for mfusg unstructured grids, in addition to
structured modflow grids
* modify t016_test.py to cater for modflow/mfdisu/_get_neighboring_nodes function
Resolves #1072, although issues still need to be addressed to enable loading RCH and EVT, so users will need to use "load_only=[]" to avoid trying to load those for now.
=> fix(utils/check) file check for mfusg unstructured models

flopy/utils/rasters.py
=> fix(Raster): update default dtypes to include unsigned integers

flopy/modflow/mfdis.py, flopy/modflow/mfhob.py
* reduced repetitive totim array generation for performance improvement
* Added a use_cached_totim flag to get_totim, get_kstp_kper_toffset, get_totim_from_kper_toffset methods in ModflowDis
* update provides ~12x speedup in HOB package loading
=> update(ModflowHob, ModflowDis): Improve HOB file performance

autotest/t065_test_gridintersect.py, flopy/utils/rasters.py
Added `extrapolate_edges` option to `resample_to_grid` method to use
`nearest` interpolation method to fill cells outside data bounds. This
option results in an array that is completely filled with data (no nans).
=> feat(raster): add option to extrapolate using ``nearest`` method

flopy/modflow/mfsfr2.py
While the previous format of "reach_connection_gaps.chk.csv" was a text file, it was not well formatted.
This PR writes the numpy recarray as a conventional CSV file.
=> fix(mfsfr2.check): make "reach_connection_gaps.chk.csv" a normal CSV file

flopy/utils/sfroutputfile.py
According to [pandas.read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) for `error_bad_lines`:
> Deprecated since version 1.3.0: The `on_bad_lines` parameter should be used instead to specify behavior upon encountering a bad line instead.
The refactor in this PR works for old and new pandas version.
=> refactor(pandas.read_csv): the error_bad_lines arg has been deprecated

autotest/t504_test.py, autotest/t505_test.py, flopy/mf6/data/mfdataarray.py, flopy/mf6/data/mfdatalist.py, flopy/mf6/data/mfdatastorage.py, flopy/mf6/mfbase.py, flopy/mf6/mfmodel.py, flopy/mf6/mfpackage.py, flopy/mf6/modflow/mfsimulation.py, flopy/utils/datautil.py
WARNING: This PR may break existing flopy for MF6 scripts that change simulation or model paths.  Data is now automatically stored internally when simulation or model paths are changed.  This is to greatly simplify the code for handling paths.  Data can be set back to external after changing paths, either individually, or by using the "set_all_data_external" method.
New simulation and model method "set_all_data_internal" added that sets all data internal. This method is automatically called whenever the simulation or model path are changed. This greatly simplifies flopy's behavior since flopy no longer needs to keep track of former and new external file paths that can possibly change multiple times before write is called.
=> feat(data storage): Data automatically stored internally when simulation or model relative path changed (#1126)

autotest/t015_test.py, flopy/utils/flopy_io.py
flopy_io.write_fixed_var could write a fixed point string (f) that
exceeded the specified fixed column width. Added test to revert to
general format (g) with precision equal to column width - 6 to preserve
as much precision as possible. This value allows for a string with a
sign (+/-) and +/-e307. Added test for issue 1164 to t015_test.py
autotest.
Closes #1164
=> bug(flopy_io): limit fixed point format string to fixed column widths

flopy/discretization/grid.py, flopy/discretization/structuredgrid.py, flopy/discretization/unstructuredgrid.py, flopy/discretization/vertexgrid.py, flopy/plot/crosssection.py, flopy/plot/map.py, flopy/plot/plotutil.py, flopy/plot/styles.py, flopy/utils/check.py, flopy/utils/gridintersect.py, flopy/utils/voronoi.py
* grid: fix iverts and verts; expose laycbd for use in utilities
* plotting: add RuntimeError to matplotlib imports as fix for HTCondor/miniconda containerization issues
=> fix(grid, plotting): bugfixes for all grid instances and plotting code

autotest/t004_test_utilarray.py, flopy/utils/util_list.py
=> fix(loading mflist from file)

autotest/autotest_scripts.py, examples/Testing/flopy3_plotdata.py, examples/scripts/flopy_swi2_ex1.py, examples/scripts/flopy_swi2_ex2.py, examples/scripts/flopy_swi2_ex3.py, examples/scripts/flopy_swi2_ex4.py, examples/scripts/flopy_swi2_ex5.py, flopy/export/utils.py, flopy/export/vtk.py, flopy/mbase.py, flopy/mf6/data/mfdatastorage.py, flopy/pakbase.py, flopy/pest/params.py, flopy/pest/templatewriter.py, flopy/pest/tplarray.py, flopy/plot/plotutil.py, flopy/utils/binaryfile.py, flopy/utils/datafile.py, flopy/utils/datautil.py, flopy/utils/gridgen.py, flopy/utils/util_array.py, flopy/utils/util_list.py
As flopy is Python 3-only code (with the exception of a few old examples), clean-up Python 2 code:
- Python 2 used `next`, replaced by `__next__` in Python 3 ([PEP 3114](https://www.python.org/dev/peps/pep-3114/)); use the [`next()` built-in function](https://docs.python.org/3/library/functions.html#next)
- Python 2 had several `from __future__ import` statements, including `print_function` and `division`, which are [redundant](https://docs.python.org/3/reference/simple_stmts.html#future-statements) in Python 3
=> refactor: clean-up python 2 'next' and redundant '__future__' imports

autotest/t016_test.py, flopy/pakbase.py
=> fix(pakbase): specify dtype=bool for 0-d active array used for USG

autotest/t506_test.py, flopy/plot/map.py
In plot/map.py, with unstructured models, numpy throws "too many indices for array" error
when indexing plotarray with a tuple of boundary condition node numbers.
* Revert plotarray BC indices to stress_period_data list[kper]["node"] as-is for
unstructured models.
=> fix(plot/plot_bc) plot_bc fails with unstructured models

.github/workflows/ci.yml, .github/workflows/rtd.yml, etc/environment.yml, setup.py
Also set minimum NumPy version to >= 1.15. Add python 3.9 to
GitHub action workflows and remove python 3.6.
Closes #1176 Closes #1177
=> update(python): set python 3.7 as minimum supported version

README.md, flopy/discretization/structuredgrid.py, flopy/modflow/mfsfr2.py, flopy/utils/modpathfile.py, flopy/utils/util_list.py
xref #1177 (and older #322, #626, #710, #1004)
Also, amend README.md for #1176
=> refactor(numpy): remove support for numpy<1.15

flopy/pakbase.py
in pakbase/_check_storage.py, np.asarray() still throws an error when using a jagged list
for unstructured models
https://github.com/modflowpy/flopy/issues/1187#issuecomment-899509532
* change to np.concatenate jagged list to a flat array
close #1187
=> fix(pakbase) unstructured storage check (#1187)

autotest/t076_modelgrid_thick.py, flopy/discretization/grid.py, flopy/discretization/structuredgrid.py, flopy/modflow/mf.py, flopy/utils/postprocessing.py
* added Grid.remove_confining_beds()
* added test_ncb_thick() to t076_modelgrid_thick.py
=> fix(Grid.saturated_thick): update saturated_thick to filter confining bed layers

flopy/utils/gridintersect.py
This is a general fix for numpy>=1.21 with any version of shapely. The issue is described further at https://github.com/Toblerity/Shapely/issues/1173, and the warning is harmless.
Also refactor related shapely warnings from #1069
=> fix(numpy): handle deprecation warnings from numpy 1.21

flopy/mf6/coordinates/modelgrid.py, flopy/mf6/mfbase.py, flopy/plot/plotutil.py
This PR removes some unnecessary `Exception.__init__` calls when only a simple message is used. But where it is overloaded, use `super()` instead of directly calling the superclass.
The error message generation in MFDataException is simplified, and should generate the same information, but without a trailing `\n`.
=> refactor(exceptions): reduce redundancy, simplify message generation

autotest/t003_test.py, autotest/t017_test.py, flopy/mf6/mfpackage.py, flopy/mf6/utils/output_util.py, flopy/modflow/mf.py, flopy/modflow/mfoc.py, flopy/mt3d/mt.py, flopy/utils/binaryfile.py, flopy/utils/datafile.py, flopy/utils/flopy_io.py, flopy/utils/mfreadnam.py, flopy/utils/observationfile.py, flopy/utils/optionblock.py, flopy/utils/util_array.py, release/make-release.py
Since Python 3.3,  IO and OS exceptions were re-worked as per [PEP 3151](https://www.python.org/dev/peps/pep-3151/). The new main base class is [OSError](https://docs.python.org/3/library/exceptions.html#OSError), with several other exceptions merged, including IOError (i.e. `assert IOError is OSError`).
This PR changes the old IOError alias to OSError, with a few exceptions:
- A few exceptions that detected something wrong with the file contents (empty, could not determine the precision, etc.) should be reclassified as ValueError, since there was no issue with reading the file from the OS.
- Fixed a stray f-string in `flopy/modflow/mf.py` line 953
=> refactor(exceptions): reclassify IOError as OSError or other type

flopy/mf6/data/mfdatalist.py
No elementwise compare is needed if user passes in a numpy recarray, this is only necessary for dictionaries.
=> fix(numpy elementwise comparison): Fixed numpy FutureWarning

autotest/t007_test.py, flopy/export/utils.py
quick fix in export.utils.export_array(). 
Is this the preferred method for exporting rasters from model?
=> Think mg extent is x0,x1,y0,y1?

autotest/t027_test.py, flopy/export/netcdf.py
This PR refactors several things:
- Use [netCDF4's `sync()` method](https://unidata.github.io/netcdf4-python/#Dataset.sync) to write data to disk, which should avoid "NetCDF: Unknown file format" issues. This should be added at the end of methods that modify the netCDF file.
- Logger messages should now print one per line (using `print(..., end="")`, because the message already has `\n`)
- `NetCDF.__init__` should raise `ImportError` if python-dateutil is not installed, rather than print a message.
- Remove `_dt_str` private method, as it's only used once; rewrite to use [strftime format codes](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes)
- Show exceptions to logger messages, or [chain](https://docs.python.org/3/tutorial/errors.html#exception-chaining …
=> refactor(netcdf): sync data, revise logger and exceptions

autotest/t007_test.py, flopy/mf6/mfpackage.py, flopy/pakbase.py
* update to allow model to resync modelgrid when discretization or bas package is modified
* added test_mf6_modelgrid_update to t007_test.py
=> Fix(_mg_resync): Added checks to reset the modelgrid resync

flopy/utils/flopy_io.py
=> fix(io): read comma separated list

autotest/t501_test.py, flopy/mf6/data/mfdatastorage.py
Checking for model_relative_path already existing in external file filename, which will be the case when reading in a model. 
Will only append model_relative_path where not already present in file name. Should improve support for models using external file storage and simulations with models in sub directories. 
Should fix #1289 and possibly also #1115 and #1126
=> Hotfix subdirs

flopy/utils/geospatial_utils.py
* reorganized code order to enforce import checks
Closes #1303
=> fix(geospatial_utils.py): added pyshp and shapely import checks to geospatial_utils.py

autotest/pytest.ini, autotest/t069_test_vtkexportmodel.py, autotest/t075_test_ugrid.py, flopy/plot/crosssection.py, flopy/plot/plotutil.py, flopy/utils/flopy_io.py
* fixed t069_test_vtkexportmodel.py
* updated voronoi tests in t075_test_ugrid.py
* fixed ulstrd open/close read method for scale factors
Closes #1306
=> fix(autotests): added pytest.ini to declare test naming convention

flopy/plot/crosssection.py, flopy/plot/plotutil.py
=> fix(plot_pathline): sort projected pathline points by travel time instead of cell order

autotest/t505_test.py, flopy/mf6/data/mfdata.py, flopy/mf6/data/mfdataarray.py, flopy/mf6/data/mfdatalist.py, flopy/mf6/data/mfdatascalar.py, flopy/mf6/data/mfdatastorage.py, flopy/mf6/mfpackage.py
Getting array data (<data object>.array) fixed so that empty stress periods repeat data from the last previous stress period with data. If there is no previous stress period with data, None is used for MFDataList arrays and an array of zeros is used for MFDataArray arrays.
=> fix(array): getting array data (#1028)

flopy/utils/gridintersect.py
* this fixes flopy-CI linting failure
=> linting with updated version of black

autotest/t080_test.py, flopy/discretization/unstructuredgrid.py, flopy/discretization/vertexgrid.py, flopy/mf6/mfmodel.py, flopy/utils/gridintersect.py
Loading an mf6 DISU model with variable voronoi grid results in extraneous iverts entries
of None (Iverts appears to be a consistent (not jagged) shape). This results in a vertexdict
indexing error in UnstructuredGrid._build_grid_geometry_info when using plot() methods.
Filter out None entries from iverts in UnstructuredGrid._build_grid_geometry_info
=> fix(UnstructuredGrid)

autotest/t505_test.py, flopy/mf6/data/mfdata.py, flopy/mf6/data/mfdatascalar.py, flopy/mf6/data/mfdatastorage.py, flopy/mf6/data/mffileaccess.py, flopy/mf6/data/mfstructure.py, flopy/mf6/mfbase.py, flopy/mf6/mfpackage.py, flopy/mf6/modflow/mfsimulation.py, flopy/utils/datautil.py
Filenames with spaces in them now are read correctly from the package files and are written to the package file in quotes.  Test cases now include filenames with spaces.
=> fix(filenames): fixed how spaces in filenames are handled (#1236)

flopy/utils/gridgen.py
=> update(Gridgen): added keyword arguments for smoothing_level_vertical and smoothing_level_horizontal

autotest/t062_test_intersect.py, flopy/discretization/grid.py, flopy/discretization/structuredgrid.py, flopy/discretization/unstructuredgrid.py, flopy/discretization/vertexgrid.py
* implemented intersect method for UnstructuredGrid
Closes #1208
=> update(Grid.intersect): added optional z-coordinate to intersect() method

flopy/export/netcdf.py, flopy/utils/gridintersect.py
This resolves a new DeprecationWarning:
> flopy/flopy/utils/gridintersect.py:15: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
Version from flopy.utils.parse_version was vendored from pypa/packaging in #1262, so is suitable and convenient.
=> refactor(distutils): Version classes are deprecated, use internal class

flopy/mf6/data/mfdatalist.py, flopy/mf6/data/mfstructure.py
This fixes issues with flopy incorrectly determining that the mvr package has cellids.  This also fixes some cellid issues that could occur with the obs package.
=> fix(cellid): Fixes some issues with flopy properly identifying cell ids (#1335)

flopy/mf6/mfpackage.py
update `header_exists()`: when None is provided for key, do not check against block header names (significantly speeds OBS loading).
=> update(MFBlockHeader): fix for very slow loading of package OBS files when many blocks exist in OBS file

autotest/t505_test.py, flopy/mf6/data/mffileaccess.py
Previously, code read the entire file without stripping headers after first layer. Enforce read_multi_layer=True if data_size != ncpl
=> update(read_binary_data_from_file): update for binary layer files with multiple layers

autotest/t007_test.py, flopy/export/utils.py, flopy/plot/crosssection.py, flopy/plot/map.py
* added filled kwarg to contour_array for filled contours
* update PlotCrossSection.contour_array() to mask out edge triangles outside of cross-section boundaries
* update export_contourf, provide support for multipolygon contours and update support for holes
* update export_contourf, remove shapely dependency. Replaced with flopy geometry objects
* update t007_test.py, test_export_contourf()
=> update(contouring routines): updates for contour_array and export_contourf routines

flopy/mf6/data/mfdatalist.py, release/make-release.py
Resolve a few [flake8 errors](https://flake8.pycqa.org/en/2.6.0/warnings.html) identified with `flake8 --select=F821 .`:
```
./release/make-release.py:28:12: F821 undefined name 'author_dict'
./flopy/mf6/data/mfdatalist.py:1643:32: F821 undefined name 'layer'
```
A review by @spaulins-usgs for `flopy/mf6/data/mfdatalist.py` would be appreciated, as this was a guess.
=> refactor(flake8): F821 for 'undefined name' errors

flopy/mf6/modflow/mfsimulation.py
Add custom support so that the mover transport package in the GWT-GWT exchange can be managed from the simulation level.
=> feat(mvt): add simulation-level support for mover transport

autotest/t069_test_vtkexportmodel.py, flopy/discretization/structuredgrid.py, flopy/discretization/vertexgrid.py, flopy/export/vtk.py, flopy/mf6/data/mfdataarray.py
* update StructuredGrid.iverts and VertexGrid.iverts to only return vertex indices (consistent with UnstructuredGrid.iverts)
* update Vtk.iverts: check if ivert is closed polygon, if closed strip closing vertex 
* update t069_test_vtkexportmodel.py: add additional tests for VertexGrid and UnstructuredGrid models
Closes #1372
=> update(vtk): iverts compatibility updates for vtk

flopy/export/shapefile_utils.py
This raises a shutil error if the .prj file already exists and belongs to another user.
=> skip .prj copy if exists

MANIFEST.in
As noted in https://github.com/modflowpy/flopy/issues/1390#issuecomment-1085200752 the package build was missing `long_description`, because `docs/PyPI_release.md` was not included with the source distribution `MANIFEST.in`.
This fix includes all markdown files in `docs` with the source distribution.
=> fix(packaging): add docs/*.md to MANIFEST.in for sdist

autotest/t057_test_mp7.py, flopy/plot/map.py, flopy/utils/mflistfile.py
* update MfListBudget docstrings
Closes #1398
=> fix(plot_pathline): split recarray into particle list when it contains multiple particle ids

autotest/t034_test.py, flopy/modflow/mfuzf1.py
=> fix(ModflowUzf1): fix for loading negative iuzfopt

flopy/modpath/mp7bas.py, flopy/modpath/mp7sim.py
This pull request fixes a bug where the variable `zones` (and probably `retardation` as well, but I did not test this) cannot be supplied to the class `Modpath7Sim` for a model with a disv-discretisation. Right now this would generate the following error:
`ValueError: Util3d: expected 3 dimensions, found shape (nlay, ncpl)`
I copied some code from `Modpath7Bas` to make sure the supplied shape is 3d.
=> make sure shape in variables 'zones' and 'retardation' is 3d in Modpath7Sim

autotest/t034_test.py, flopy/modflow/mfuzf1.py, flopy/plot/crosssection.py, flopy/plot/map.py, flopy/plot/plotutil.py
* updates for plot_pathline()
* update test_034, test_uzf_negative_iuzfopt
Closes #1406
=> fix(ModflowUzf1): update load for iuzfopt = -1

autotest/t016_test.py, flopy/utils/util_array.py
mfusg layer-based properties can not be provided as a flat model-wide array.
-trap for flat mfusg property arrays in Util3d, convert to a (potentially jagged) list
-add test to t016: providing a flat property array to a package constructor
close #1427
=> fix(mfusg) flat arrays for layer-based properties

binder/environment.yml, etc/environment.yml, etc/requirements.full.pip.txt, etc/requirements.windows.pip.txt, requirements.txt
The `pyshp` package [was restricted](https://github.com/modflowpy/flopy/commit/2160ba6f049a91ba2ed28fc51bee851b92713f7c) to `<2.2.0` for CI issues some time ago. I also noticed [some test cases](https://github.com/modflowpy/flopy/blob/ea6a0a190070f065d74824b421de70d4a66ebcc2/autotest/t074_test_geospatial_util.py#L152) account for API changes introduced in `2.2.0`.
I am able to pass all the tests with `2.3.0`. Wondering if the `pyshp` version restriction can be lifted or if some more tests might be necessary to be sure of compatibility. ~~I will update this PR with more current info after the CI runs.~~ Looks like CI passes (excepting the outstanding Windows failures).
=> Lift pyshp version cap

autotest/t504_test.py, autotest/t505_test.py, flopy/export/shapefile_utils.py, flopy/export/utils.py
This PR updates `t504` and `t505` tests.
A few of the test cases were writing to `examples/data`, now they write to a temporary folder instead. This eliminates the need to e.g. `git clean -fd examples/data`. Also cleaned up a stray `examples` folder getting created in `autotests`.
=> Test teardown

autotest/conftest.py, autotest/conftest_test.py, autotest/pytest.ini, autotest/t007_test.py, autotest/t503_test.py
This PR introduces some shared `pytest` fixtures in `autotest/conftest.py`:
- keepable temporary directories
- paths to example data
- loading commonly used models/simulations from example data
`pytest` provides the [built-in `tmp_path` fixture](https://docs.pytest.org/en/latest/how-to/tmp_path.html#the-tmp-path-fixture) for function-scoped temporary directories, located in the [system's default base temporary directory](https://docs.pytest.org/en/latest/how-to/tmp_path.html#the-default-base-temporary-directory). By default, outputs from the last 3 test sessions are stored in this location, and `pytest` will automatically remove artifacts created by older sessions. This is not ideal for manually inspecting test outputs as the system temporary directory may be inconveniently located or …
=> Shared pytest fixtures

autotest/t039_test.py, autotest/t078_test_lake_connections.py, flopy/utils/postprocessing.py, flopy/utils/zonbud.py
* update `read_zone_file()` to allow for extraneous text after zone arrays are read
* update `get_specific_discharge()`; add error for "faces" and "vertices" option
* update pth to model_ws in `t078_test.test_base_run` to prevent autotesting from writing test output to examples directory
#1433
Closes #1340
=> update(utils): updates to zonbudget and get_specific_discharge

.github/workflows/rtd.yml, autotest/ci_prepare.py, autotest/test_scripts.py, docs/get_modflow.md, flopy/utils/__init__.py, flopy/utils/get_modflow.py, setup.cfg
This new features adds a console program with FloPy `get-modflow` (or `get-modflow.exe` for Windows), which automates installing MODFLOW and related programs from GitHub releases hosted at https://github.com/MODFLOW-USGS/executables or https://github.com/MODFLOW-USGS/modflow6-nightly-build
Features:
- Easy way to install MODFLOW and related programs on Windows, Mac or Linux
- The utility can be used as a console program installed with FloPy, or as a flopy module (`flopy.utils.get_modflow_main`)
- The script can be downloaded separately from FloPy with CC0 license, and run as any basic Python script
Here is what `get-modflow --help` currently shows:
```
usage: get-modflow [-h] [--repo {executables,modflow6-nightly-build}] [--release-id RELEASE_ID]
[--ostag {linux,mac,win32,win64}] …
```
=> feat: get modflow utility

.github/workflows/ci-windows.yml, .github/workflows/ci.yml, .github/workflows/rtd.yml, flopy/utils/get_modflow.py
A few bits extracted from #1458 to fix CI runs on macOS. This implementation requires [GITHUB_TOKEN](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) to be passed as an environment variable, as done within GitHub Actions. Bad tokens are also handled.
Closes #1059
=> fix(get-modflow/ci): use GITHUB_TOKEN to side-step ratelimit

DEVELOPER.md, autotest/conftest.py, autotest/regression/test_lgr.py, autotest/regression/test_mf6.py, autotest/regression/test_mf6_examples.py, autotest/regression/test_mfnwt.py, autotest/regression/test_modflow.py, autotest/regression/test_str.py, autotest/regression/test_swi2.py, autotest/regression/test_wel.py, autotest/test_example_notebooks.py, autotest/test_example_scripts.py, autotest/test_export.py, autotest/test_generate_classes.py, autotest/test_modflow.py, autotest/test_performance.py, autotest/test_specific_discharge.py, autotest/test_str.py
This is followup to #1458 including small fixes and tidying, updates to the benchmarking approach as well as developer documentation updates. Planning to add CI updates discussed yesterday in subsequent PRs.
A few tests were accidentally skipped, now included. `conftest.py` has been cleaned up, removing unused fixtures added during development.
Benchmarking is scoped back to include only the original set of performance tests (1458 included regression tests too) as testing model performance is probably not a flopy concern- only loading/writing models, etc.
Performance tests are moved back to their own file as well: `test_performance.py` now has what used to live in `t064_test_performance.py`.
The benchmarking section in `DEVELOPER.md` is updated to reflect `pytest-benchmark` and …
=> Update tests after feedback

flopy/utils/get_modflow.py
Hopefully resolves issues described in #1477. The strategy is to capture error code 404 and retry up to 3 times, particularly when `release_id` is valid. Also, GitHub [has a 10 second timeout](https://docs.github.com/en/rest/overview/troubleshooting).
=> fix(get-modflow/ci): handle 404 error to retry request from GitHub

.github/workflows/daily.yml, .gitignore, DEVELOPER.md, autotest/conftest.py, autotest/pytest.ini, autotest/regression/test_mf6.py, autotest/test_conftest.py, autotest/test_modflow.py, autotest/test_modpathfile.py, autotest/test_scripts.py, autotest/test_seawat.py
Performance profiling for `ModpathFile` methods (results [here](https://github.com/modflowpy/flopy/issues/1479)) and a few unrelated fixes and updates
Test cases are added to `autotest/test_modpathfile.py` to profile `ModpathFile.get_destination_pathline_data()` and `ModpathFile.get_destination_endpoint_data()`.
More generally this PR adds profiling support to `pytest` with a `--profile` (short `-P`) flag and a `profile` marker. Using the `--profile` flag runs only test functions marked with `@pytest.mark.profile`. Profiling functions do not run when the `--profile` flag is not provided (normal testing and profiling are mutually exclusive). By default, results are only printed to `stdout`. Results can be saved to disk with the `--profile-autosave` flag. This will create a folder …
=> ModpathFile performance profiling, misc fixes

.github/workflows/commit.yml, .github/workflows/daily.yml, DEVELOPER.md, autotest/conftest.py, autotest/pytest.ini, autotest/regression/test_lgr.py, autotest/regression/test_mf6.py, autotest/test_binarygrid_util.py, autotest/test_example_scripts.py, autotest/test_export.py, autotest/test_grid.py, autotest/test_lgr.py, autotest/test_mf6.py, autotest/test_modpathfile.py, autotest/test_plot.py, autotest/test_scripts.py, autotest/test_usg.py
Pytest framework changes include:
* use `pytest-benchmark`'s [builtin profiling capability](https://pytest-benchmark.readthedocs.io/en/stable/usage.html#commandline-options) instead of manual implementation
* update `DEVELOPER.md` to reflect above
* remove `requires_exe("mf6")` from `test_mf6.py` tests that don't run models/simulations
* add `@requires_spatial_reference` marker to `conftest.py` (for tests depending on [spatialreference.org](spatialreference.org))
* split `test_export.py::test_polygon_from_ij` into network-bound and non-network-bound cases (and use marker above)
* try both `importlib.import_module` and `pkg_resources.get_distribution` in `@requires_pkg` marker
* #1486 only used latter, which caused some tests to be unintentionally skipped due to differences between package …
=> Update pytest framework

.github/workflows/commit.yml, .github/workflows/daily.yml, flopy/discretization/grid.py, flopy/discretization/structuredgrid.py, flopy/discretization/unstructuredgrid.py, flopy/discretization/vertexgrid.py
=> update(intersect): update to raise error only when interface is called improperly

.github/workflows/commit.yml, .github/workflows/daily.yml
Fixes multiline command syntax error in Windows benchmark job. Also disables dependency caching (pip, conda and modflow executables) pending resolution of GitHub actions [`hashFiles()` timeouts](https://github.com/actions/runner/issues/1840).
=> CI: fix benchmark steps, disable dependency caching

.docs/introduction.rst, README.md, autotest/test_get_modflow.py, docs/get_modflow.md, flopy/mbase.py, flopy/utils/__init__.py, flopy/utils/get_modflow.py
The main ambition in this PR is to allow a user to easily install executables for flopy to use. The steps would be:
1. `pip install flopy` / `conda install flopy`
2. `get-modflow :flopy`
The auto-select option `:flopy` for bindir will determine the path to the users' localdata directory, which will use a `bin` directory. This localdata `bin` directory will be prepended to Python's PATH after `import flopy` so that most `m.run_model()` commands should find a working executable. There are a few downsides or things to consider when choosing `:flopy` as a recommended default:
- The localdata `bin` directory used by flopy is only added to PATH within Python after `import flopy`, but not before the import and not in a command prompt (unless that localdata `bin` directory is manually added to …
=> refactor(get-modflow): add option to have flopy bindir on PATH

etc/environment.yml, flopy/export/shapefile_utils.py, setup.cfg
This removes a minor dependency on [apprdirs](https://github.com/ActiveState/appdirs), which was used to determine a user-writable path to write application data. The replacement is to let flopy determine this:
- Windows will use `%LOCALAPPDATA%\flopy`
- Others (macOS, Linux) will use `$HOME/.local/share/flopy`
This is the same directory used by get-modflow to store other metadata and potentially `bin`.
Note that previous logic had a fall-back directory `HOME/.flopy` if appdirs was not available. This directory is no longer used (if it ever was), so it can be cleaned up.
=> refactor(shapefile_utils): remove appdirs dependency

autotest/test_export.py, flopy/export/utils.py
- add test case for `export_contours` function (previously only filled contours version `export_contourf` was tested)
- remove `modelgrid` from `flopy.export.utils.export_contours` signature
- follow `export_contourf` convention
- `epsg` and `prj` are already optional params
- mention contour export functions in `flopy3.3_PlotMapView.ipynb` ([cell 15](https://github.com/modflowpy/flopy/blob/eb06b9edfa21be80e6aac02c9a8d2e4211ace7e6/examples/Notebooks/flopy3.3_PlotMapView.ipynb))
Motivated by #1527
=> refactor(export_contours): refactor, test and example for flopy.export.utils.export_contours

setup.cfg
Since #1458, `autotest` was installed along side `flopy` in a Python's site-packages directory. This was done via [automatic/custom discovery](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#custom-discovery) since `autotest/__init__.py` was added to create a new module. However, it does not make sense to install `autotest`. This is fixed by specifying an `include` list option, which implicitly excludes `autotest` (or potentially any other directory with `__init__.py`).
=> fix(setuptools): only include flopy and flopy.* packages (not autotest)

autotest/conftest.py, autotest/pytest.ini, autotest/regression/test_mf6.py, autotest/regression/test_mf6_examples.py, autotest/test_binarygrid_util.py, autotest/test_cbc_full3D.py, autotest/test_copy.py, autotest/test_export.py, autotest/test_generate_classes.py, autotest/test_lake_connections.py, autotest/test_mf6.py, autotest/test_modflow.py, autotest/test_modpathfile.py, autotest/test_mp6.py, autotest/test_mp7.py, autotest/test_plot.py, autotest/test_postprocessing.py, autotest/test_specific_discharge.py, autotest/test_structured_faceflows.py, autotest/test_zonbud_utility.py
Introduce `mf6` marker to `pytest.ini` and add it to all tests using `flopy.mf6`. The marker is applied separately to some test cases with `@pytest.mark.mf6` and to some entire files with `pytestmark = pytest.mark.mf6`. Modflow6 tests can be selected with `pytest -m "mf6"` and queried with `pytest --collect-only --quiet -m "mf6"`.
Also:
- un-`xfail` external-path related tests in `test_modflow.py` (marked in error)
- skip `test_modflow.py::test_single_mflist_entry_load` on Windows CI to avoid [errors](https://github.com/modflowpy/flopy/runs/8096439002?check_suite_focus=true#step:8:1753) when changing workspace between drives and resetting external path [with `os.path.relpath`](https://bugs.python.org/issue7195)
- add fixture to make sure plots are closed when tests are run interactively, …
=> test: add marker for mf6 tests

flopy/mf6/mfpackage.py
Modified the way `maxbound` is evaluated relative to the size of the `stress_period_data` data. If `maxbound` is defined to be something other than `None` when a package is initialized the value is only modified if the sized of the `stress_period_data` exceeds the specified `maxbound` value. This change was precipitated by the need to set a `maxbound` value larger than the largest size of `stress_period_data` for use with the MODFLOW API.
This change also simplifies the three value boolean check that was used previously.
=> fix(mfpackage): modify maxbound evaluation

autotest/test_geospatial_util.py, autotest/test_plot.py, flopy/plot/crosssection.py, flopy/utils/geospatial_utils.py
- accept flopy/shapely linestrings for `CrossSectionPlot` line via `GeoSpatialUtil` as suggested [here](https://github.com/modflowpy/flopy/issues/1436#issuecomment-1183432320)
- make sure at least 2 coordinates provided to create `GeoSpatialUtil` with linestring shapetype
=> refactor(CrossSectionPlot, GeoSpatialUtil)

autotest/test_grid.py, autotest/test_gridutil.py, autotest/test_headufile.py, flopy/discretization/grid.py, flopy/utils/binaryfile.py, flopy/utils/gridutil.py
#1510 added new grid utility function `get_lni(ncpl, *nodes)` to compute layer index and within-layer node index from grid-wise node number. For `ncpl` it expects an `int` or array-like of integers per the convention for unstructured grids.
Originally if the `ncpl` argument to this function was an `int` it was assumed to describe a 1-layer grid. Now an integer value is no longer understood to carry information about the number of layers, and indicates only that all layers have the same node count. If the value is less than any specified node numbers, the grid is presumed to have at least enough layers to contain them.
The function's signature has changed from `get_lni(ncpl, *nodes)` to `get_lni(ncpl, nodes)`, and likewise for `Grid.get_lni(nodes)`. Both now expect array-like `nodes` and …
=> refactor(get_lni): simplify get_lni signature & behavior

autotest/regression/test_mf6.py, autotest/test_example_scripts.py, examples/scripts/flopy_henry.py, examples/scripts/flopy_lake_example.py, examples/scripts/flopy_swi2_ex1.py, examples/scripts/flopy_swi2_ex2.py, examples/scripts/flopy_swi2_ex3.py, examples/scripts/flopy_swi2_ex4.py, examples/scripts/flopy_swi2_ex5.py, flopy/plot/crosssection.py
Fix example script/notebook [test failures](https://github.com/modflowpy/flopy/actions/runs/3072694989/jobs/4964349538#step:8:509)
- use named `match_original` param when creating `PatchCollection` in `crosssection.py` (avoid usage warning)
- update `test_example_scripts.py` allowed outputs (don't fail on matplotlib warning)
- explicitly provide axis for colorbar in `flopy3.3_PlotMapView.ipynb`
- use filename instead of abs path for plot title in `flopy3.3_PlotMapView.ipynb`
- lint `autotest/regression/test_mf6.py`
=> fix: example scripts and notebooks

.github/workflows/commit.yml, CITATION.cff, MANIFEST.in, docs/make_release.md, flopy/__init__.py, flopy/version.py, scripts/make-release.py, setup.cfg
This PR does a few things:
- Adds a [CITATION.cff](https://citation-file-format.github.io/) file [supported by GitHub](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) (and others), which contains both a software citation and a preferred citation to the _Groundwater_ article. It also contains author [ORCIDs](https://orcid.org/), which I've hopefully correctly identified from a basic search (except @dbrakenhoff you may want to create one). The lint workflow validates this file, and shows the citation in "apalike" and BibTeX formats.
- Parts of `flopy/version.py` are removed, and this file now just contains version-related information.  `__author_email__` is not widely used (usually it is `__email__`; …
=> refactor(make-release): use CITATION.cff for author metadata

CITATION.cff, autotest/regression/conftest.py, flopy/utils/mfreadnam.py
This PR fixes a bug with parsenamefile, where it attempts to find case-insensitive filename matches from a parent directory, e.g. this change:
```diff
--- a/examples/data/mt3d_test/mf2005mt3d/P07/p7mf2005.nam
+++ b/examples/data/mt3d_test/mf2005mt3d/P07/p7mf2005.nam
@@ -7 +7 @@
-LIST         7       P7.LST
+LIST         7       ..\other\P7.LST
```
will raise errors with `pytest test_mt3d.py::test_mf2005_p07`:
```
../flopy/modflow/mf.py:733: in load
ext_unit_dict = mfreadnam.parsenamefile(
...
>               fls = os.listdir(dn)
E               FileNotFoundError: [Errno 2] No such file or directory: '/data/mtoews/src/flopy/examples/data/mt3d_test/mf2005mt3d/P07/../other'
../flopy/utils/mfreadnam.py:167: FileNotFoundError
```
The fix was to only check other files if the parent directory …
=> fix(parsenamefile): only do lowercase comparison when parent dir exists

autotest/test_grid.py, flopy/discretization/grid.py, flopy/discretization/structuredgrid.py, flopy/discretization/unstructuredgrid.py, flopy/mf6/mfmodel.py, flopy/modflow/mf.py, flopy/plot/map.py
* added `tri_mask` **kwarg to contour_array to check triangle elements against grid cell nearest neighbors and mask triangles that do not conform to nearest neighbor requirements. `tri_mask` is only needed when holes are present or a modelgrid has concave boundaries. 
* added neighbors() method to Grid, StructuredGrid, and UnstructuredGrid that returns a cells nearest neighbors 
* updated UnstructuredGrid to optionally include iac, ja arrays
* updated MFModel and Modflow to provide iac and ja arrays during UnstructuredGrid construction
* added tests for neighbors routine
=> update_data(contour_array): added routine to mask errant triangles

autotest/test_cbc_full3D.py, autotest/test_export.py, autotest/test_grid.py, autotest/test_modpathfile.py, autotest/test_mp6.py, autotest/test_mp7.py, autotest/test_mt3d.py, autotest/test_obs.py, autotest/test_plot.py, autotest/test_postprocessing.py, autotest/test_sfr.py, autotest/test_uzf.py, autotest/test_zonbud_utility.py
Some markers to skip tests based on executable availability were missing. (Noticed while setting up a fresh environment and running the tests before installing exes.)
=> fix(test markers): add missing markers for exes required

autotest/test_gridintersect.py, docs/flopy_method_dependencies.md, etc/environment.yml, flopy/plot/map.py, flopy/utils/rasters.py, setup.cfg
Updates to map.py: 
* remove deprecated code that was tagged for removal in flopy version 3.3.5
* explicitly set default cmap to viridis in plot_array()
Updates to rasters.py:
* Major update to geostatistical sampling routine within resample_to_grid()
* Update takes advantage of the `rasterstats` package to perform zonal statistics, which provides over a 100x speed up to min, max, mean, med, mode sampling routine
* begin deprecation of multithread and thread_pool input parameters as they are no longer used
* Update introduces another optional dependency (`rasterstats` package) to FloPy
=> Update(rasters.py, map.py): speed improvement updates for `resample_to_grid()`

autotest/test_get_modflow.py, docs/get_modflow.md, flopy/utils/get_modflow.py
Supports installing releases from the main modflow6 repository. Updates the `repo` option to accept `modflow6` so the user can select any of the following:
- `executables` (default)
- `modflow6`
- `modflow6-nightly-build`
The `modflow6` repo's release archive contains most of the repository, not just binaries, so instead of unzipping directly to `bindir` like the other 2 options, there is an extra step to unzip in the download location before copying binaries to `bindir`.
Adds a section describing repo selection to the docs. Also adds a table of contents.
Besides covering the bases as far as distributions go, this is a step towards replacing the `pymake` dependency in modflow6 tests (currently `pymake` is used to download the latest mf6 release, among other things)
=> feat(get_modflow): support modflow6 repo releases

autotest/test_export.py, flopy/export/shapefile_utils.py, flopy/mt3d/mt.py
This PR does several things:
- Ensure that methods in `flopy.export.shapefile_utils` can be used with [pathlib](https://docs.python.org/3/library/pathlib.html) objects
- Allow `write_gridlines_shapefile` to write .prj file
- Add `test_write_gridlines_shapefile`
- Add remaining file missed from #1563 for `Mt3dms`
=> refactor(shapefile_utils): pathlib compatibility, other improvements

autotest/test_binaryfile.py, autotest/test_gridintersect.py, autotest/test_lake_connections.py
- add a few test cases for `HeadFile` and `CellBudgetFile` precision detection while attempting to reproduce https://github.com/modflowpy/flopy/issues/1572
- mark tests which need new `rasterstats` optional dependency introduced in https://github.com/modflowpy/flopy/pull/1571
=> test(binaryfile): add tests for head and budget file precision detection

flopy/utils/observationfile.py
* The CsvFile load routine used default np.genfromtxt arguments, including those that would remove spaces, dashes, parentheses and others.  This caused problems if these characters were used in obs names, for example.  This PR changes default behavior so that these characters are not removed.
=> fix(csvfile): default csvfile to retain all characters in column names

autotest/test_mf6.py, flopy/utils/observationfile.py
This fixes an argument mix-up with CsvFile (from #1587), where `deletechars` was passed as `replace_space`, and `replace_space` was never passed to `np.genfromtxt`.
Also, use a context manager to open/read/close file, as it does not need to be open any longer.
=> fix(csvfile): correction to read_csv args, close file handle

autotest/test_geospatial_util.py, etc/environment.yml, flopy/utils/gridintersect.py, setup.cfg
This PR does the following:
- enforce minimum shapely 1.8, also check that it works with shapely 2.0 (beta 1 pre-release was this week; [new docs here](https://shapely.readthedocs.io/en/latest/))
- change types `geoms` and `cellids` from lists to numpy arrays, which are are faster to process; but keep list return types for deprecated functions
- corrections to docstrings
- focus on speed-up for `_rect_grid_to_geoms_cellids` (called from `__init__`), building arrays of coordinates for constructing grid cell polygons
- before this PR, testing with a 500x500 grid, `GridIntersect(sgr, method="vertex", rtree=False)` (i.e. calling `__init__`) would take 3.09 s ± 61.2 ms
- with this PR and shapely 1.8.5, 2.3 s ± 79.5 ms, so 1.3x faster
- with this PR and shapely 2.0b1, 146 ms ± 184 µs, so about …
=> refactor(gridintersect): faster __init__ and better shapely 2.0 compat

autotest/test_grid.py, autotest/test_gridintersect.py, flopy/discretization/structuredgrid.py
This PR replaces internal processing of `get_lrc` and `get_node` to use NumPy's [`unravel_index`](https://numpy.org/doc/stable/reference/generated/numpy.unravel_index.html) and [`ravel_multi_index`](https://numpy.org/doc/stable/reference/generated/numpy.ravel_multi_index.html). There is a minor speed bump, and the methods also check the bounds of the inputs, raising ValueError if they are outside the L/R/C/node range.
Also add docstring examples and minor formatting to adhere to the [numpydoc style guide](https://numpydoc.readthedocs.io/en/latest/format.html).
=> refactor(get_lrc, get_node): use numpy methods, add examples

autotest/test_binaryfile.py, autotest/test_conftest.py, autotest/test_geospatial_util.py, autotest/test_get_modflow.py, autotest/test_grid.py, autotest/test_gridintersect.py, autotest/test_obs.py, autotest/test_plot.py, autotest/test_postprocessing.py, autotest/test_seawat.py, autotest/test_usg.py, autotest/test_zonbud_utility.py, docs/get_modflow.md, flopy/utils/get_modflow.py
A few minor fixes for `get-modflow` following up on https://github.com/modflowpy/flopy/pull/1573
- `:local` -> `:home` for `~/.local/bin` bindir option
- remove test asserts checking for downloaded zip file
- make sure user-local bindir exists before tests run
- remove stale `append` invocations on a `dict`
Also a bit of refactoring:
- update `get_releases` function signature to accept `repo` instead of full API URL
- factor out `get_release` function (planning to use this from  `modflow6` test framework)
- factor out function to (auto-)select `bindir` if a `:`-prefixed option is used
- use parametrization to combine previously separate test functions
- add tests for refactored functions
Finally, miscellaneous:
- fix test case missed in https://github.com/modflowpy/flopy/pull/1586
=> fix(get_modflow): misc

.docs/conf.py, examples/Notebooks/flopy3_mfusg_freyberg.ipynb, examples/Notebooks/flopy3_modpath6_example.ipynb, examples/Tutorials/modflow6output/tutorial01_mf6_output.py, examples/common/notebook_utils.py, setup.cfg
This PR does several things related to docs/examples:
- Online docs needed updating to use authors from CITATION.cff instead of `__authors__` metadata
- Update dependencies for `doc` extras (i.e. `pip install -e .[doc]`) to make a complete build
- Fix-up an issue with `get_project_root_path` only in `examples/Tutorials/modflow6output/tutorial01_mf6_output.py`
- Use [`Path.cwd()`](https://docs.python.org/3/library/pathlib.html#pathlib.Path.cwd) instead of `Path(os.getcwd())`
- Sphinx now considers `language = None` to be invalid, so specify "en"
- Update copyright year for docs
=> refactor(docs/examples): correction to authors, use Path.cwd()

autotest/test_export.py, flopy/export/vtk.py
This PR is primarily focused with the vtk export module:
- Ensure the vtk module works with pathlib and str path objects
- Use more pathlib throughout vtk module and test_export.py
- Many corrections to docstrings for vtk module
- Use Sphinx's [`deprecated` directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-deprecated) with a link to the recommended method(s)
- Remove `binary` option with `count_lines_in_file` since it wasn't used and does not make sense
- Add `is_binary_file` and use it instead of "exists()" checks
=> refactor(vtk): use pathlib, corrections to docstrings

flopy/utils/modpathfile.py
* fix applies to vertex and unstructured grid pathlines
=> fix(write_shapefile): fix transform call for exporting shapefile

.github/workflows/benchmark.yml, .github/workflows/commit.yml, .github/workflows/examples.yml, .github/workflows/mf6.yml, .github/workflows/regression.yml, .github/workflows/rtd.yml, flopy/mbase.py, flopy/plot/crosssection.py, flopy/plot/map.py
- update commit-triggered CI to run on any branch starting with prefix `ci-diagnose*`
- fix Python usage in cross-platform CI jobs
- `python` isn't aliased to Python3 on Mac when `bash -l {0}` is the default shell, causing [Python2 to be used](https://github.com/modflowpy/flopy/actions/runs/3367930152/jobs/5585909218#step:4:14)
- use `shell: bash -l {0}` only [as required for Micromamba](https://github.com/mamba-org/provision-with-micromamba#important), otherwise `shell: bash`
- fix default values for `hnoflo` and `hdry` introduced in #1610
- correct `hdry` default from `-1e-30` to `-1e30`
- add defaults to `BaseModel` (fix [notebook errors](https://github.com/modflowpy/flopy/actions/runs/3367943010/jobs/5585933660#step:8:412) caused by `None` passed to numpy)
- this caused the MODFLOW 6 …
=> fix(multiple): miscellanous fixes/enhancements

.github/workflows/benchmark.yml, .github/workflows/examples.yml, .github/workflows/regression.yml
I added the `push` trigger for benchmark, example and regression workflows while testing #1614 and neglected to remove it
=> fix(ci): don't run benchmarks, examples and regression tests on push

autotest/regression/test_lgr.py
`autotest/regression/test_lgr.py::test_simplelgr` failed on Windows CI last night, marked it `@flaky` for an automatic retry
=> test: mark LGR test flaky

autotest/test_export.py, autotest/test_plot.py, flopy/plot/map.py
- switch from matplotlib `tricontour` to `contour` for `StructuredGrid` map view plots
- requested in #1605
- moved from #1614
- code rearranged a bit to separate the tri / contours cases
=> feat(contours): use standard contours for StructuredGrid map view plots

flopy/modpath/mp7sim.py
- while writing stoptime with stoptimeoption 3, there is an arbitrary +1 to the specified stoptime value
- addresses issue  #1622
=> fix(mp7-writestoptime) arbitrarily adding 1 to stoptime when writing modpath input file

.gitignore, autotest/test_datautil.py, flopy/utils/datautil.py
To test:
```python
from flopy.utils.datautil import PyListUtil
line = '13,14'
```
PyListUtil.split_data_line(line)
=> fixBug: not reading comma separated data correctly

autotest/test_get_modflow.py, flopy/utils/get_modflow.py
The recent addition of `code.json` to the [`executables` repo distribution](https://github.com/MODFLOW-USGS/executables/releases/tag/9.0) seemed to trip up executable naming/suffix handling when `--subset` is provided. This PR fixes that and makes `--subset` work by exact rather than substring matching, so the user must specify e.g. `mfnwt` and `mfnwtdbl` separately to get both. ~~Also sets execute permissions on the `libmf6` shared library.~~
=> fix(get-modflow): fix code.json handling

autotest/regression/test_mf6.py, autotest/test_mf6.py, flopy/mbase.py, flopy/mf6/mfmodel.py, flopy/mf6/mfpackage.py, flopy/mf6/modflow/mfsimulation.py, flopy/utils/datautil.py
Quotes properly removed when loading files with quoted strings (#1643).  If all else fails trying to find exe_path, abs_path is used (#1633).  Proper error message given when user attempts to create namefile (#1617).
=> fix(quotes+exe_path+nam_file): fixes for quoted strings, exe path, and nam file

.gitignore
In the release workflow, the [`app` directory](https://github.com/modflowpy/flopy/pull/1649/commits/fee7c58ca0bfc34f52763cf3c593547227b0bb12#diff-a172cedcae47474b615c54d510a5d84a8dea3032e958587430b413538be3f333) was leftover by the `orhun/git-cliff-action` step and was previously included in the automated version/DFN/plugin update commit via `git add -A`.
PR adds `app` to `.gitignore`. Also adds `venv` (convenient to ignore Python3 virtual environment in the project root).
=> fix(ci): update .gitignore

.github/workflows/release.yml, flopy/version.py
The [post-release PR to reset the `develop` branch](https://github.com/modflowpy/flopy/pull/1656) neglected to rerun the linter after resetting version files. Do so manually and update `release.yml` to do so in future
=> ci: lint after post-release reset version update

autotest/test_binaryfile.py, autotest/test_compare.py, autotest/test_gridutil.py, autotest/test_mfreadnam.py, flopy/utils/binaryfile.py, flopy/utils/compare.py, flopy/utils/gridutil.py, flopy/utils/mfreadnam.py
Move utilities that seem in-scope for `flopy` from `modflow-devtools` (originally from `pymake`)
* head & budget file writing
* head and budget comparison
* creating DISU model objects
* creating a uniform flow field
* reading entries from namefiles
Minimal tests are added for the last three items. The first two have either extremely minimal tests or (skipped) empty stubs. This PR will allow refactored modflow6 tests in https://github.com/MODFLOW-USGS/modflow6/pull/1066 to import from FloPy instead of pymake. I'm planning to return to this and expand the tests after getting more comfortable with how they're used in modflow6 autotests.
Both items below were moved to #1665
- ~~add a test for #1519~~
- ~~import shared fixtures and utilities from `modflow-devtools`~~
=> feat(utils): move utils from modflow-devtools

CITATION.cff, docs/make_release.md, scripts/README.md
- add myself to authors in `CITATION.cff` per @langevin-usgs' recommendation
- expand/clarify `docs/make_release.md` and `scripts/README.md`
- [automation of remaining manual steps in `executables` release](https://github.com/MODFLOW-USGS/executables/pull/16) simplifies steps before making a new flopy release
=> docs: expand release docs, update authors

.github/workflows/benchmark.yml, .github/workflows/commit.yml, .github/workflows/examples.yml, .github/workflows/regression.yml, .github/workflows/release.yml, DEVELOPER.md, README.md, autotest/conftest.py, etc/environment.yml, setup.cfg
This PR drops Python 3.7 for the next development effort. According to [PEP 537](https://peps.python.org/pep-0537/) Python 3.7 will be maintained until June 2023. NumPy dropped Python 3.7 support December 2021 ([NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html)).
With setting Python 3.8 as the minimum, there are a few new features available ([What’s New In Python 3.8](https://docs.python.org/3/whatsnew/3.8.html)). In this PR use of [`pkg_resources`](https://setuptools.pypa.io/en/latest/pkg_resources.html) is replaced with [`importlib.metadata`](https://docs.python.org/3/library/importlib.metadata.html).
CI workflows are adjusted by:
- Adding Python 3.11 to multi-version jobs
- Replace single versions that use Python 3.7 with 3.8 as the new minimum
Other changes to note:
- …
=> refactor/ci: drop Python 3.7, add Python 3.11

.github/workflows/benchmark.yml, .github/workflows/commit.yml, .github/workflows/examples.yml, .github/workflows/regression.yml, CONTRIBUTING.md, autotest/regression/test_lgr.py, autotest/regression/test_mf6.py, autotest/regression/test_mf6_examples.py, autotest/regression/test_mfnwt.py, autotest/regression/test_modflow.py, autotest/regression/test_str.py, autotest/regression/test_swi2.py, autotest/regression/test_wel.py, docs/flopy_method_dependencies.md, flopy/utils/compare.py, flopy/utils/mfreadnam.py, setup.cfg
- Replace `pymake` in autotests with comparison/etc functions newly relocated from `pymake` and utilities now in `modflow-devtools`. Allows code unrelated to building programs to be removed from `pymake`. Moved from #1668
- Adapt `regression/test_modflow.py::test_mf2005fhb` to the new behavior of `get_entries_from_namefile()` in `flopy/utils/mfreadnam.py`, recently relocated from pymake. The function [used to return a single-entry list with a tuple of `None`s if no entries are found](https://github.com/modflowpy/pymake/blob/2e84c5dbdbdae84db29bbbbc6576774d3c60d1ca/pymake/autotest/autotest.py#L426), but now just returns an empty list in that case
- Remove `pymake`-specific print statements from recently relocated utilities
=> refactor(dependencies): use devtools & relocated utils, drop pymake

flopy/modflow/mfgmg.py
There was a tiny bug in MF2005 reading GMG file. RELAX was always being read but should only be if ISC==4. Added default RELAX=1.0 following the logic of other optional variables DUP,DLOW, and CHGLIMIT
=> Hotfix gmg read

flopy/mf6/mfbase.py
package_key_dict has been removed and replaced with a property getter that gives a deprecation warning and returns the package_type_dict, which is functionally similar.
=> fix(package dictionary): removed package_key_dict since it is redundant and can cause errors

flopy/mf6/data/mfdatastorage.py
This resolves a RuntieWarning from flopy doing something like this:
```python
import flopy
def test_this():
sim = flopy.mf6.MFSimulation()
_ = flopy.mf6.ModflowTdis(sim)
gwf = flopy.mf6.ModflowGwf(sim)
_ = flopy.mf6.ModflowIms(sim)
_ = flopy.mf6.ModflowGwfdis(gwf, idomain=1)
_ = flopy.mf6.ModflowGwfoc(gwf, saverecord=[("HEAD", "ALL")])
```
which shows a warning summary:
```
$ pytest test_this.py
...
=============================== warnings summary ===============================
test_this.py::test_this
<__array_function__ internals>:200: RuntimeWarning: invalid value encountered in cast
```
and looking at a big trace shows where/how it was raised:
<details><summary>pytest trace</summary>
```
$ pytest -W error::RuntimeWarning test_this.py 
============================= test session starts …
```
=> fix(mfdatastorage): use appropriate fill_value for data type

autotest/test_mf6.py, etc/environment.yml, flopy/mf6/mfbase.py
This PR aims to add pathlib support for `flopy.mf6.MFSimulation`, so that one can supply a pathlike object to the `sim_ws` argument. This also adds pip to `etc/environment.yml` to avoid the warning that you get when creating a conda environment from this file (conda installs pip anyways after the warning).
=> Feat sim pathlib support

autotest/test_sfr.py
This fixes CI tests failure that previously worked <24 hrs due to a new release of matplotlib.
Generally, `isinstance()` is more tolerable, and works here for different versions of matplotlib.
=> fix(test_sfr): update test to be more robust with Matplotlib versions

examples/Tutorials/modflow6data/tutorial08_mf6_data.py, flopy/mbase.py, flopy/mf6/data/mfdataarray.py, flopy/mf6/data/mfdatalist.py, flopy/mf6/data/mffileaccess.py, flopy/mf6/data/mfstructure.py, flopy/mf6/mfmodel.py, flopy/mf6/mfpackage.py, flopy/mf6/modflow/mfsimulation.py
FloPy modifications to improve external file performance and best practices documented for optimizing performance for models with large datasets.  Specifically,
1) Reading and writing external binary files are now significantly faster than reading and writing external text files.
2) FloPy can be configured to no longer parse external files during load or save, unless they are specifically requested or modified.   In order to configure FloPy for this, turn FloPy's verification checks and auto-update "maxbound" value off:
sim.simulation_data.auto_set_sizes = False
sim.simulation_data.verify_data = False
=> fix(flopy performance): FloPy performance modifications + best practices documented

autotest/regression/test_mf6.py, flopy/mbase.py, flopy/mf6/data/dfn/sln-ims.dfn, flopy/mf6/data/mfstructure.py, flopy/mf6/modflow/mfgwf.py, flopy/mf6/modflow/mfgwt.py, flopy/mf6/modflow/mfims.py, flopy/mf6/modflow/mfsimulation.py, flopy/mf6/utils/createpackages.py
Also included: fix(exe path): FloPy now correctly resolves relative paths to mf6 executable (#1633)
=> feat(solvers): support for multiple solver types (#1706)

.github/workflows/mf6.yml
Avoid [errors like this](https://github.com/modflowpy/flopy/actions/runs/4265346307/jobs/7424562227#step:12:620). We already do this in `MODFLOW-USGS/modflow6`, just hadn't updated CI here to do so yet.
=> ci(mf6.yml): use GITHUB_TOKEN to bypass rate limit when installing exes

flopy/plot/crosssection.py, flopy/plot/map.py, flopy/plot/plotutil.py
=> Add logical "==" to filter_modpath_by_travel_time()

autotest/test_plot.py, flopy/plot/map.py
Support `color` kwarg in `PlotMapView.plot_endpoint()`. Also add a test for `plot_endpoint()`.
Motivated by cell 28 [here](https://github.com/aprovost-usgs/prt-examples-temp/blob/main/notebooks/ex-prt-mp7-p01.ipynb). Previously a matplotlib error would be raised if `color` was supplied
```
ValueError: Supply a 'c' argument or a 'color' kwarg but not both; they differ but their functionalities overlap.
```
This occurred because FloPy did not check whether a `color` value was provided before setting a default `c` value. This PR adds a check for `color` or `c`, passing `kwargs` directly to `ax.scatter` if one but not the other is found. If both are found, `color` is popped from `kwargs` so that `c` takes precedence and we avoid the above error.
=> refactor(PlotMapView): support color kwarg in plot_endpoint()

autotest/test_particledata.py, flopy/modpath/mp7particledata.py
Addresses #1628, uses `from numpy.lib.recfunctions import unstructured_to_structured` as suggested and adds a few test cases
=> fix(ParticleData): support partlocs as ndarray or list of lists

flopy/modpath/mp6sim.py
[Pandas 2.0](https://pandas.pydata.org/pandas-docs/version/2.0/whatsnew/v2.0.0.html) made [non-keyword arguments illegal for `DataFrame.drop()`](https://github.com/pandas-dev/pandas/pull/41486), update usage in `mp6sim.py`.
=> fix(mp6sim): use keyword args for pandas DataFrame.drop

autotest/test_mf6.py, flopy/mf6/mfbase.py, flopy/mf6/mfmodel.py, flopy/mf6/mfpackage.py
There is a [bug](https://github.com/python/cpython/issues/103220) in Python's `ntpath.join` (the Windows implementation of `os.path.join`) which adds an extra leading slash to UNC paths. This is causing a [test failure](https://github.com/modflowpy/flopy/actions/runs/4622009709/jobs/8174222128?pr=1757#step:9:3199) for `MFFileMgmt.string_to_file_path`, as far as I can tell only for Python>=3.11.1.
The `string_to_file_path` method seems unnecessary: the [tests](https://github.com/modflowpy/flopy/blob/8d52ecef28bdf5624d78ce0b809620353014e42c/autotest/test_mf6.py#L241) just assert that the arg value equals the return value. This PR removes the method.
=> fix(MFFileMgmt): remove string_to_file_path

autotest/test_mf6.py, flopy/mf6/mfbase.py, flopy/mf6/mfpackage.py
- Fix #1747. `MFSimulation.load()` with absolute or relative paths on Windows could raise `IndexError`, tracing to `MFFileMgmt.strip_model_relative_path`. Avoid this and refactor to use `pathlib`. Test providing namefile by name, by absolute path, and by relative path
- Since Modflow6 supports POSIX paths even on Windows, use forward slash separators in relative path strings returned by `strip_model_relative_path` on all OS &mdash; previously used backslashes on Windows
- Convert back- to forward-slashes in `filename` ctor argument to `MFPackage`. Fixes [an error](https://github.com/modflowpy/flopy/actions/runs/4806458990/jobs/8554004109) introduced in https://github.com/modflowpy/flopy/pull/1759 occurring with a relative `filename` with Windows separators
- Currently FloPy …
=> fix(MFFileMgmt): fix strip_model_relative_path to avoid IndexError

flopy/mt3d/mtdsp.py
- Addresses #1776
- Ran black
- Tested changes on local machine using MT3D-USGS autotest [t006_test_mt3dms_p03.py](https://github.com/MODFLOW-USGS/mt3d-usgs/blob/develop/autotest/t006_test_mt3dms_p03.py)
=> fix(mtdsp): Add support for keyword 'nocross' in MT3D dsp package

autotest/test_export.py, autotest/test_shapefile_utils.py, flopy/export/shapefile_utils.py
- fix https://github.com/modflowpy/flopy/issues/1775
- if array data (e.g. `angldegx`) is missing, a warning is shown but export proceeds
- add some test cases for above, factor out a function to create a sim with a GWF model on a DISU grid
- update `test_export.py::test_freyberg_export` to check shapefiles exported for each level (model/pkg/obj) exist
- update `test_export.py::test_export_output` to write netCDF files to tempdir instead of cwd
=> fix(shapefile_utils): check attr.array for None in model_attributes_to_shapefile

autotest/test_export.py, autotest/test_geospatial_util.py, autotest/test_gridintersect.py, autotest/test_mbase.py, autotest/test_mf6.py, autotest/test_mp6.py, autotest/test_plot.py, autotest/test_sfr.py, autotest/test_shapefile_utils.py, flopy/modpath/mp6sim.py
With a fresh install of FloPy from PyPI without pandas installed, a message is always shown after import:
```bash
$ python -c "import flopy"
Missing optional dependency 'pandas'. writing particles is more effcient with pandas Use pip or conda to install pandas.
```
This PR moves the import of the optional dependency to the `_write_particle_data_with_pandas` method, which raises an error instead with `StartingLocationsFile(model=mp, use_pandas=True)`. Now `import flopy` does not show the message.
Also `test_mpsim` is modified to test with `use_pandas=False` and `use_pandas=True` if pandas is available, which should improve coverage.
Several other miscellaneous edits to tests allow skipping of tests with a subset of optional packages installed, or without `mf6`.
=> fix(Modpath6Sim): move import_optional_dependency("pandas") to method

flopy/discretization/unstructuredgrid.py, flopy/mf6/mfmodel.py, flopy/mf6/modflow/mfgwfgwf.py, flopy/mf6/modflow/mfgwfgwt.py, flopy/mf6/modflow/mfgwtgwt.py, flopy/mf6/utils/createpackages.py, flopy/modflow/mf.py, flopy/plot/plotutil.py
* update: createpackages.py to automatically define `exgtype` parameter in `__init__` for exchange packages
* removed unneeded `return` statements from` UnstructuredGrid` class
* updated: mfmodel.py and mf.py `UnstructuredGrid` creation routine to send `iac` and `ja` as arrays instead of MFArray objects
* updated: `irregular_shape_patch()` in `UnstructuredPlotUtilities`. Update assists with formatting cell2d `iverts` for model splitting and remapping.
=> bugfixes and updates for model spiliting integration

.github/workflows/examples.yml
The nightly example tests [have been failing](https://github.com/modflowpy/flopy/actions/runs/5130512589) on Linux and Windows due to the same VTK/PyVista issue we initially ran into after #1750. Use the same workarounds introduced for the `rtd.yml` docs build in #1790 (originally referenced from the PyVista repo)
- use `vtk-osmesa` and `trame` on Linux
- install openGL on Windows
=> ci: add VTK workarounds for example notebook tests

flopy/mf6/data/mfdata.py, flopy/mf6/data/mfdataarray.py, flopy/mf6/data/mfdatalist.py, flopy/mf6/data/mfdatascalar.py, flopy/mf6/data/mfdatastorage.py, flopy/mf6/mfpackage.py
Fixed issue where flopy only recognized float64 data and not float32 data.
Fixed issue where block headers were not getting created for empty data blocks.
=> fix(float32, empty stress period): #1779 and #1793

flopy/mbase.py, flopy/mf6/modflow/mfsimulation.py
Use `mpiexec` to run parallel MODFLOW 6 models when `processors` 
keyword argument is not None.
=> feat(run_simulation): add support for running parallel simulations

.docs/Notebooks/mt3d-usgs_example.py, .docs/Notebooks/plot_map_view_example.py, .github/workflows/rtd.yml
Prevents missing font errors like `findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial`
Also restore font usages removed from notebooks to avoid these errors in #1790
=> ci: install fonts and clear mpl cache before running notebooks

.docs/Notebooks/groundwater2023_watershed_example.py, .docs/Notebooks/mf6_parallel_model_splitting_example.py, .docs/Notebooks/mf6_support_example.py, .docs/Notebooks/modpath7_structured_transient_example.py, .docs/Notebooks/mt3d-usgs_example.py, .docs/Notebooks/nwt_option_blocks_tutorial.py, .docs/Notebooks/raster_intersection_example.py, .docs/Notebooks/sfrpackage_example.py, .docs/Notebooks/zonebudget_example.py
In the ReadTheDocs sidebar, rendering of tables of contents requires a valid hierarchy of headers in each notebook (title must be higher level than subsections), otherwise links to notebook subsections are included in the TOC.
=> docs(notebooks): fix headers so TOCs render properly

.github/workflows/commit.yml, .github/workflows/examples.yml, .github/workflows/release.yml
A regression test is broken because an mf6 example model using `develop` branch features was [recently added](https://github.com/MODFLOW-USGS/modflow6-examples/commit/b4a4382050010f9b77bb52ebf8a797c0a9287ceb). Previously flopy used the official release of modflow6 for commit-triggered and nightly CI testing. This PR switches to the development build of mf6 and updates flopy packages so that mf6 and flopy can be developed in sync.
Also correct "plugins" to "packages" in `release.yml`
=> ci: install mf6 nightly build exes and update flopy pkgs

.github/workflows/regression.yml
#1824 included `commit.yml` and `examples.yml` but failed to include the regression tests CI workflow `regression.yml`, do so here
=> ci: use mf6 dev exes and pkgs for regression tests

autotest/test_model_splitter.py, flopy/mf6/modflow/mfsimulation.py, flopy/mf6/utils/model_splitter.py
* update test_save_load_node_mapping
* fix MFSimulation.model_names, return an iterable list instead of dict keys object
=> fix(load_node_mapping): add sim parameter to populate Mf6Splitter._model_dict

flopy/mf6/data/mfdatalist.py, flopy/mf6/data/mffileaccess.py
When a keystring contains a record flopy assumed that the key record name would be <keystring>record.  Since it is very easy for someone to not follow this naming convention in the dfn file, flopy no longer requires it.
=> fix(keystring): flopy key record no longer needs to be named after keystring (#1616)

flopy/modflow/mfsfr2.py
parse only the first three entries to avoid error when the rest of the line are not integers
=> bugfix in mfsfr2.py for tabulate flow format

autotest/test_export.py, autotest/test_mp7.py, autotest/test_mp7_cases.py, flopy/modpath/mp7sim.py
- add a test for #1817
- refactor mp7 test cases (separate functions for creating gwf and mp7 models/sims)
- update mp7 test cases to use `inner/outer_dvclose` instead of deprecated `hclose`
- make docstring indentation consistent in `mp7sim.py`
=> test(mp7): refactor cases, check warning for duplicate mp7sim pkgs

.github/workflows/examples.yml, autotest/test_example_scripts.py
- prevent [CI failures](https://github.com/modflowpy/flopy/actions/runs/5302617620/jobs/9597672524) on missing fonts, deprecation warnings, etc as long as return code is 0
- show (use `-s` flag) instead of capturing warnings sent to stdout + stderr
=> test(scripts): don't fail on stderr

flopy/mbase.py, flopy/mf6/utils/model_splitter.py
* update message written for simulations run with mpiexec.
=> feat(model_splitter): add support for models that do not use IDOMAIN

autotest/test_generate_classes.py, autotest/test_model_splitter.py, autotest/test_mp6.py, autotest/test_notebooks.py, etc/environment.yml, flopy/mf6/utils/generate_classes.py, pyproject.toml, scripts/run_notebooks.py
- Add optional `owner` param to `generate_classes()` to update classes from a fork, default is "MODFLOW-USGS"
- Add test using [`pytest-virtualenv`](https://pypi.org/project/pytest-virtualenv/) which allows updating sources in an isolated temporary environment
- Add `pytest-virtualenv` to `pyproject.toml` and `environment.yml`
- Run black and isort on some scripts and autotests
=> feat(generate_classes): add optional owner param

autotest/test_get_modflow.py, flopy/utils/get_modflow.py
There have been recent changes to modflow6-nightly-build that have changed how get-modflow works.
From Linux:
```
$ get-modflow :python --repo modflow6-nightly-build --release-id 20230622
auto-selecting option ':python' for ':python'
fetched release '20230622' info from MODFLOW-USGS/modflow6-nightly-build
downloading 'https://github.com/MODFLOW-USGS/modflow6-nightly-build/releases/download/20230622/mf6.4.2dev_linux.zip' to '/tmp/tmp84o_afdm/modflow6_nightly-20230622-mf6.4.2dev_linux.zip'
extracting 7 files to '/tmp/py310/bin'
mf6.4.2dev_linux/bin/libmf6.so   mf6.4.2dev_linux/code.json
mf6.4.2dev_linux/bin/mf5to6      mf6.4.2dev_linux/doc/mf6io.pdf
mf6.4.2dev_linux/bin/mf6         mf6.4.2dev_linux/doc/release.pdf
mf6.4.2dev_linux/bin/zbud6
updated flopy metadata file: …
```
=> fix(get-modflow): manage internal "bin" dir structures

.github/workflows/release.yml, docs/make_release.md
Update the release workflow to append "+" to the version string merged back to `develop` from `master`, to indicate preliminary/development status. This is as opposed to incrementing one of the version numbers, which is not a great solution as it can't always be predicted if the next release will be major, minor, or patch.
Also a minor fix to changelog generation
=> ci: update post-release versioning conventions

.github/workflows/release.yml, docs/make_release.md
Update the release workflow to use PyPI trusted publishing.
=> ci: update PyPI publishing step/docs

.docs/Notebooks/array_output_tutorial.py, .docs/Notebooks/plot_cross_section_example.py, .docs/Notebooks/plot_map_view_example.py, autotest/test_flopy_module.py, flopy/utils/get_modflow.py
The [mf6 windows distribution](https://github.com/MODFLOW-USGS/modflow6/releases/tag/6.4.2) has an OS tag `win64` now so can be handled in the same way as the nightly build and executables dists &mdash; all three now have assets with `linux`, `mac`, and `win64` in the name
Fixes `get-modflow <bindir> --repo modflow6`, which could break if used with the latest release
=> fix(get-modflow): accommodate mf6 release asset name change

etc/environment.yml, pyproject.toml
The [`pytest-virtualenv`](https://pypi.org/project/pytest-virtualenv/) plugin can evidently fail to install `virtualenv` where needed (reported with Mamba on Mac). List `virtualenv` separately as a testing dependency
=> chore: add virtualenv as test dependency

autotest/test_example_scripts.py, autotest/test_notebooks.py
- prevent potential `None` reference
- add comment re: collection order
- reformat test scripts
=> test: minor fixes to notebook/script tests

.github/workflows/release.yml
Trusted publishing [requires using action `pypi/gh-action-pypi-publish`](https://docs.pypi.org/trusted-publishers/using-a-publisher/#the-easy-way). This is a temporary fix in case another release is made before flopy can adopt [the reusable Python release workflow](https://github.com/MODFLOW-USGS/modflow-devtools/pull/85) forthcoming from devtools.
=> ci(release): fix publish to PyPi step

flopy/utils/binaryfile.py, flopy/utils/gridutil.py
In the future, [numpy will stop treating arrays with 1 element and dimension >0 as scalars](https://numpy.org/doc/stable/release/1.25.0-notes.html#deprecations). Use `.item()` to access the single element.
This may need to be fixed elsewhere in the codebase, this is the only place I have seen warnings from recently.
=> fix(binaryfile): avoid numpy deprecation warnings

docs/make_release.md
https://github.com/modflowpy/flopy/pull/1850#pullrequestreview-1530879973https://github.com/modflowpy/flopy/pull/1850#pullrequestreview-1530879973https://github.com/modflowpy/flopy/pull/1850#pullrequestreview-1530879973
=> docs(release): add note to review deprecations

.docs/Notebooks/modelgrid_examples.py, .docs/Notebooks/shapefile_export_example.py, autotest/test_export.py, autotest/test_grid.py, autotest/test_lgr.py, autotest/test_modflow.py, autotest/test_modflowdis.py, autotest/test_mp6.py, flopy/discretization/grid.py, flopy/discretization/structuredgrid.py, flopy/discretization/unstructuredgrid.py, flopy/discretization/vertexgrid.py, flopy/export/shapefile_utils.py, flopy/export/utils.py, flopy/mf6/mfmodel.py, flopy/modflow/mf.py, flopy/modflow/mfdis.py, flopy/utils/crs.py, flopy/utils/mfreadnam.py, flopy/utils/modpathfile.py
This PR is is a continuation of #1737 which has a few broad aims:
- Use a `crs` parameter, which can take an EPSG integer, a PROJ string, or a CRS instance from pyproj. This single parameter replaces (and deprecates) `epsg`, `proj4` and `proj4_str` parameters, where present.
- Use a `prjfile` parameter as a path to a `.prj` file that describes a coordinate reference system, which replaces (and deprecates) `prj`, where present.
This PR embeds these changes further within the code.
However, a vital change in this PR is to provide some support without pyproj installed. For instance, a modelgrid can be created using (e.g.) `crs="EPSG:26915"` or `crs=26915`, and the resulting object will always have a `.epsg` property with an integer code. This was the case before #1737, but was broken. …
=> refactor(crs): provide support without pyproj, other deprecations

.docs/Notebooks/sfrpackage_example.py, autotest/test_export.py, autotest/test_grid.py, autotest/test_hydmodfile.py, autotest/test_listbudget.py, autotest/test_mnw.py, autotest/test_mp5.py, autotest/test_mp6.py, autotest/test_mp7.py, autotest/test_plot.py, autotest/test_sfr.py, autotest/test_str.py, autotest/test_swr_binaryread.py, autotest/test_util_2d_and_3d.py, autotest/test_zonbud_utility.py, docs/flopy_method_dependencies.md, flopy/export/metadata.py, flopy/mf6/utils/binaryfile_utils.py, flopy/mf6/utils/mfobservation.py, flopy/modflow/mfsfr2.py, flopy/modpath/mp6sim.py, flopy/utils/flopy_io.py, flopy/utils/mflistfile.py, flopy/utils/mtlistfile.py, flopy/utils/observationfile.py, flopy/utils/sfroutputfile.py, flopy/utils/util_list.py, flopy/utils/utl_import.py, flopy/utils/zonbud.py, pyproject.toml
Last #1788 was discussed (May 2023) it was proposed to wait one more release cycle before adding pandas as a core requirement, especially since pandas v2 came out in early April. In view of recent effort to optimize flopy file IO, now may be a good time. Some work underway to support MF6 PRT could also be simplified if pandas were present
- Add `pandas>=2.0.0` as a core dependency
- Replace optional imports with standard imports
- Update docstrings (remove "if available" language)
- Remove alternative logic for pandas < 1.3.0 from `sfroutputfile.py`
- Remove `requires_pkg("pandas")` from autotests
- Update autotests to always test pandas path (where applicable)
- Remove pandas entries from `flopy_method_dependencies.md`
If support should be maintained for older pandas I can remove the >=2 …
=> refactor(dependencies): require pandas>=2.0.0

autotest/test_plot.py, flopy/plot/crosssection.py, flopy/plot/map.py
- Accept single or list of recarray or dataframe in`PlotMapView` and `PlotCrossSection` particle track plotting methods
- `plot_pathline()`
- `plot_timeseries()`
- `plot_endpoint()`
- Update plot tests
- Tidy doc strings
=> refactor(pathline/endpoint plots): support recarray or dataframe

flopy/discretization/grid.py, flopy/discretization/structuredgrid.py, flopy/discretization/unstructuredgrid.py, flopy/discretization/vertexgrid.py
This warning was introduced with #1326 for FloPy 3.3.5, changed to an error with #1489 for FloPy 3.3.6.
This error was intended to be removed for 3.3.7, so this is overdue.
=> refactor(expired deprecation): remove warning for third parameter of Grid.intersect

DEVELOPER.md, autotest/test_export.py, docs/make_release.md
Add deprecation guidelines after discussion with @langevin-usgs, @jdhughes-usgs, @mjreno. Followup to https://github.com/modflowpy/flopy/pull/1878.
* describe policy loosely following [NEP 23](https://numpy.org/neps/nep-0023-backwards-compatibility.html) in
* `DEVELOPER.md`
* `docs/make_release.md`
* update table of contents in `DEVELOPER.md`
* fix some autotest names
PRs applying deprecations introduced in version 3.3.5 or before:
- #1890
- #1891 
- #1892 
- #1893 
- #1894
=> docs: add deprecation policy to dev docs and release guide

.docs/conf.py
No longer needed. Hoping this fixes broken notebook rendering in `latest` due to `ModuleNotFoundError: No module named 'sphinxcontrib.jquery'` in RTD build
=> docs: remove workaround for https://github.com/readthedocs/sphinx_rtd_theme/issues/1452

pyproject.toml
[RTD default versions](https://docs.readthedocs.io/en/stable/build-default-versions.html#external-dependencies) for `sphinx` and `sphinx-rtd-theme` for projects of flopy's age are incompatible. Require at least sphinx 4 to avoid [style attribute errors](https://github.com/readthedocs/sphinx_rtd_theme/issues/1465#issuecomment-1531262630)
=> docs: require sphinx>=4 to fix RTD build

pyproject.toml
Followup to #1898, need to specify recent versions of both sphinx and sphinx-rtd-theme to override RTD's [defaults](https://docs.readthedocs.io/en/stable/build-default-versions.html#external-dependencies)
=> refactor(dependencies): constrain sphinx-rtd-theme >=1

flopy/mf6/data/mfdataarray.py, flopy/mf6/mfmodel.py, flopy/mf6/mfsimbase.py
* layer kwarg in `get_data()` in `mfdataarray.py`, deprecated 3.3.5 (June 2022)
* `get_mvr_file()`, `get_mvt_file()`, `get_gnc_file()` in `mfsimbase.py`, removal overdue since 3.3.6
* `get_ims_package()` in `mfsimbase.py`, removal overdue since 3.4
*  fix `mfmodel.py` usage to `get_solution_package()`
=> refactor(mf6): remove deprecated features

flopy/export/shapefile_utils.py
- deprecated 3.3.1 (June 2020)
- remove unused URL
=> refactor(shapefile_utils): remove deprecated SpatialReference usages

autotest/test_model_splitter.py
- add `requires_pkg` to a test case to skip if pymetis not available
=> test: add requires_pkg marker to model splitter test

autotest/conftest.py, autotest/test_generate_classes.py
- parametrize the test fn
- check that release tag may be provided as `branch`
- allow testing custom refs `owner/repo/ref` configured via pytest opt `--ref` or env var `TEST_GENERATE_CLASSES_REF`
=> test(generate_classes): parametrize, allow configuring via CLI/env

autotest/test_mbase.py, autotest/test_modflow.py, flopy/mbase.py
=> fix(BaseModel): don't suppress error if exe not found

autotest/test_get_modflow.py, docs/get_modflow.md, flopy/utils/get_modflow.py
* support `--owner` cli option and corresponding `run_main()` (and other fn) params
* document owner option in `get_modflow.md`
* expand tests
This allows installing from releases posted on e.g. personal forks of modflow6. For instance, after this PR, to install the PRT [development build](https://github.com/aprovost-usgs/modflow6/releases/tag/20230808):
```
get-modflow : --owner aprovost-usgs --repo modflow6
```
=> feat(get-modflow): allow specifying repo owner

.github/workflows/commit.yml, .github/workflows/examples.yml, .github/workflows/regression.yml, .github/workflows/release.yml, autotest/test_generate_classes.py, docs/generate_classes.md, docs/make_release.md, flopy/mf6/utils/generate_classes.py
- add `repo` parameter, in case e.g. a fork is named differently
- add `ref` parameter, deprecate `branch`
- should be generically named since supports hashes, branch names, tags
- update usages in CI from branch to ref
- add tests for short- and long-form commit hashes
- update `commit.yml` and `release.yml` test jobs to use `--dist loadfile`
- tests in `test_generate_tests.py` can't run in parallel due to `pytest-virtualenv`
=> refactor(generate_classes): deprecate branch for ref, introduce repo, test commit hashes

autotest/test_mfreadnam.py, autotest/test_modflow.py, flopy/discretization/grid.py, flopy/mbase.py, flopy/modflow/mf.py, flopy/utils/mfreadnam.py
This fixes a bug from #1737 where loading classic NAM files does not retain any CRS information that may be been stored in the header comment.
- With pyproj installed, the `modelgrid` properties `.proj4` and `.epsg` are generated from the `crs` inputs.
- Without pyproj installed, `.proj4` retains the original string input to crs, and `.epsg` retains a valid integer parsed from the crs input.
This PR adds tests for `flopy.utils.mfreadnam.attribs_from_namfile_header` and checks the same simulations with `Modflow.load` to inspect a few modelgrid properties. This PR was also tested locally without pyproj.
=> fix(modelgrid): retain crs data from classic nam files

autotest/test_export.py, autotest/test_modflow.py, docs/flopy_method_dependencies.md, flopy/discretization/grid.py, flopy/export/shapefile_utils.py, flopy/mbase.py, flopy/modflow/mfdis.py, flopy/modflow/mfsfr2.py, flopy/mt3d/mt.py, flopy/pakbase.py, flopy/plot/plotutil.py, flopy/utils/binaryfile.py, flopy/utils/reference.py
This cleans-up a few remaining references to SpatialReference or related (e.g. "sr"). This extends beyond #1200 and #1892.
Details of changes:
- Some related docstrings improved and expanded
- Remove unused method `_set_sr_coord_info` from `flopy/discretization/grid.py`
- Spatial metadata in `flopy/modflow/mfdis.py` was not actually ignored, but now it actually is ignored and removed, as this should be in classic NAM files
Note that these changes are not related to [`flopy.mf6.utils.reference.SpatialReference`](https://flopy.readthedocs.io/en/3.4.1/source/flopy.mf6.utils.reference.html#flopy.mf6.utils.reference.SpatialReference), which is not deprecated.
=> refactor(expired deprecation): remaining references to SpatialReference

.github/workflows/commit.yml, .github/workflows/optional.yml, autotest/test_export.py, autotest/test_grid.py, autotest/test_gridgen.py, autotest/test_gridintersect.py, autotest/test_mf6.py, autotest/test_model_splitter.py
- close #1905
- run smoke tests with all, some and no optional dependencies on nightly schedule
- in partial dependency availability case, remove 3 randomly chosen dependencies every day
- mark some tests requiring optional dependencies
- only check crs deprecations if pyproj available
=> ci: smoke test with/out optional dependencies, mark more tests

autotest/test_mf6.py, flopy/mf6/data/mfdatastorage.py
Flopy allows some keywords to be excluded from recarrays, like "FILEIN".  This fix makes sure that optional keywords, like "MIXED" are not excluded from recarrays.  Since they are optional their presence adds information to the recarray and they therefore can not be excluded.
=> fix(keyword data): optional keywords (#1909)

flopy/utils/gridintersect.py
This fix uses [`shapely.unary_union`](https://shapely.readthedocs.io/en/stable/reference/shapely.unary_union.html) (or [`shapely.ops.unary_union`](https://shapely.readthedocs.io/en/1.8.5/manual.html#shapely.ops.unary_union)) to combine a list of 1 or more [Multi]LineString geometries into one geometry.
Ideas on a test for this would be welcome.
Closes #1922
=> fix(GridIntersect): combine list of geometries using unary_union

flopy/modpath/mp7particledata.py
- close #1933
- update docstring, keep default False (avoid potentially breaking change)
=> fix(ParticleData): fix docstring, structured default is False

autotest/test_generate_classes.py, flopy/mf6/utils/generate_classes.py
- previously `branch` arg was mistakenly ignored even when provided
- recently deprecated but we still want to support it for now
- add `repo` parameter to `download_dfn()` function
- fix logging output to use `ref`, not `branch`
- fix test to use `ref` correctly
=> fix(generate_classes): use branch arg if provided

autotest/regression/test_mf6.py, autotest/test_mf6.py, flopy/mf6/mfsimbase.py
Method remove_model removes all references to the model from the simulation namefile.  Tests added to autotest.
=> fix(remove_model): remove_model method fix and tests (#1916)   

autotest/test_gridutil.py, flopy/utils/gridutil.py
This PR adds a simple function that constructs vertices, cell2d, and other arguments needed to construct a flopy ModflowGwfdisv object.  This function is mostly designed for MODFLOW testing purposes, but it may also be generally useful for constructing a DISV grid.  Could be enhanced to remove IDOMAIN=0 cells and to rotate the resulting grid.
```
disvkwargs = get_disv_kwargs(
nlay, nrow, ncol, delr, delc, top, botm, xoff, yoff,
)
disv = flopy.mf6.ModflowGwfdisv(gwf, **disvkwargs)
```
=> feat(gridutil): add function to help create DISV grid

autotest/test_export.py, flopy/export/utils.py
- close #1950
- update tests for easier visual debugging of exported shapefiles
- update `export_contours()` and `export_contourf()` for matplotlib 3.8+ compat
- add `verbose` flag to `export_contours()` to match `export_contourf()`
See [this comment](https://github.com/modflowpy/flopy/issues/1950#issuecomment-1722342691) for context
=> fix(export_contours/f): support matplotlib 3.8+

flopy/mfusg/mfusgbcf.py, flopy/modflow/mfsfr2.py
* minor bugfix in mfusg bcf (resolves #1958)
* add sfr2 channel_geometry_data to docstring
=> Fix usgbcf

autotest/test_triangle.py, flopy/utils/triangle.py
- previously `Triangle.build()` would continue silently if expected output files not found after invoking exe
- raise `FileNotFoundError` immediately instead
- remove unneeded return statements
- [motivation](https://github.com/modflowpy/flopy/discussions/1948#discussioncomment-7017393)
=> refactor(triangle): raise if output files not found

.docs/code.rst
* model splitter RST file wasn't included in any toctree
=> docs(code.rst): add model splitter to API docs

autotest/test_mbase.py, autotest/test_modflow.py, flopy/mbase.py
- close #1633
- followup to #1727 
The motivation here is symmetry of portability &mdash; relative paths with `.exe` suffix will work on non-Windows, and paths without `.exe` suffix will work on Windows, provided the relpath is otherwise identical
=> fix(resolve_exe): support extensionless abs/rel paths on windows

autotest/test_mp7.py, flopy/mbase.py
* close #1817
* consistent with MFSimulation verbosity default
* specify category=UserWarning for warnings in mbase.py
=> fix(mbase): warn if duplicate pkgs or units

.docs/Notebooks/modpath7_structured_example.py, autotest/test_mp6.py, flopy/utils/__init__.py, flopy/utils/modpathfile.py, flopy/utils/recarray_utils.py
- deprecate `ra_slice()`, suggest `numpy.lib.recfunctions.repack_fields()`
- deprecate `recarray()`, suggest `numpy.core.records.fromrecords()`
- add tests demonstrating equivalent usage
- replace occurrences in tests and notebooks
- update docstring examples
- show output instead of assigning to variable
- use [doctest](https://docs.python.org/3/library/doctest.html#module-doctest) to verify examples run correctly
Maybe worth doctesting in CI in future?
=> refactor(recarray_utils): deprecate functions for numpy builtins

autotest/test_binaryfile.py, flopy/utils/binaryfile.py
* close #1939
* previously, omitted totim=0 if compact
* detect compact format by negative nlay
* add mf6 test case courtesy of @mbakker7 
* test mf2005 with compact/non-compact
=> fix(CellBudgetFile): detect compact fmt by negative nlay

autotest/test_generate_classes.py
* avoid failures caused by different DFNs in mf6 develop and master
=> test(generate_classes): skip on master and release branches

.github/workflows/mf6.yml
* previously only files named `test_gw*.py` were run
* run the full mf6 test set minus (as before) example model / regression tests (`test_z*.py`)
* may catch more mf6 integration issues without much extra time (previously `mf6.yml` took ~15min, now ~20)
* prepares also for differently-named models e.g. prt
=> ci(mf6.yml): include more mf6 autotests

autotest/test_model_splitter.py
Set cwd to tempdir in `test_model_splitter.py::test_control_records` to avoid leaving conductivity and well files behind
```
k.l2.0.txt
k.l2.1.txt
k.l2.txt
k33.l2.0.bin
k33.l2.1.bin
k33.l2.bin
wel.1.1.txt
wel.1.txt
wel.2.1.bin
wel.2.bin
```
=> test(model_splitter): use tempdirs

.github/workflows/mf6.yml
* `modflowpy/install-gfortran-action` will be retired soon
=> ci: swap setup-fortran for install-gfortran-action

.github/workflows/commit.yml, .github/workflows/mf6.yml, .github/workflows/rtd.yml
Always run commit-triggered workflows (`commit.yml`, `rtd.yml`, `mf6.yml`) on push.
This was suggested recently by @spaulins-usgs. CI testing work on a personal fork before opening a PR avoids consuming the upstream org's actions quota. To do this currently requires adding the branch name to the workflow's `on.push.branches`, then removing it before the PR is merged. This is inconvenient and easily neglected.
It seems safe to assume contributors generally want CI to run on their fork. To exclude a branch, [`branches-ignore`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore) can be used if needed.
Existing branch filters are still kept for PR triggers.
=> ci: remove branch filters from push trigger

autotest/test_export.py, autotest/test_gridgen.py, autotest/test_plot_map_view.py, flopy/discretization/structuredgrid.py, flopy/discretization/vertexgrid.py, flopy/export/utils.py, flopy/plot/map.py
* refactor some disu test grids/models into fixtures
* update `PlotMapView.contour_array()` docstring
* add `layer` param to `flopy.export.utils.contour_array()`
* pop/pass `layer` kwarg to `contour_array()` in `export_array_contours()`
* test `export_array_contours()` disu grids with constant and variable ncpl
* test `PlotMapView.contour_array()` various array dimensions, with/without layer
* motivated by #1953
=> refactor(contour_array): add layer param, test disu contours and export

.docs/Notebooks/mf6_parallel_model_splitting_example.py, autotest/test_model_splitter.py, flopy/mf6/utils/model_splitter.py
* add check for no boundary condition instances in list based input packages. Do not write package in this case
* update options setting routine to respect previously set options for split models 
* remove maxbound variable from mapped_data for list based input packages. Allows for dynamic maxbound setting by flopy built ins
=> update(model_splitter.py): 

flopy/modflow/mf.py, flopy/modflow/mfuzf1.py
* `nwt_11_fmt` parameter/logic from `mfuzf1.py`, deprecated 3.3.1 (June 2020)
* raise `ValueError` if `ml.version` is "mfusg" in `mf.py`, deprecated 3.3.4 (August 2021)
=> refactor(modflow): remove deprecated UZF option, disallow USG

flopy/modflow/mfsfr2.py
=> refactor(msfsr2): write sfr_botm_conflicts.chk to model workspace

flopy/export/shapefile_utils.py
* https://github.com/modflowpy/flopy/issues/1977#issuecomment-1750915986
=> refactor(shapefile_utils): warn if fieldname truncated per 10 char limit

autotest/test_mfsimlist.py, flopy/mf6/utils/__init__.py, flopy/mf6/utils/mfsimlistfile.py
* add testing for MfSimulationList
=> feat(MfSimulationList): add functionality to parse the mfsim.lst file

autotest/test_gridutil.py, flopy/utils/gridutil.py
* delr is of size (ncol) and delc is of size (nrow).  `get_disu_kwargs` had it wrong in a couple spots.  
* Added test to show that the problem is fixed
* Updated `get_disu_kwargs` to optionally return vertices and cell2d
=> fix(get_disu_kwargs): incorrect indexing of delr and delc

flopy/plot/crosssection.py
* Update the `plot_bc` method to work properly for fully unstructured grids
=> fix(PlotCrossSection): boundary conditions not plotting for DISU

.docs/Notebooks/mf6_simple_model_example.py
This PR fixes the [Simple MODFLOW 6 Model Example](https://flopy.readthedocs.io/en/3.4.3/Notebooks/mf6_simple_model_example.html), which is based on the [Lake Package Example](https://flopy.readthedocs.io/en/3.4.3/Notebooks/lake_example.html) for mf2005. These models set the "head at the cell in the center in the top layer is fixed to `h2`". The older example is correct, but the MF6 example puts this cell in the middle of the upper left quadrant, and not in the center of the top layer.
=> docs(notebooks): fix cell center for Simple MODFLOW 6 Model

autotest/test_mnw.py, autotest/test_modflow.py, flopy/modflow/mfag.py, flopy/modflow/mfchd.py, flopy/modflow/mfdrn.py, flopy/modflow/mfdrt.py, flopy/modflow/mffhb.py, flopy/modflow/mfgage.py, flopy/modflow/mfghb.py, flopy/modflow/mfhyd.py, flopy/modflow/mfmnw2.py, flopy/modflow/mfriv.py, flopy/modflow/mfsfr2.py, flopy/modflow/mfstr.py, flopy/modflow/mfwel.py, flopy/utils/mflistfile.py, flopy/utils/util_list.py
* close #1917
* support pandas dataframe for `node_data`, `stress_period_data` etc for `flopy.modflow.*` pkgs
* just convert to recarray &mdash; not reimplementing data storage with pandas
* test with mnw and wel
=> feat(modflow): support dataframe for pkg data

flopy/utils/binaryfile.py, flopy/utils/datafile.py, flopy/utils/formattedfile.py
Prompted by #1338
Plan originally proposed/implemented but abandoned (see discussion below):
* use 0-based indexing for both `kstpkper` attribute and `get_kstpkper()` method
* deprecate `get_kstpkper()` method (redundant)
* applies to
* `LayerFile` and children
* `BinaryLayerFile` and children
* `CellBudgetFile`
=> refactor(datafiles): use 0-based kstp/kper indexing

.github/workflows/release.yml
* support for mf6 develop and last mf6 release is expected as is, without recreating pkgs
=> fix(release.yml): don't regenerate pkgs from mf6 main on release

.gitattributes
* `.bas` (and other?) model input files might be interpreted as visual basic by [linguist](https://github.com/github-linguist/linguist/tree/master)?
* mark `examples/data` as docs to exclude from linguist processing
* hopefully repo metadata will be corrected to (mostly) python
=> refactor(.gitattributes): exclude examples/data from linguist

.docs/md/optional_dependencies.md, README.md
* list pandas dependency
* minor phrasing updates
* show interactive `get-modflow :`
=> docs(readme): update core/optional dependencies

.docs/Notebooks/gridgen_example.py, autotest/test_gridgen.py, flopy/utils/gridgen.py
* close #2024 
* follow up to #2022 
* support arbitrary paths as `feature`/`features` params to `add_active_domain()`/`add_refinement_feature()`
* support and test shapefile names with/without ".shp" extension (for backwards-compatibility)
* use `ValueError` instead of `Exception` where appropriate
=> fix(gridgen): support arbitrary path-like for shapefiles

autotest/test_gridgen.py
* forgot to mark tests that need `pyshp` in #2026
* fix nightly optional dependency tests
=> test: mark gridgen tests needing pyshp

autotest/test_mf6.py, flopy/mf6/coordinates/modeldimensions.py, flopy/mf6/data/mfdatastorage.py, flopy/mf6/mfpackage.py
Fix is specifically for setting flopy data with recarrays that contain cellids broken out by layer, row, column instead of as a cellid tuple.  Flopy now automatically converts the layer, row, and column into a tuple for storage.
=> fix(recarrays with cellid): fixes bug when setting data as recarrays with cellids

autotest/test_model_splitter.py, flopy/mf6/utils/model_splitter.py
* reset mfarray value for idomain to constant 1 if idomain is unspecified
closes #2027
=> update(remap_array): trap for None type idomain

README.md
* fix broken links
* link to RTD instead of github where possible
* consistently link to latest ReadTheDocs (previously mixed stable/latest)
=> docs(readme): fix broken links, default to latest rtd

.docs/Notebooks/mf6_simple_model_example.py
Previously described GWF as the only supported model, mention GWF and GWT but leave the wording open-ended in view of other forthcoming models (GWE, PRT, SWF)
=> docs(examples): update language re: supported MF6 models

flopy/utils/gridgen.py
See #2059.
Previously, gridgen files could not be read without an instance of the Gridgen class. This PR adds static methods to the gridgen class that read the gridgen files.
=> feat: add static methods to read gridgen quadtreegrid files

.docs/conf.py, .docs/main.rst
* title was previously "Indices and tables &mdash; Flopy Documentation \<version> documentation"
* rename header in `main.rst` from "Indices and tables" -> "FloPy"
* rename project from "FloPy Documentation" -> "FloPy" in `conf.py`
* title will now appear simply as "FloPy &mdash; FloPy \<version> documentation"
* remove the ["Search page"](https://flopy.readthedocs.io/en/latest/search.html) link under "Indices and tables" section in `main.rst` &mdash; leads to an [empty page](https://flopy.readthedocs.io/en/latest/search.html) and there is a search box in the left panel anyway
* update version in `main.rst` to 6.5.0.dev0 (this gets auto-updated whenever docs are built, just updating to stay current with status of `develop` branch)
* update copyright year in `conf.py` from 2022 -> 2024
=> docs(rtd): various cleanup

.docs/Notebooks/mf_error_tutorial01.py
* fix readthedocs pdf build [failure](https://readthedocs.org/projects/flopy/builds/23198771/)
=> docs: fix pdf build (cell fmt in mf_error_tutorial01.py)

autotest/test_notebooks.py, pyproject.toml
* fix nbsphinx build error due to nbconvert https://github.com/jupyter/nbconvert/issues/2092
* removed unused import in `test_notebooks.py`
=> docs(rtd): pin nbconvert < 7.14

autotest/test_particledata.py, flopy/modpath/mp7particledata.py
* fix #2072 
* 1D arrays were passed straight to [`numpy.lib.recfunctions.unstructured_to_structured`](https://numpy.org/doc/stable/user/basics.rec.html#numpy.lib.recfunctions.unstructured_to_structured), which when given an array with N dimensions, attempts to return an N-1 dimensional array of structures, so argument needs to be at least 2D
=> fix(particledata): support 1D numpy array for partlocs

autotest/test_geospatial_util.py, autotest/test_grid.py, autotest/test_grid_cases.py, flopy/discretization/grid.py, flopy/discretization/structuredgrid.py, flopy/discretization/unstructuredgrid.py, flopy/discretization/vertexgrid.py, flopy/utils/geospatial_utils.py, flopy/utils/triangle.py, pyproject.toml
* update test_geospatial_util.py to include GeoDataFrame tests
* add geopandas as optional dependency
=> update(GeoSpatialCollection): add support for GeoDataFrame objects

etc/environment.yml, pyproject.toml
* `python-dateutil` is already [required by pandas](https://github.com/pandas-dev/pandas/blob/24f7db72a3c93a4d0cfa3763724c01ac65d412c6/pyproject.toml#L35), don't need to list it explicitly
* prevents optional dependency CI testing failures [like this](https://github.com/modflowpy/flopy/actions/runs/7738242585/job/21098676085#step:6:447)
=> refactor(dependencies): remove python-dateutil

flopy/mf6/utils/mfsimlistfile.py
* previously error message was e.g. "units input variable must be seconds ,minutes ,hours: abc was specified."
=> fix(MFSimulationList): fix comma spacing in error message

flopy/mf6/utils/model_splitter.py, flopy/plot/map.py
simple fix for soon-to-be deprecated `np.alltrue`. See Issue #2086 - this sorts it out
=> hotfix(numpy 2.0 deprecation)

.github/workflows/optional.yml, autotest/test_grid.py, autotest/test_modflow.py
* add some explanatory comments to `optional.yml`
* check for shapely and scipy before creating voronoi test grids (fix [failing `optional.yml` workflow](https://github.com/modflowpy/flopy/actions/runs/7772742566))
* run all non-regression, non-example tests in `optional.yml` &mdash; previously only smoke tests ran, but it's probably better to be comprehensive
* fix `test_modflow.py::test_pkg_data_containers`
* parametrized test IDs were not path-friendly on Windows, so could fail to create a temp dir named for the test case
* the model could sometimes fail to converge, fix it
=> ci: fix optional dependency workflow

etc/environment.yml, pyproject.toml
* as recommended in https://github.com/numpy/numpy/issues/24300
* once required (pandas, matplotlib) and optional (e.g. scipy) dependencies support v2, a new flopy release can be made 
* #2089 originally proposed CI testing against numpy nightly build but this is not feasible until other deps support v2
=> refactor(dependencies): pin numpy<2 until other reqs support it

flopy/mfusg/mfusgcln.py
Util2d.load expects two dimensions. MfusgCln was previously specifying only the first for 1d arrays, but util2d requires both.
=> fix(usgcln) add explicit second dimension to util2d.load calls

flopy/utils/datautil.py
* avoid warnings [like these](https://modflow6-examples.readthedocs.io/en/latest/_notebooks/ex-gwt-stallman.html#Running-the-example)
=> refactor(datautil): in is_int/float use .item() for np arrays

autotest/test_gridintersect.py, flopy/discretization/grid.py, flopy/utils/gridintersect.py
This PR fixes #2106. 
- Gridintersect now correctly picks up the rotated/offset real-world coordinates for vertex grids.
- Added a `local` kwarg that uses local model coordinates to build intersection grid if set to True.
- Added tests
When looking through the documentation of the Grid objects I came across some entries under Attributes and Methods that do not seem to be used:
- xgrid, ygrid and zgrid are not valid attributes as far as I can tell
- xyzgrid is not an attribute and only available as key in `Grid._cache_dict`
- the method xyvertices also doesn't exist
I removed them now in this PR, but if this is best fixed/improved in a separate PR, let me know.
=> fix(gridintersect): gridintersect does not work for rotated vertex grids

autotest/test_plot_cross_section.py, autotest/test_plot_map_view.py, flopy/discretization/structuredgrid.py, flopy/plot/crosssection.py, flopy/plot/map.py
* added method to check for user supplied axes limits and set with default extents if autoscaling is on
* update docstring in StructuredGrid.neighbors
* add tests for axes limit checks and scaling
closes #2101
=> update(plotting): check for user set axes limits

autotest/test_get_modflow.py, flopy/utils/get_modflow.py
* restore/refactor https://github.com/modflowpy/flopy/commit/4c5e2ee3ec6699f61acb04a5e7bd35407b16f9ff, support for the [ARM mac distribution now on the nightly build](https://github.com/MODFLOW-USGS/modflow6-nightly-build/releases/tag/20240223)
* this change is "opt-in" &mdash; default behavior for users on all platforms remains the same, ARM mac users will get intel binaries if no `--ostag` provided
* ARM mac users can request a native binary from the nightly build with e.g.
```
get-modflow : --repo modflow6-nightly-build --ostag macarm
```
=> feat(get-modflow): support ARM mac nightly build

flopy/mf6/data/mfdata.py, flopy/mf6/data/mfdataarray.py, flopy/mf6/data/mfdatalist.py, flopy/mf6/data/mfdataplist.py, flopy/mf6/data/mfdatascalar.py, flopy/mf6/data/mfdatastorage.py
When transient data contains multiple blocks of data this fix:
1) Makes sure that the first block of data's str/repr gets called (it use to be the last "active" block got displayed)
2) Flopy use to just display just one block of data.  Now, if there are additional blocks, a message is added to the end of the str/repr indicating that more data is present.
Also added text for external data indicating that external is not displayed in the repr (it was not displayed before but no text indicated this)
For example, getting the str of ghb obs continuous data:
`str(model.get_package("ghb_obs").continuous)`
Might produce the following output:
```
{open/close AdvGW_tidal.ghb.obs_continuous_ghb_flows.csv.txt}
(External data not displayed)
...
and 1 additional data blocks
```
=> fix(str and repr): better repr and str output for transient data with multiple blocks (#2058)

autotest/test_binaryfile.py, flopy/utils/binaryfile.py
feat get budget by second package name paknam2
=> feat get budget by second package name `paknam2`

autotest/test_grid.py, flopy/discretization/structuredgrid.py
This is a general refactor of `get_cell_vertices()` to raise helpful exception messages, improve the docstrings, and add some missing tests.
=> refactor(get_cell_vertices): raise helpful messages, improve docs, add tests

autotest/test_get_modflow.py, flopy/utils/get_modflow.py
* support installing parallel windows build with `--repo modflow6-nightly-build --ostag win64par`*
* https://github.com/MODFLOW-USGS/modflow6/pull/1682
*maybe consider generalizing in future &mdash; instead of hardcoding supported asset names, dynamically discover them from the release info? in particular, if assets are expected to change as more mf6 variants (architecture, parallel/netcdf, etc) are included
=> feat(get-modflow): support windows parallel nightly build

autotest/test_mbase.py, flopy/mbase.py, flopy/mf6/mfsimbase.py
The printout of a MF6 run can be pretty long, especially if there are many time steps. While it is possible turn off printing altogether, it can be useful to allow the user to customize the printing. This PR suggest to add a callable the will be use during the model instead of the builtin `print` function.
Setting up a model:
```python
import flopy
sim_name = 'AdvGW_tidal' 
sim_ws = 'examples/data/mf6/test005_advgw_tidal'
sim = flopy.mf6.MFSimulation.load(
sim_name=sim_name,
exe_name=exe_name,  # not shown here
sim_ws=sim_ws,
)
```
Defining a custom print callable:
```python
from time import sleep
class CustomPrint:
"""
Custom print of MF6 output.
This prints the line containing 'Solving:' in place, i.e. creating
an up-counting effect for the number of the time step. The last time
step in …
```
=> feat: add optional custom print callable

autotest/regression/test_mf6.py
* accidentally broken by #2124
=> test(regression): fix syntax causing regression test failures

flopy/mf6/coordinates/modeldimensions.py, flopy/mf6/coordinates/modelgrid.py, flopy/mf6/utils/mfenums.py
* This first PR doesn't really do anything, except define model shapes and cellids for dis2d
* A DIS2D grid does no have layers or a top array, and botm and idomain have shape (nrow, ncol)
* Also considering DISV2D (no layers)
* Also considering renaming of DISL to DISV1D for 1D line network described by vertices
* No testing yet
* A modelgrid for this discretization type has not been addressed yet
* Unclear what type of plotting and export to support
=> feat(dis2d): limited support for a 2D structured grid (for overland flow)

.docs/Notebooks/mf6_mnw2_tutorial01.py, autotest/test_modflow.py, flopy/modflow/mfmnw2.py, flopy/modflow/mfriv.py, flopy/utils/util_list.py
* motivated by #2135
* followup to #2010 
* patch a few remaining gaps in support for dataframes
* update `mf6_mnw2_tutorial01.py` to use dataframe pkg input
* update a test in `test_modflow.py` to use dataframe pkg input
=> fix(modflow): dataframe support was patchy in a few packages

flopy/mf6/mfmodel.py, flopy/mf6/mfsimbase.py
Adding this PR because:
* we should be able to define time discretization for a simulation structure prior to adding models and packages
* models are a seperate entity that underly a simulation object
* IMS and TDIS are the only simulation based packages
*a simulation object should be able to be written without a model attached to it
* model objects should be able to be read with no packages attached
=> update(MFSimulationBase): allow simulations to have no attached models

flopy/utils/flopy_io.py, flopy/utils/sfroutputfile.py
The `delim_whitespace` parameter on `read_table()` and `read_csv()` is [deprecated](https://pandas.pydata.org/docs/whatsnew/v2.2.0.html#other-deprecations), use `sep="\\s+"` instead
=> chore(pandas): use sep instead of deprecated delim_whitespace

autotest/regression/test_mf6.py, flopy/mf6/data/mfdataarray.py, flopy/mf6/mfpackage.py
Empty transient array blocks were not being read or written correctly.
=> fix(empty transient arrays): #2145

.docs/Notebooks/nwt_option_blocks_tutorial.py, autotest/test_uzf.py, flopy/modflow/mfwel.py, flopy/pakbase.py, flopy/utils/optionblock.py
This attribute is documented [here](https://flopy.readthedocs.io/en/3.6.0/Notebooks/nwt_option_blocks_tutorial.html#Building-an-OptionBlock-from-scratch), but unfortunately is a common typo. The backwards compatible change in this PR shows a DeprecationWarning if the typo attribute name is used (either get or set).
=> fix(OptionBlock): deprecate attribute typo 'auxillary' -> 'auxiliary'

autotest/test_lgrutil.py, flopy/utils/lgrutil.py
* `test_lgrutil.py` fails with numpy>=2.0.0rc1
* wrap numpy scalars with `float()` to avoid loss of precision, per https://numpy.org/devdocs/numpy_2_0_migration_guide.html#changes-to-numpy-data-type-promotion
* use builtin types in custom output data structures, not mixed builtins and np types &mdash; this seems preferable in general, and here in particular for `lgr.get_exchange_data()`
=> refactor(lgrutil): coerce numpy types to builtins for np2 compat

flopy/export/vtk.py
Instead of hardcoding which arrays to include in vtk pathline export, include all numeric arrays present in the pathline data
=> feat(vtk): include all arrays on pathline input

autotest/test_grid.py, flopy/utils/cvfdutil.py
* Changed area_of_polygon and centroid_of_polygon to use shapely calculations
* Close #2150
* Added test, which uses a polygon that was failing with the previous implementation
Decided to use shapely calculations instead of our own flopy calculations.  This should much more robust for real-world models, such as the one described in #2150.
=> fix(cvfdutil): polygon area and centroid calculations now use shapely

.github/workflows/rtd.yml, autotest/test_export.py, autotest/test_grid.py, autotest/test_gridutil.py
Fix [optional dependency CI tests](https://github.com/modflowpy/flopy/actions/runs/8875519001/job/24365119996) by marking tests requiring shapely. Also, it seems netcdf4-python is no longer happy with python3.8 on mac.
=> test: mark tests requiring shapely

autotest/test_gridgen.py, flopy/utils/cvfdutil.py, flopy/utils/gridgen.py
* remove near-duplicate vertices produced by GRIDGEN, with tunable precision
* fix #1492
=> fix(gridgen): trap duplicate vertices #1492

flopy/mf6/mfmodel.py, flopy/mf6/utils/output_util.py
* add `budgetkey` param to `MF6Output` and pass it down to `MF6ListBudget` in `MF6Output.__list()`
* update `MFModel.output` to set `budgetkey` to "MASS..." instead of volume for transport models
* fix #2087
=> fix(mfmodel): fix budgetkey for transport models

autotest/test_modflow.py, flopy/utils/util_list.py
* close #2141
* ndarray is treated as before &mdash; only named data structures (recarray and dataframe) are considered, to avoid questions about where to put the kper column
=> feat(MfList): support kper field in stress period data

autotest/conftest.py
This minor enhancement will expand the pytest header to show which packages and versions from the "test" extra are installed. It should help in situations like #2180
---
New header would look something like this:
```
============================= test session starts ==============================
platform linux -- Python 3.8.18, pytest-8.2.0, pluggy-1.5.0 -- /opt/hostedtoolcache/Python/3.8.18/x64/bin/python
cachedir: .pytest_cache
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
required packages: numpy-1.24.4, matplotlib-3.7.5, pandas-2.0.3
optional packages: affine-2.4.0, descartes-1.1.0, fiona-1.9.6, geojson-3.1.0, geopandas-0.13.2, imageio-2.34.1, …
```
=> test: show test package extras in pytest report header

flopy/utils/gridintersect.py
* check `np.isclose` instead of exact equality in `find_position_in_array()` to allow for floating point error after round-trip coordinate transformation &mdash; if a coordinate passes the fuzzy check, clamp it to the cell boundary
* fix #2049
=> fix(gridintersect): relax cell boundary checks with np.isclose

autotest/test_gridgen.py
* fix [failing optional dependency CI tests](https://github.com/modflowpy/flopy/actions/runs/8966183383)
=> test(gridgen): mark test requiring shapely and pyshp

flopy/mf6/data/mfdatastorage.py, flopy/mf6/data/mffileaccess.py
[Recent flopy changes](https://github.com/scottrp/flopy/commit/56b175defff2178ef0dc7d14e427f80b5fd0895c) broke reading of non-layered input, as mentioned [here](https://github.com/modflowpy/flopy/issues/2053).
This PR fixes the situation where non-layered input is read from a griddata block and all of the values are provided on one line.  This is the case for reading idomain for a [testmodel](https://github.com/MODFLOW-USGS/modflow6-testmodels/tree/master/mf6/test019_VilhelmsenLGR_nr) from [this file](https://github.com/MODFLOW-USGS/modflow6-testmodels/blob/master/mf6/test019_VilhelmsenLGR_nr/TM9_parent_GN.dis.idomain.dat).
=> fix(MFFileAccessArray): read_text_data_from_file modified for non-layered

autotest/test_postprocessing.py, flopy/mf6/utils/postprocessing.py
This branch fixes a bug in get_structured_faceflows (introduced in PR #1968) that caused flf to become 0 for cells for which the cell below has idomain -1. Also includes a new test for it in test_postprocessing.py
=> Fix problem with get_structured_faceflows

.docs/Notebooks/mf6_data_tutorial01.py, flopy/mf6/mfsimbase.py
Tutorial01's name was too long for MODFLOW.  Additionally, it did not define a top and botm.
Added a verbosity setter that automatically converts numerical verbosity values to the verbosity enumeration value, so that interval values are kept consistent.
=> fix(tutorial, verbosity setter): fixed tutorial model name and verbosity setter (#2182)

autotest/test_export.py, flopy/mbase.py, flopy/pakbase.py, flopy/utils/util_list.py
This PR changes deprecated `.to_shapefile()` functions to raise AttributeError with a helpful message.
These are the affected functions:
- [`flopy.utils.util_list.MfList.to_shapefile`](https://flopy.readthedocs.io/en/3.6.0/source/flopy.utils.util_list.html#flopy.utils.util_list.MfList.to_shapefile)
- [`flopy.pakbase.Package.to_shapefile`](https://flopy.readthedocs.io/en/3.6.0/source/flopy.pakbase.html#flopy.pakbase.Package.to_shapefile)
- [`flopy.mbase.BaseModel.to_shapefile`](https://flopy.readthedocs.io/en/3.6.0/source/flopy.mbase.html#flopy.mbase.BaseModel.to_shapefile)
While these functions have been deprecated since 3.2.4 released in 2016 ([changelog](https://flopy.readthedocs.io/en/3.6.0/md/version_changes.html#version-3-2-4)), they were never documented as such. Thus a helpful …
=> refactor(expired deprecation): raise AttributeError with to_shapefile

autotest/test_binaryfile.py, flopy/utils/binaryfile.py
This PR deprecates `binaryread_struct()` (documented [here](https://flopy.readthedocs.io/en/3.6.0/source/flopy.utils.binaryfile.html#flopy.utils.binaryfile.binaryread_struct)), since it is not used. Before FloPy migrated to GitHub, this function was replaced by `binaryread()` as the default method used internally due to better performance of NumPy's [`fromfile()`](https://numpy.org/doc/stable/reference/generated/numpy.fromfile.html) over struct's [`unpack()`](https://docs.python.org/3/library/struct.html#struct.unpack).
This PR also improves the docstring for `binaryread()`, and provides low-level testing/coverage for both methods.
=> refactor: deprecate unused flopy.utils.binaryfile.binaryread_struct

.readthedocs.yml
The RTD builds have stopped working for a few weeks now, with the error occurring while processing the PDF documents with:
```
...
! TeX capacity exceeded, sorry [main memory size=5000000].
\FV@Space ...ionary {\copy \sphinxvisiblespacebox 
}{\sphinxafterbreak } {\ke...
l.7888 ...TC: datetime.datetime.now(datetime.UTC).
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on flopy.log.
...
```
This type of fatal error is due to insufficient memory on the worker node. [Troubleshooting docs](https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html#reduce-formats-you-re-building) suggests to reduce the number of output formats.
This PR disables the following output formats.
- PDF. For flopy 3.6.0, this document is 2145 pages in US Letter page …
=> ci(RTD): build only html and htmlzip -- disable PDF to conserve memory

flopy/utils/gridgen.py
Docstrings and kwarg names didn't match, fix the docstrings
=> docs(gridgen): fix smoothing level kwarg names in docstring

etc/environment.yml, pyproject.toml
Avoid `datetime.utcnow()` deprecation warning to fix broken nbsphinx galleries on RTD.
Another option is a warning filter `warnings.simplefilter("ignore", DeprecationWarning)` in all the examples but pinning is easier and I think we want to know ASAP when something needs an update
=> chore(deps): require jupyter_client>=8.4.0 for now

autotest/regression/test_mf6.py, autotest/test_export.py, autotest/test_geospatial_util.py, autotest/test_gridgen.py, autotest/test_modpathfile.py, autotest/test_mp6.py, autotest/test_particledata.py, autotest/test_sfr.py, autotest/test_shapefile_utils.py
* devtools now [replaces square brackets](https://github.com/MODFLOW-USGS/modflow-devtools/commit/90316a1cca281ac36062da946374145bda421d52) from parametrization in path names
* also need to `name_map` pyshp -> shapefile since `requires_pkg` is strict now
=> test: reenable parametrization in gridgen tests, update markers

.github/workflows/commit.yml, .github/workflows/mf6.yml, .github/workflows/rtd.yml
* only allow one concurrent workflow run per branch
=> ci: add concurrency groups to commit-triggered workflows

.docs/Notebooks/lgr_tutorial01.py, .github/workflows/rtd.yml, autotest/regression/test_mf6.py, autotest/regression/test_mf6_pandas.py, flopy/mf6/coordinates/modeldimensions.py, flopy/mf6/data/mfdataplist.py, flopy/mf6/data/mfdatastorage.py, flopy/mf6/data/mffileaccess.py
Support for binary file option with exchange package exchangedata block. In order to support this the column headers for the cellid data (layer, row, column) are renamed in the binary file header to make the unique.  Unique column header names are generated by adding the cellid field name (<cellidm1> or <cellidm2>) as a prefix to the <layer>, <row>, <column>, <node> names.  For example, originally column header for layers was just "layer".  Flopy changes this column header to "cellidm1_layer" for <cellidm1> and "cellidm2_layer" for <cellidm2>.
=> feat(exg pkg binary file support)

autotest/test_binaryfile.py, autotest/test_cellbudgetfile.py, autotest/test_formattedfile.py, flopy/utils/binaryfile.py, flopy/utils/datafile.py, flopy/utils/formattedfile.py
This feature adds a `.headers` property for a pandas data frame of the headers of various data files, including HeadFile, FormattedHeadFile, UcnFile and CellBudgetFile. This is a modern accessor to the headers, which is created internally using:
pd.DataFrame(self.recordarray, index=self.iposarray)
where the index is the file position to the start of each array. Text fields are decoded to `str` types (rather than dealing with bytes types, which is probably a hang-over from Python2). Int32 types are left as-is, except for iposarray which should be int64 to read large files >2GB. Float32 types are also left as-is, since these would otherwise have a lossy conversion to float64.
With the CellBudgetFile, the headers vary depending on the type of budget file. For instance, "classic" files …
=> feat(datafile): add .headers property with data frame

autotest/test_binaryfile.py, autotest/test_cellbudgetfile.py, autotest/test_formattedfile.py, flopy/utils/binaryfile.py, flopy/utils/datafile.py
This PR has a few aims related to data files, including FormattedHeadFile, HeadFile and CellBudgetFile.
These files have a "number of records" property that was implemented with `get_nrecords()`. This "length of the object" measure is more naturally done with [`__len__`](https://docs.python.org/3/reference/datamodel.html#object.__len__), i.e. `len(headsfile)`.
It is advised to prefer the `len()` approach, so instances of `get_nrecords()` for these files show a DeprecationWarning.
The CellBudgetFile also has a `.nrecords` property. It is also advised to show a DeprecationWarning with this property.
This PR also fixes a bug with `get_nrecords()` shown here:
https://github.com/modflowpy/flopy/blob/ea3e475c2a566872670d067b7c611861d4be8c54/flopy/utils/datafile.py#L427-L430
the bug is that …
=> refactor(datafile): use len(obj) rather than obj.get_nrecords()

autotest/regression/test_mf6.py
While this regression test "passes", this PR resolves two errors to _actually_ compare concentrations results:
1. Fix typo for filename "gwt_mst03.unc" ->"[gwt_mst03.ucn](https://github.com/modflowpy/flopy/blob/11ada32e289c25634e1e058a772b439bb052b8b9/examples/data/mf6/create_tests/test_transport/expected_output/gwt_mst03.ucn)"
2. Compare the two concentration files with `compare_heads` with `text="concentration"`.
---
Further explanations to the fixes:
1. The `flopy.utils.compare` module "passes" (returns `assert True`) if there are there are not two files to compare, which is an unusually silent approach. This was due to the filename typo.
2. These files are not MT3D-style concentration files, and would raise exceptions if read with `UcnFile`. They must be read with `HeadFile(..., …
=> fix(regression): corrections to test_create_tests_transport

autotest/test_binaryfile.py, autotest/test_cellbudgetfile.py, flopy/utils/binaryfile.py
This fixes issues while reading some binaryfiles with auto precision detection, and also modernizes a few aspects of flopy.utils.binaryfile left-over from python2.
There are two changes to `flopy.utils.binaryfile.binaryread()`:
1. Raises EOFError if attempting to read data beyond the end-of-file
2. Deprecate `vartype=str`, since `bytes` is the the return type with Python3
Other refactors:
- Simplify conventional ASCII range checks by converting `bytes` to a list of int, then check if bytes are within range
- Remove checks if bytes are not str, and use `.encode("ascii")` where appropriate
---
Reading a cell budget file that contains `imeth=5` with `precision="auto"` (the default):
```
python -c "from flopy.utils import *; print(CellBudgetFile('examples/data/preserve_unitnums/testsfr2.ghb.cb …
```
=> fix(binaryread): raise/handle EOFError, deprecate vartype=str

flopy/mf6/utils/binarygrid_util.py
The get_iverts() method can work without knowing the grid type.  The PR uses the shape of iavert rather than grid properties so that the method works for any grid type, including new ones just added for ongoing surface water model development.
=> refactor(binarygrid_util): refactor get_iverts to be general

.docs/Notebooks/mf6_simple_model_example.py, .docs/Notebooks/mfusg_conduit_examples.py, .docs/Notebooks/sfrpackage_example.py, .docs/Notebooks/uzf_example.py, autotest/regression/test_mf6.py, autotest/test_binaryfile.py, autotest/test_cbc_full3D.py, autotest/test_cellbudgetfile.py, autotest/test_formattedfile.py, flopy/utils/binaryfile.py, flopy/utils/datafile.py, flopy/utils/formattedfile.py
Now that data files have a `.headers` data frame property (#2221), there is no need to have methods that print parts of this information to stdout (they return `None`). This PR deprecates the following:
- `list_records()`: use `headers` instead
- `list_unique_records()`: use `headers[["text", "imeth"]].drop_duplicates()` instead
- `list_unique_packages(to=True/False)`: use `headers.paknam.drop_duplicates()` or `headers.paknam2.unique()` (there are a few ways)
The last two only apply to CellBudgetFile. This PR does not apply to `flopy.mf6.utils.mfobservation.list_records()`.
=> refactor(datafile): deprecate list_records() and other list_ methods

autotest/test_uzf.py
Checking `test_uzf_negative_iuzfopt` with NumPy 2.0 (xref #2153), this test failed. The test criteria originally had several issues, including confusing `extpd` as `pet`. These issues are fixed in this PR to properly compare expected array values.
=> fix: test_uzf_negative_iuzfopt

.github/workflows/benchmark.yml, .github/workflows/commit.yml, .github/workflows/examples.yml, .github/workflows/mf6.yml, .github/workflows/optional.yml, .github/workflows/release.yml, autotest/test_export.py, etc/environment.yml, flopy/mf6/data/mfdatastorage.py, pyproject.toml
Remove numpy upper bound to close #2153. Also fix `@requires_pkg` usage in `test_export.py`, replace deprecated `itemset` in `mfdatastorage.py`, and bump some CI jobs to Python 3.9.
This PR required updates on the MF6 side:
* https://github.com/MODFLOW-USGS/modflow6/pull/1886
* https://github.com/MODFLOW-USGS/modflow6/pull/1887
=> refactor(dependencies): support numpy 2

flopy/plot/map.py
Defaulting to layer 0 for arrays where each cell is assigned a color is sensible but for pathlines it seems more natural to include all layers for complete pathlines. This might (pragmatically) be seen as a bugfix rather than a breaking change?
=> fix(PlotMapView): default to all layers in plot_pathline()

autotest/test_get_modflow.py, flopy/utils/get_modflow.py
Tests will only pass after an ARM distribution is added to the [executables](https://github.com/MODFLOW-USGS/executables) release
=> refactor(get-modflow): support ARM macs by default (previously opt-in)

.github/workflows/benchmark.yml, .github/workflows/commit.yml, .github/workflows/examples.yml, .github/workflows/rtd.yml
Workaround https://github.com/MODFLOW-USGS/executables/issues/33.
=> ci(macos): use intel triangle build for now

flopy/utils/rasters.py
Just a small fix on dtype reclassification when creating a `Raster` object.
I was also tempted to reclassify `float` as `FLOAT64` and `int` as `INT64` because based on my quick search, Python's `float` is represented as 64-bit, and `int` is pretty much unbounded. But then maybe these might be intended for optimization purposes as `FLOAT32` and `INT32` are practically sufficient in most cases.
=> fix(Raster): reclassify np.float64 correctly

autotest/test_binaryfile.py, flopy/utils/binaryfile.py
Fix the write logic for head file reversal to properly write each layer. Add a test for each discretization type. Fix in-place reverse by writing to a temp file first then renaming. Improve docstrings.
@cneyens could you check if this resolves #2246 on your end?
=> fix(HeadFile): fix dis reversal, expand tests

.github/workflows/rtd.yml
The RTD build integration expects artifacts named according to the pattern `prefix-sha`. Previously the workflow used the current ref's hash, not the hash of the selected ref. Fix it so the RTD build can find the proper artifacts. Also add the workflow trigger to the concurrency group key.
=> ci(rtd): fix artifact upload sha, update concurrency key, cleanup

.docs/Notebooks/raster_intersection_example.py, autotest/test_gridintersect.py, flopy/utils/rasters.py, flopy/utils/triangle.py
* add feature `to_crs()` for re-projecting rasters
* add static method `raster_from_array()` to allow users to make rasters from data
* update `resample_to_grid()`
- removed multithread and thread_pool kwargs
- added initial check for raster/modelgrid intersection
=> update(Raster): add new methods and checks

autotest/test_binaryfile.py
Fix the failing optional dependency CI tests: https://github.com/modflowpy/flopy/actions/runs/10140767481/job/28036619744#step:7:3899
=> ci: add shapely marker to binaryfile test

autotest/test_mf6.py, flopy/mf6/mfmodel.py
This fixes MFModel.get_ims_package which is a method that returns the relevant IMS through the simulation name files's solution group block.
=> fix(mfmodel): fix get_ims_package

.github/workflows/release.yml
This is no longer needed/supported as of #2240
=> ci(release): remove --approve from update_version.py call

flopy/mfusg/mfusgbcf.py, flopy/modflow/mfbcf.py
=> docs(mfbcf): 'storage coefficient' -> 'specific yield'

flopy/utils/rasters.py
Address https://github.com/modflowpy/flopy/discussions/2273#discussioncomment-10268125
=> update(resample_to_grid): filter raster nan values from scipy resampling routines

.docs/Notebooks/export_vtk_tutorial.py, .docs/Notebooks/plot_cross_section_example.py, .docs/Notebooks/plot_map_view_example.py
#2264 removed the `notebook_utils.py` module but neglected to remove this dependency from 3 examples:
- `export_vtk_tutorial.py`
- `plot_cross_section_example.py`
- `plot_map_view_example.py`
This is why these are missing from the develop version of the RTD site.
This PR inlines the shared models which previously lived in `notebook_utils.py`. This duplication will go away once we have a models API as proposed in #1872.
=> fix(examples): restore example notebooks skipped after #2264

autotest/test_grid.py, autotest/test_model_splitter.py, flopy/discretization/unstructuredgrid.py, flopy/mf6/mfmodel.py, flopy/mf6/utils/model_splitter.py, flopy/utils/rasters.py
* force remapping to be calculated from iac, ja array
* add 0 digit padding to file names
* update UnstructuredGrid, add cell2d input parameter and property method
* add clean_iverts() to UnstructuredGrid to remove duplicated vertex and invert information
* update testing for new features
=>  updates(model_splitter.py): update UnstructuredGrid support

cliff.toml
Relax the patterns in `cliff.toml` so commit messages like `updates(...): ...` are included in the refactor group in the auto-generated changelog at release time
=> chore(git-cliff): relax changelog patterns to accomodate 'updates' type

flopy/discretization/structuredgrid.py, flopy/discretization/vertexgrid.py, flopy/mf6/mfmodel.py
New MODFLOW 6 surface water models (overland flow and channel flow) use two dimensional and one dimensional grids.  This PR adds an elegant fix to allow the grids to work properly with these new grid types (DISV1D, DIS2D, and DISV2D).  These new grids do not have "top" but do have a "bottom" array (not "botm").  Plan for the future is to split up VertexGrid and StructuredGrid to support other types of grids.
=> fix(modelgrid): add more support for mf6 surface water models 

flopy/discretization/grid.py, flopy/discretization/vertexgrid.py
The Channel Flow (CHF) Model simulates one dimensional surface water flow in a connected line network.  This PR adds some minimal support to the VertexGrid class to allow plotting of the 1D network.  There was some older broken support for "cell1d", which is fixed here to work with the new mf6 CHF model.
=> feat(cell1d): add support for 1D vertex grids

cliff.toml
Commit messages were omitted from the generated changelog if they had any leading whitespace. Fix it.
=> chore(git-cliff): trim leading whitespace in commit messages

.github/workflows/release.yml
Explicitly add files to commit after updating the version number and generating the changelog. Previously we used `git add -A`. As of `git-cliff-action@v4` this includes the `git-cliff` binary and related content which is apparently installed to the working directory.
=> ci(release): explicitly specify files to commit

autotest/test_particledata.py, flopy/modpath/mp7particledata.py
Vertical extent is miscalculated for structured grids when providing a cell index, only the first layer is handled properly. This causes bad results from `*ParticleData.to_coords()` and `.to_prp()`.
=> fix(mp7particledata): fix get_extent() vertical extent calculation

autotest/test_export.py, flopy/export/utils.py, flopy/utils/datautil.py
This PR aims to address the issue raised in discussion https://github.com/modflowpy/flopy/discussions/2308
=> fix(array3d_export): fix exporting of array3d to shp

flopy/utils/binaryfile.py, flopy/utils/datafile.py, flopy/utils/formattedfile.py
The `reverse()` methods on `HeadFile` and `CellBudgetFile` [would fail](https://github.com/jdhughes-usgs/GW3099-2024/actions/runs/10865950745/job/30152962324#step:11:155) on an in-place reversal if the system temp dir occupied a different drive than the original file. Use `shutil.move()` instead of `Path.replace()` per [SO discussion here](https://stackoverflow.com/a/21116654/6514033).
=> fix(binaryfile): accommodate windows drives for in-place reversal 

autotest/test_export.py
Quick fix on `test_export_array`
=> test(export_array): check exported raster's bounds with modelgrid

flopy/utils/get_modflow.py
https://github.com/orgs/community/discussions/140079
=> fix(get_modflow): accommodate missing ratelimit info on api response

autotest/test_plot_cross_section.py, autotest/test_plot_map_view.py, flopy/plot/crosssection.py, flopy/plot/map.py, flopy/plot/plotutil.py, flopy/utils/geometry.py
fixes and updates included with feature:
* filter very short/small intersection segments from cross-sectional plotting routine
* sort and assure vertex order is correct for intersected cross-sectional segments
* improve geometry.project_point_onto_xc_line() calculation routine.
* update reproject_modpath_to_crosssection()
closes #2299
=> Feat(plot_centers): add plot_centers support to PlotMapView and PlotCrossSection

.github/workflows/commit.yml, .github/workflows/rtd.yml, flopy/utils/zonbud.py
fix failing CI (setup-micromamba@v2 issue on Windows)
=> Fix(ZoneFile6.load): Add split statement to input read

.github/workflows/commit.yml, .github/workflows/rtd.yml, flopy/utils/rasters.py, flopy/utils/zonbud.py
* remove nan masking from standard scipy resampling methods
* allow extrapolate_edges kwarg to be applied to nearest neighbor resampling
=> fix(resample_to_grid): fix unintended extrapolation 

.github/workflows/commit.yml
The test step was suppressing errors, I think because we ran coverage immediately after. Move coverage to a subsequent step. This reveals a few failing tests which are not addressed in this changeset.
=> ci(commit.yml): fix silently failing test step

.github/workflows/commit.yml, autotest/test_generate_classes.py, autotest/test_mp7.py
Fix tests whose failures were suppressed before #2335:
* skip snapshot on mac for `test_mp7.py::test_mp7_output`, mp7 results differ slightly for some reason
* fix the `venv` bin/lib directory names on Windows in `test_generate_classes.py`
=> test(multiple): fix failing tests

autotest/test_mp7.py, flopy/modpath/mp7.py
This PR exposes the porosity parameter of Modpath7Bas in Modpath7's convenience method, create_mp7. This idea is raised in https://github.com/modflowpy/flopy/discussions/2339.
=> refactor(Modpath7.create_mp7): expose porosity parameter of Modpath7Bas

autotest/test_export.py, autotest/test_gridgen.py, flopy/export/shapefile_utils.py, flopy/export/utils.py, flopy/mf6/data/mfdatalist.py, flopy/mf6/data/mfdataplist.py, flopy/mfusg/mfusgdisu.py, flopy/utils/util_list.py
This PR aims to address the issue raised in discussion https://github.com/modflowpy/flopy/discussions/2309
- generalize setting of array shape for different grid types
- re-use preceding spd array data
- update relevant test
- generalize setting of array shape for different grid types
- re-use preceding spd array data
- create separate case for disu
- update relevant test
- compare mf6 and non-mf6 shp export (riv data)
- if package has timeseries data, transientlist elements are all of object type
- if package has timeseries data, mflist elements are all of object type
I did remove the bare except clause in `flopy.export.shapefile_utils.model_attributes_to_shapefile` but it caused several tests to fail. These issues were addressed in the last commits. However, in hindsight, I'm not sure …
=> fix(masked_4D_arrays): allow re-use of preceding spd data if empty

autotest/test_gridintersect.py, flopy/utils/gridintersect.py
Fix for #2342
- fix typo in shapely.multilinestrings
- fix issue with np.apply_along_axis
- consider geometry collections when computing overlaps
- add test for vertex mode
- add inactive test for structured mode (not yet working)
Notes: 
`np.apply_along_axis` was reducing result from multiple GeometryCollections to a single MultiLineString causing duplication of shapes in the intersection result. 
~~The test for GeometryCollections in "structured"-mode is commented out as it was failing and I don't have the time at the moment to figure that out. I will open a separate issue, along with some other GridIntersect to-do's (see #2344).~~
EDIT: structured support will be dropped in future releases (see #2344).
=> fix(gridintersect): typo shapely function call within gridintersect #2342

flopy/utils/get_modflow.py
https://github.com/MODFLOW-USGS/modflow6/pull/2037
=> Add win64ext to get_modflow ostag list

flopy/mf6/mfmodel.py, flopy/mf6/mfpackage.py, flopy/mf6/mfsimbase.py, flopy/utils/check.py
Deprecate MF6 checks for the rest of the 3.x series. Consider either reworking/replacing them in 3.10+ in a backwards-compatible way, or removing them and making the `.check()` methods on simulation model/package base classes no-ops, pending a 4.x rework.
The sense after discussion is that the checks have limited utility at the moment, a few relevance/correctness issues, and see little use. Deprecating should help to determine if anyone is relying on them while we investigate how deeply they are woven into the existing framework.
=> refactor(mf6): deprecate mf6 checks

flopy/utils/datafile.py
Codacy began detecting a "severe" pylint E1126 `invalid sequence index` violation in #2362.
> Sequence index is not an int, slice, or instance with __index__
The issue pre-existed that PR, I think the format changes just revealed it. We could just ignore it in the web UI but this is probably worth coming back to, to appease linters and type checkers and to make the code easier to reason about.
Relatedly, there is work ongoing to make ruff work with codacy, so hopefully in future we can use ruff ignore syntax for things like this if/when needed
=> chore(datafile): ignore lint rule for codacy, pending refactor

.git-blame-ignore-revs, DEVELOPER.md
This PR attempts to clear some "noise" when using GitHub's "blame view" UI tool to see changes in code history for individual files.
These commits are chosen as they are mostly style-related changes rather than code refactors (minor refactors are OK):
- de38a5bb9559a4acb14317a9038ce8267c432c03
- 675d12b07b1c7f93c2bce9da29790cf364d52505
- 2912b1dfc3fbfc926128702f222b7b1ca9f15c6c
- 5d4324ddb6ed5abad231295d63e28cdf779e5e07
- 16b84e8e7933b98c63eaa4fbeb47f6e28a45d611
- b142b081516e6ac78e426257c7472dd4a9994b89
- 12a3bcd1ba8b229e00e2da8a448e7866c16fdb29
=> chore: add .git-blame-ignore-revs

etc/environment.yml, pyproject.toml
Workaround https://github.com/nedbat/coveragepy/issues/1891
=> ci(dependencies): add temporary upper bound for coverage

.docs/Notebooks/vtk_pathlines_example.py, autotest/test_plot_particle_tracks.py, pyproject.toml
This is a minor refactor to resolve [F821](https://docs.astral.sh/ruff/rules/undefined-name/) for undefined name.
As with other checks, `"flopy/mf6/**/*.py"` is ignored (which currently has several F821 issues).
=> refactor: resolve ruff check F821 for undefined name

DEVELOPER.md, pyproject.toml, tach.toml
Creates visualizations of the import statements in the code. See DEVELOPER.md on how to use it.
=> Add tach package to dev for dependency analysis

.docs/Notebooks/mf6_simple_model_example.py, flopy/mf6/utils/reference.py
The `flopy.mf6.utils.reference` module contains spatial reference classes similar to those deprecated/removed in #1914, #1892, and #1200. These are not in use anywhere in the codebase. The `flopy.discretization` module can/should be used instead?
=> refactor(deprecations): deprecate flopy.mf6.utils.reference module

autotest/test_export.py, pyproject.toml
This fixes a recent CI failure that uses the latest VTK package (9.4.0). The tests are changed from simple counting number of lines to checking attributes in the XML file using [built-in XML tools](https://docs.python.org/3/library/xml.etree.elementtree.html), which should be more robust.
Binary wheels for vtk are now available for Python 3.13, so the conditional installs are removed for vtk and pyvista.
=> ci(vtk): fix tests for vtk-9.4.0 by parsing XML file and checking attrs

setup.py
The `setup.py` file was converted to a setuptools wrapper with #1678. This file is not used in this project, and modern pip/setuptools don't look for it anymore, so it can be cleaned up.
=> chore: remove unused setup.py wrapper

autotest/test_grid_cases.py, autotest/test_particledata.py, flopy/modpath/mp7particledata.py
- default is False which converts vertices to model coordinates
- add simple test
Note: method does get slow when it has to do the vertices conversion for lots of points. This can undoubtedly be optimized by first computing vertices in model coordinates or something along those lines. But I figured that was outside the scope for this PR.
=> fix(mp7particledata): add global_xy to `to_prp`

autotest/test_model_splitter.py, flopy/mf6/utils/model_splitter.py
* add support for empty fmi package
* add support for buy package mapping
=> Update(model_splitter): add timeseries support

autotest/test_mf6.py, autotest/test_model_splitter.py, autotest/test_plot_cross_section.py, autotest/test_plot_map_view.py
This should fix the [failing optional dependency CI tests](https://github.com/modflowpy/flopy/actions/runs/12686192812/job/35358012973). There are still failures afflicting the main CI tests, to be fixed shortly
=> test: mark tests requiring optional dependencies

.github/workflows/benchmark.yml
The `upload-artifact` action stopped uploading "hidden" files (any file whose path contains a leading "." in some element).
=> ci: fix benchmark upload settings

autotest/test_mbase.py, flopy/mbase.py
This PR aims to address an issue found in local testing in `Windows` with `Python 3.13.1`. The issue is seen in the failing test: `test_mbase.py::test_run_model_exe_rel_path` and is caused by a behavior change in `shutil.which` (in Windows) introduced in https://github.com/python/cpython/pull/127035.
For more context, in `test_run_model_exe_rel_path`, the mf6 executable is copied to a relative path, `../bin/mf6` (without extension). Within the test, `shutil.which` is used to locate the executable path. However, with the new changes in `shutil.which`, by default, it would only search for the path with an extension in `PATHEXT`, excluding paths without extension.
=> fix(resolve_exe): allow shutil.which() to find exe without suffix in Windows

.git-blame-ignore-revs
Quick PR ignoring formatting changes in https://github.com/modflowpy/flopy/pull/2411 from Ruff 0.9
=> chore: ignore formatting changes in blame

autotest/test_modflow.py, flopy/modflow/mf.py
Add extra_pkgs kwarg, which updates the mfnam_packages dictionary.
=> feat(mf2005,mf2k): allow loading custom flopy packages

.docs/Notebooks/array_output_tutorial.py, .docs/Notebooks/mt3dms_sft_lkt_uzt_tutorial.py, .docs/Notebooks/plot_cross_section_example.py, .docs/Notebooks/plot_map_view_example.py, .docs/Notebooks/seawat_henry_example.py, .docs/Notebooks/shapefile_feature_examples.py, autotest/conftest.py, autotest/test_notebooks.py, etc/environment.yml
The `environment.yml` was missing a few optional/developer dependencies we've recently added to `pyproject.toml`. Bring the former into sync with the latter (and list packages in the same order).
With luck, conda will eventually be able to consume `pyproject.toml` files, and we can remove `environment.yml`. More info at issue 10633 on the conda repo (not linking to avoid the crossref showing up there).
There were some old pycharm cell format comments in the notebook scripts which jupytext didn't like, remove them.
This should close #2253. To avoid similar situations in the future, don't skip notebooks due to missing dependencies in CI &mdash; we did this for convenient local testing, so tests can run without all optional dependencies, but CI should be strict.
=> chore(dependencies): update conda environment

flopy/mf6/utils/binarygrid_util.py, flopy/utils/observationfile.py, flopy/utils/swroutputfile.py, flopy/utils/utils_def.py
Minor cleanup. Use properties instead of attributes. Deprecate `set_float()` and replace usages with `precision` setter.
=> refactor(FlopyBinaryData): use properties, deprecate set_float

autotest/test_model_splitter.py
Exclude it from the smoke tests
=> chore: mark slow model splitter test

flopy/utils/cvfdutil.py
vertexdict_keys was put out of the if condition skip_hanging_node_check, to avoid failure if the check is not necessary on some grids
Related to issue #2321
=> fix(cvfdutil): fix skip_hanging_node_check

flopy/utils/get_modflow.py
Since these are given to change, it seems sufficient to raise (as we do) if a corresponding asset doesn't exist.
=> refactor(get-modflow): don't hard-code available os tags

flopy/mf6/utils/model_splitter.py
* add support for GWE models
* fix zero padding issue in `split_multi_model`. Padding issue caused splitting arrays with 10 or more model domains to crash.
Closes #2415
=> fixes(Mf6Splitter): multiple bug fixes and added support

.docs/Notebooks/export_vtk_tutorial.py, autotest/test_notebooks.py
Since exporting a transient array looks the same as exporting a normal array, I removed that cell. And commented out 2 more write statements that were each taking ~45s. This brings the runtime from >2 minutes down to ~30 seconds on my machine.
The goal here (eventually) is to get the notebooks to run fast enough for the RTD build service, so we don't have to run them on GH actions and then upload to RTD. Also just for convenience &mdash; it seems a bit daunting and unexpected for a tutorial notebook to spin for minutes. Is there a different transient model we could swap into the VTK export example to avoid commenting out the write statements?
The next slowest are
```
142.58s call     test_notebooks.py::test_notebooks[/Users/wbonelli/dev/flopy/.docs/Notebooks/swi2package_example5.py] …
```
=> perf(tutorials): skip some writes in export_vtk_tutorial.py

flopy/modpath/mp7particledata.py
Fix #2440 and one more similar case
=> fix(mp7particledata.py): avoid attribute error

MANIFEST.in, pyproject.toml
This PR does the following:
- Changes the [build backend](https://packaging.python.org/en/latest/glossary/#term-Build-Backend) from [setuptools](https://setuptools.pypa.io) to [hatch's hatchling](https://hatch.pypa.io/latest/config/build/). Why?
- While both are [PyPA projects](https://packaging.python.org/en/latest/key_projects/#pypa-projects), setuptools has some odd legacy concepts like MANIFEST.in and egg-info directories, that are not used with modern builds. It's an old system that is primarily maintained to maintain legacy behaviour and not to embrace modern enhancements.
- Hatchling is a common and modern build backend, e.g. [demonstrated as a default in guidelines](https://packaging.python.org/en/latest/tutorials/packaging-projects/#choosing-a-build-backend). New features and …
=> chore: replace setuptools with hatchling, remove 'build' extra

autotest/test_binaryfile.py, flopy/utils/binaryfile/__init__.py
=> fix(HeadFile,CellBudgetFile): fix tdis reversal

autotest/test_mbase.py, autotest/test_modflow.py, flopy/mbase.py
This extends a bit further than #2457 to resolve #2455 to use the str and PathLib versions of exe paths in the method. It also improves the docstring and return typing info.
But it also fixes `autotest/test_mbase.py` which was broken on Linux for paths that have mixed case to the repo. Paths don't need to be converted to `lower()` for equality comparisons, as this breaks mixed-case paths. The tests are written to compare pathlib objects, which works for the host path, e.g. Windows paths:
```pycon
>>> from pathlib import PureWindowsPath
>>> PureWindowsPath(r"C:\dir\program.EXE") == PureWindowsPath(r"c:\Dir\program.exe")
True
```
This also catches a missing warning thrown in `autotest/test_modflow.py`.
=> refactor(resolve_exe): also fix tests

flopy/mf6/utils/output_util.py
Noticed and fixed by @jlarsen-usgs in https://github.com/modflowpy/flopy/pull/2465/commits/e8118b8702124d2479f19d73f58f391ada0536bb, just getting this in asap to fix CI tests.
This is a result of https://github.com/MODFLOW-ORG/modflow6/pull/2228
=> fix: trap grb in MF6Output

.docs/Notebooks/mf6_parallel_model_splitting_example.py, autotest/test_model_splitter.py, etc/environment.yml, flopy/mf6/utils/model_splitter.py, flopy/mf6/utils/output_util.py, flopy/plot/map.py, pyproject.toml
* `save_node_mapping` now writes a compressed `hdf5` file and stores additional modelgrid reconstruction information for original and split model representations
* `load_node_mapping` changed to a static method that returns a Mf6Splitter object that can be used for array reconstruction
* updated autotests
* added example usage to `mf6_parallel_model_splitting_example.py`
* json node mapping files no longer supported, user must rewrite node mapping files as hdf5 files.
* bugfix for observation file naming convention on remapped obs files
=> update(Mf6Splitter): change how node mapping is stored and loaded

DEVELOPER.md
Related discussion in #2466. We just dropped python 3.9 in #2467.
=> chore: update python support policy in dev docs

autotest/test_modeltime.py, flopy/discretization/modeltime.py
Add a class method to reconstruct a `ModelTime` from an array of mf6 binary output file headers, and a method to reverse the time discretization. These are useful for binary file reversal.
=> feat(modeltime): add from_headers and reverse methods

autotest/test_gridutil.py, flopy/utils/gridutil.py
Use the same pattern from `get_disv_kwargs` to check/expand arguments in `get_disu_kwargs`. Also update the logic so any 1D array-like of shape `(nlay,)` can be used to specify constant top/bottom elevations per layer, where previously only a list was accepted.
=> refactor(gridutil): improve arg handling in get_disu_kwargs

autotest/test_binaryfile.py, autotest/test_binaryfile_reverse.py, autotest/test_export.py, autotest/test_modeltime.py, flopy/discretization/modeltime.py, flopy/utils/binaryfile/__init__.py, flopy/utils/binaryfile/reverse.py
Following up on #2475. Fixes #2473. #2480 was extracted from this changeset for tidiness.
Up to now the reversal methods have worked for our backwards particle tracking examples, which have very simple time discretizations. But they didn't work in the general case &mdash; only for "symmetric" tdis with no time step multiplier. 
Fix several issues with binary output file reversal.  Clean up and expand tests to include dis/disv/disu with both trivial and a couple non-trivial time discretizations. Make a small (but consequential) fix for #2481: when reversing we need to take the reciprocal of tsmult. Fix an issue with the `ModelTime` class `perioddata` property and add a `pertim` property like the `totim` property.
=> fix(binaryfile): fix head/budget file reversal

flopy/mf6/utils/binarygrid_util.py
https://github.com/MODFLOW-ORG/modflow6/issues/1323
https://github.com/MODFLOW-ORG/modflow6/pull/2254
=> feat(grb): support reading data strings from binary grid file

flopy/utils/gridutil.py
For the new flux limiter the vertices and angledeg information are needed in the DISU grid
This commit adds that info to the kwargs produced by the get_disu_kwarg method.
I can imagine that this is also useful when  using XT3D because it needs the same information
=> Add the angldegx to the kw dictionary produced by the get_disu_kwarg method

autotest/test_model_splitter.py, flopy/mf6/utils/model_splitter.py
* Fix indexing error in observation remapping routine
* Add test for remapping package observations
=> fix(model_splitter.py): add trap for obs packages in bc packages

.docs/Notebooks/mf6_complex_model_example.py, autotest/regression/test_mf6.py, flopy/mf6/data/mfdatastorage.py, flopy/mf6/data/mfdatautil.py, flopy/mf6/data/mffileaccess.py
Address some mishandling of ```EVT``` list input optional fields:
- #2057 
- #2353
=> fix(evt): optional field mishandling

etc/requirements.mf6.txt
Fix some CI failures. Same underlying root cause as https://github.com/MODFLOW-ORG/modflow6-examples/pull/274. We need to get to the bottom of why meson 1.8.0 broke the mf5to6 converter build, and see if we can unpin meson upstream and here.
=> ci: pin meson to 1.3.0 in requirements.mf6.txt

.docs/Notebooks/plot_map_view_example.py, etc/environment.yml
Fix a problem in example notebook CI. The `delete` parameter to `TemporaryDirectory` was added in Python 3.12, but we still want to support >=3.10. Also the `environment.yml` still had a lower bound of 3.9, bump it.
=> chore: use python>=3.10 in conda env, fix map plot example

.github/workflows/mf6.yml, .github/workflows/rtd.yml, etc/requirements.mf6.txt
* skip vtk/pyvista pathlines example on windows for now, I think one of the windows-latest (2025) image updates today broke something which pyvista/vtk/opengl rely on
* switch mf6 CI tests to use the mf6 pixi environment, accommodating https://github.com/MODFLOW-ORG/modflow6-examples/pull/275
=> ci: multiple fixes

flopy/utils/zonbud.py
This small PR resolves the deprecation warnings coming from `np.in1d`:
```python
/home/runner/work/flopy/flopy/flopy/utils/zonbud.py:1031: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instea
```
=> fix: update numpy array comparisons to use isin

autotest/test_model_splitter.py, flopy/discretization/modeltime.py, flopy/mf6/utils/model_splitter.py
* fix support for SSM file mapping
* add ATS support
* replace match/case statements in `ModelTime` with if/else
Closes #2497
=> update(model_splitter.py): support for SSM and ATS

flopy/mf6/utils/codegen/__init__.py, flopy/mf6/utils/codegen/component.py, flopy/mf6/utils/codegen/filters.py, flopy/mf6/utils/dfn.py, flopy/mf6/utils/dfn2toml.py, flopy/mf6/utils/generate_classes.py, pyproject.toml
To avoid the dependency on a development branch of modflow-devtools, copy over the DFN parser, TOML conversion script, etc for now. Also include the necessary transitive dependencies. Workaround for 3.9.3's [failure to launch](https://github.com/modflowpy/flopy/actions/runs/14978507520/job/42076757224).
=> refactor(codegen): move dfn utils from devtools
