modflowpy/flopy

flopy/seawat/swtvdf.py

Now supports mtdnconc to be -1, multiple fluids affecting fluid density. Also supports crhoref, which is quite useful for temperature modeling.

Update swtvdf to support SEAWAT version 4

---

flopy/utils/binaryhydmodfile.py

(trimmed of spaces) rather than bytes

updated the binaryhydmodfile reader to return gagename as a string 

---

flopy/mbase.py
flopy/utils/reference.py

think the merge is straightened out - 
thought on time deltas - present elapsed seconds per time step?

mod to time delta and bug in reference.py

---

flopy/modflow/mfchd.py

Adapt data format in example-documentation loading stress-periods data.

Update example documentation in mfchd.py

---

flopy/modflow/mfbas.py

Add parameter documentation for ifrefm.

Update parameters documentation mfbas.py

---

flopy/modflow/mflpf.py

Add documentation for parameter iwdflg.
Change order of parameter-documentation like in the constructor.

Update parameter documentation mflpfs.py

---

flopy/modflow/mflpf.py

Revert "Update parameter documentation mflpfs.py"

---

flopy/modflow/mfwel.py

Add documentation for parameter dtype.

Update parameter documentation mflwel.py

---

flopy/modflow/mfriv.py

Add documentation for dtype and change parameter order as in constructor.

Update parameter documentation mfriv.py

---

autotest/t007_test.py
autotest/t027_test.py
autotest/t031_test.py
autotest/t032_test.py
examples/Notebooks/flopy3_Modpath_example.ipynb
examples/Notebooks/flopy3_shapefile_features.ipynb
flopy/plot/map.py
flopy/utils/flopy_io.py
flopy/utils/reference.py

* fix bug in xll, xul conversion in SR
* update ModelMap to work with updated SR

SR and ModelMap fix

---

autotest/t007_test.py
flopy/utils/reference.py

add resetting of xul, yul or xll, yll when spatial reference attributes they depend on are reset.

dynamic setting of origin

---

.gitignore
autotest/t012_test.py
examples/data/mt3d_test/mfnwt_mt3dusgs/keat_uzf/Keat_UZF.ssm
flopy/mt3d/mtlkt.py
flopy/mt3d/mtssm.py

LKT trying to pop lake conc obseration file from an empty list

Debugging new test problems associated with MT3D-USGS

---

flopy/modflow/mflpf.py

Update docs in mflpf.py

---

docs/script_examples.md

Saw the links were broken, so fixed them.

Fix links in script examples.

---

flopy/utils/util_array.py

Fixes issue found through pyemu

More general check for NumPy integer type

---

autotest/t002_test.py
autotest/t027_test.py
flopy/mbase.py
flopy/modflow/mfsfr2.py
flopy/utils/check.py

This feature goes nicely beside `mbase.get_package(name)` (which I've also modified slightly).
For example, `m.has_package('dis')` will return True if it's there.
This reads a bit better than `'DIS' in m.get_package_list()`.
Also updated/amended other parts of code and a few autotests.

Add feature: has_package(name), to see if a package exists

---

flopy/export/vtk.py
flopy/utils/reference.py

minor tweaks to deal with quasi-3d beds in VTK export (yes, i actually found a recent model with quasi-3d beds in a data release) - 
and a small change when reading the spatial reference file - it could use some more work.

adding quasi-3d to vtk and line length check to reference

---

autotest/t039_test.py
flopy/modflow/mfmnw2.py
flopy/utils/zonbud.py

This PR addresses a bug that caused errors when non-sequential zones are used. I also cleaned up a typo in the MNW2 documentation and hopefully with the third commit I'll be able to cross the Coveralls Bridge of Death. Green..wait, no red....aaaaaahhh!

Bug patch in ZoneBudget

---

flopy/pakbase.py

Pass numpy array to numpy function instead of Util2d
Fixes #370, #373

Fix issue with Numpy 1.15.0

---

flopy/mf6/mfpackage.py

Fixed runtime issues when many time series files are referenced by a single package.
Issue #427

fix(mfpackage.py): Runtime issue with time series files

---

flopy/mf6/utils/createpackages.py
flopy/modflow/mf.py

Also revised the repr function to work with unstructured modflow-usg models

fix(createpackages): use absolute imports instead of relative imports

---

autotest/build_exes.py

refactor build_exes to download executables. Setting up to allow test
of whether executable is in download and using that instead of building.

testing(build_exes): refactor build_exes to download executables

---

flopy/mf6/utils/__init__.py
flopy/mf6/utils/generate_classes.py

Classes can be updated using definition files downloaded from Github or from a user provided folder containing the definition files.

feat(generate_classes): added script to update MODFLOW 6 classes

---

autotest/t505_test.py
examples/Notebooks/flopy3_mf6_obs_ts_tas.ipynb
examples/Notebooks/flopy3_mf6_tutorial.ipynb
flopy/mf6/data/mfdata.py
flopy/mf6/mfpackage.py
flopy/utils/datautil.py

Single record data can now be entered as a single list. Time series fixed to correctly initialize file name when initialized with <class>.ts.<method>.

Fixes: Initialization of time series file name and more robust support for records

---

flopy/discretization/grid.py
flopy/export/netcdf.py

* keyword bug fixes for Grid.read_usgs_model_reference_file() 
* netcdf bbox from modelgrid.extent bugfix

Fix(grid.py, netcdf.py): Minor bug fixes for modelgrid and netcdf export

---

autotest/t035_test.py
flopy/modflowlgr/mflgr.py

fix(mflgr): fix couple of unit number issues and added a test

---

flopy/modpath/mp7.py
flopy/modpath/mp7sim.py

fix(mp7): fix mp7 laytyp property for MF6 models

---

autotest/t007_test.py
flopy/modflow/mfdis.py

fix(mfdis): multiple issues in mfdis with intersection

---

autotest/t027_test.py
flopy/modflow/mfmnw2.py

* updated make_node_data() to set wells with inconsistent numbers of nodes to ModflowMnw2.node_data recarray
* added test case test_mnw2_create_file() to t027_test.py

fix(ModflowMnw2): fix for issue #556 

---

setup.py

Suggest to use this classifier in an effort to centrally start documenting Python packages for use in hydrological studies. (https://github.com/pypa/warehouse/issues/5728)

Add classifier: Topic :: Scientific/Engineering :: Hydrology

---

autotest/t007_test.py
flopy/export/utils.py
flopy/utils/lgrutil.py
flopy/utils/reference.py

* added export array and export array tests
* one small change to lgrutil to resample a parent grid array and get back a replicated child grid array

fix(export_array_contours): contours would not export in some cases

---

flopy/mbase.py

Fix(mbase.py): laytyp property method call to "UPW" package laytyp variable

---

flopy/modflow/mfmnw2.py

Fix a bug in mnw2 when there are multiple stress periods
* Fix mfmnw2 file

Fix(mfmnw2): Fix a bug that causes mnw2 file writing to crash when

---

flopy/modflow/mfuzf1.py

Fix(mfuzf1): fix read and write dataset 4b when specifysurfk option is used

---

autotest/t061_test_gridgen.py
flopy/utils/gridgen.py

* Fixed minor bugs in to_disu6() method
* Added tests for the to_disu6() and to_disv6() Gridgen methods
* Closes #678

fix(gridgen): fixed writing of mf6 disu package

---

flopy/mf6/modflow/mfsimulation.py

Docstring clean up using flake8 for guidance.

refact(docstrings): refactored docstrings in mfsimulation

---

autotest/t069_test_vtkexportmodel.py
flopy/export/vtk.py

model packages extraction change from ml.packageslist to model.packageslist

fix(vtk): change in export_model when packages_names is None

---

autotest/t024_test.py
autotest/t504_test.py
autotest/t505_test.py
flopy/discretization/structuredgrid.py
flopy/discretization/unstructuredgrid.py
flopy/export/netcdf.py
flopy/mbase.py
flopy/mf6/data/mfdataarray.py
flopy/mf6/data/mfdatalist.py
flopy/mf6/data/mfdatascalar.py
flopy/mf6/data/mfdatastorage.py
flopy/mf6/data/mfdatautil.py
flopy/mf6/data/mffileaccess.py
flopy/mf6/mfmodel.py
flopy/mf6/mfpackage.py
flopy/mf6/modflow/mfsimulation.py
flopy/modflow/mf.py
flopy/modflow/mfbas.py
flopy/modflow/mfdis.py
flopy/modflow/mfmnw2.py
flopy/modflow/mfmnwi.py
flopy/modflow/mfoc.py
flopy/modflow/mfrch.py
flopy/modflow/mfriv.py
flopy/modflow/mfsfr2.py
flopy/modpath/mpsim.py
flopy/mt3d/mt.py
flopy/pakbase.py
flopy/seawat/swt.py
flopy/utils/check.py

refactored mf2005 input data check to support both mf2005 and mf6. issue #738

input data check for mf6

---

flopy/mf6/mfmodel.py

fixed remove_package to rebuild namefile recarray correctly after removing package

fixed remove_package - issue #776

---

flopy/utils/util_list.py

fix(mflist): default value not working

---

autotest/build_exes.py

Fix a number of bugs found when running `nosetests -v build_exes.py` on Windows.
Close #810

fix(build_exes.py): fix bugs for Windows (#810)

---

CONTRIBUTING.md
README.md

Fix a few instruction issues related to FloPy installation and testing.

docs(README.md and CONTRIBUTING.md): fix a few instruction issues

---

autotest/t015_test.py
flopy/modflow/mfstr.py
flopy/utils/flopy_io.py

fix(str): add consistent fixed and free format approach

---

autotest/t504_test.py
autotest/t505_test.py
flopy/export/utils.py
flopy/mf6/data/dfn/gwf-lak.dfn
flopy/mf6/data/mfdata.py
flopy/mf6/data/mfdataarray.py
flopy/mf6/data/mfdatalist.py
flopy/mf6/data/mfdatastorage.py
flopy/mf6/data/mffileaccess.py
flopy/mf6/data/mfstructure.py
flopy/mf6/mfmodel.py
flopy/mf6/mfpackage.py
flopy/mf6/modflow/mfgwflak.py
flopy/mf6/modflow/mfsimulation.py

Feature added to set all data external for a simulation, model, package, or list/array data.

feat(set all data external): set all data external for simulation

---

README.md
autotest/t042_test.py
autotest/t050_test.py
autotest/t070_test_spedis.py
flopy/discretization/structuredgrid.py
flopy/export/utils.py
flopy/export/vtk.py
flopy/utils/postprocessing.py

* fix a few postprocessing and vtk export issues (1st commit)
* allow for selecting stress periods to export to vtk (2nd commit)
* allow for exporting to vtk as true 2d data (3rd commit)

New vtk export functionalities

---

autotest/t505_test.py
flopy/mf6/data/mfdataarray.py
flopy/mf6/data/mfdatalist.py
flopy/mf6/data/mfstructure.py

Specifying period data with value None now only removes data from that period. Also, fixed an unrelated problem by updating the multi-package list.

fix(#856): Fix for period data of None

---

flopy/mf6/data/mfstructure.py

fixed minimum record entry count for lists to never include keywords in the count

fix(#867): fixed minimum record entry count

---

autotest/t504_test.py
flopy/mf6/modflow/mfsimulation.py

Fix(#870): Update ims name file record after removing ims package

---

autotest/t504_test.py
flopy/mf6/modflow/mfsimulation.py

Fix(MFSimulation): remove case sensitivity from register_ims_package()

---

flopy/seawat/swt.py

fix(Seawat.modelgrid): pass lenuni from dis file into modelgrid instance

---

autotest/t011_test.py
examples/data/mf6/test005_advgw_tidal/expected_output/AdvGW_tidal.gitlist
flopy/mf6/modflow/mfsimulation.py
flopy/utils/mflistfile.py

feat(Mf6ListBudget): add support for mf6 budgets with multiple packages with same name

---

autotest/t015_test.py
flopy/modflow/mfstr.py

feat(str): add IRDFLG and IPTFLG control to STR

---

autotest/t016_test.py
flopy/mf6/modflow/mfsimulation.py
flopy/modflow/mfsms.py

feat(ModflowSms): add support for simple, moderate, complex

---

autotest/t015_test.py
flopy/mbase.py
flopy/modflow/mf.py
flopy/mt3d/mt.py

Add similar suppression for other informative messages in mbase, mf,
and mt.
Closes #345

feat(mbase): suppress duplicate package warning if verbose is False

---

flopy/modpath/mp7sim.py

fix(Modpath7Sim): fix TimePointInterval calculation for TimePointOption 3

---

flopy/discretization/structuredgrid.py
flopy/discretization/vertexgrid.py
flopy/export/utils.py
flopy/modflow/mfsfr2.py
flopy/plot/crosssection.py
flopy/plot/map.py
flopy/plot/plotutil.py
flopy/plot/vcrosssection.py
flopy/utils/geometry.py
flopy/utils/gridgen.py
flopy/utils/reference.py
flopy/utils/triangle.py
requirements.travis.txt

refactor(matplotlib imports): wrap matplotlib imports in try/except

---

flopy/utils/check.py

fix get_active() error for confining bed layers

---

autotest/t034_test.py
flopy/modflow/mfsfr2.py
flopy/modflow/mfuzf1.py

update(mfsfr2, mfuzf1) change default optionblock behavior to block = True for 'nwt' models

---

flopy/mf6/coordinates/modeldimensions.py
flopy/mf6/data/mfdataarray.py
flopy/mf6/data/mfdatalist.py
flopy/mf6/data/mfdatastorage.py
flopy/mf6/mfmodel.py
flopy/mf6/mfpackage.py
flopy/mf6/modflow/mfsimulation.py

new check_data option gives user option to turn off data checking for improved performance

feat(set_all_data_external) : new check_data option 

---

flopy/modflow/mfag.py

update for GSFLOW file convention in IRRDIVERSION block.

update(mfag): update _read_block_21_25_or_29 

---

autotest/t007_test.py
flopy/modflow/mfdis.py

fix(dis): fix for dis.get_lrc() and dis.get_node()

---

autotest/t505_test.py
flopy/mf6/coordinates/modeldimensions.py
flopy/mf6/data/mfdatalist.py
flopy/mf6/data/mfdatastorage.py
flopy/utils/datautil.py

Minimum number of data columns was not being calculated correctly for columns that can either repeat and be zero.  Replaced old calculation of minimum data columns with updated calculation based on the code that builds the column headers.

fix(data check): Minimum number of data columns check fixed (#1062)

---

flopy/discretization/grid.py
flopy/discretization/unstructuredgrid.py
flopy/plot/crosssection.py
flopy/plot/plotutil.py

updates to crosssection.py and plotutil.py for unstructued grid cross-sectional plotting

Update(PlotCrossSection): updates for unstructured grid plotting

---

autotest/t504_test.py
autotest/t505_test.py
flopy/utils/gridgen.py

* Closes #1120 
* Fix indexing issue in gridarray_to_flopyusg_gridarray

fix(gridgen): mfusg helper function not indexing correctly

---

.docs/code.rst
.docs/tutorials.rst
examples/Tutorials/modflow6/tutorial02_mf6.py
examples/Tutorials/modflow6/tutorial03_mf6.py
examples/Tutorials/modflow6/tutorial04_mf6.py
examples/Tutorials/modflow6/tutorial05_mf6.py
examples/Tutorials/modflow6/tutorial06_mf6.py
examples/Tutorials/modflow6/tutorial07_mf6.py
examples/Tutorials/modflow6/tutorial08_mf6.py
examples/Tutorials/modflow6/tutorial09_mf6.py
flopy/mf6/coordinates/modeldimensions.py
flopy/mf6/coordinates/modelgrid.py
flopy/mf6/data/mfdataarray.py
flopy/mf6/data/mfdatalist.py
flopy/mf6/data/mfdatascalar.py
flopy/mf6/data/mfdatastorage.py
flopy/mf6/data/mfdatautil.py
flopy/mf6/data/mfstructure.py
flopy/mf6/mfbase.py
flopy/mf6/mfmodel.py
flopy/mf6/mfpackage.py
flopy/mf6/modflow/mfsimulation.py

* Flopy for MF6 documentation improved
* Support for multi-variable scalars as a string (#1028)
* Fix for multiple exchange packages

feat(flopy for mf6 docs): Documentation added and improved for flopy 

---

flopy/mf6/modflow/mfgwf.py

Thanks Brioch! relates to #1115

(inconsequential) update model_rel_path in docstring

---

flopy/utils/modpathfile.py

Remove duplicative code in PathlineFile and TimeseriesFile by adding _ModpathSeries base class
Close #1098

Update(modpathfile.py): Speed up get_alldata() method

---

flopy/discretization/grid.py
flopy/discretization/unstructuredgrid.py

update(cross_section_set_contour_arrays): updates for single layer unstructured and vertex model contouring

---

flopy/utils/rasters.py

* re-run flopy3_raster_intersection.ipynb Notebook
update to address PR #1159 issue

update(raster): update threading routine to use daemon threads

---

flopy/utils/flopy_io.py
flopy/utils/mflistfile.py
flopy/utils/observationfile.py

* added get_reduced_pumping() method to flopy.utils.observationfile module
* updated ListBudget.get_reduced_pumping() to call new method
* moved static IO code to flopy_io.py
* PEP8 cleanups in mflistfile.py
Closes #1048

feat(get_reduced_pumping): update to read external pumping reduction files

---

.docs/conf.py
.docs/introduction.rst
.docs/main.rst
README.md
examples/Tutorials/modflow6/tutorial01_mf6.py
flopy/version.py

doc: clarify readthedocs versions

---

flopy/modpath/mp7particledata.py
flopy/utils/modpathfile.py

fix(modpath7): address #993 and #1053

---

autotest/t504_test.py
flopy/mf6/utils/output_util.py

* update MF6Output gwt list() method to use MfListBudget
* Added test to t504_test.py for adding new observations

Fix(MF6Output): fix add new obs package issue

---

flopy/mf6/data/mfstructure.py

* Support new mf6 transport utility for specifying concentrations for boundary conditions

feat(mf6): allow multi-package for stress package conditions

---

autotest/t050_test.py
etc/environment.yml
examples/Notebooks/flopy3_vtk_export.ipynb
flopy/export/utils.py
flopy/export/vtk.py

* updates for unstructured grid, vertex grid, and structured grid support
* updates to allow the export of pathlines to vtk
* added dependency introduced (python Visualization ToolKit library -- pip install vtk) for vtk exporting
* updated flopy3_vtk_export.ipynb to document changes
* added deprecation warnings for old exporting code
* updated t050_test.py
Closes #873
Closes #1070
Closes #1114
Closes #1127 
Closes #1228

Update(Vtk): updates to Vtk class for MF6, HFB, and MODPATH

---

autotest/t029_test.py
flopy/mf6/utils/postprocessing.py

* function was fixed to support multi-layer models
* test added to ensure face flow calculations work
* replace #1329

fix(postprocessing): get_structured_faceflows fix to support 3d models

---

autotest/t065_test_gridintersect.py
flopy/utils/rasters.py

* update autotest t065_test_gridintersect.py
* update flopy3_raster_intersection.ipynb
Closes #1365

update(Raster): added "mode" resampling to resample_to_grid

---

autotest/t039_test.py
flopy/mf6/utils/output_util.py

fix(.__zonebudget()): add additional check for "gwf6" model type.

---

flopy/plot/crosssection.py
flopy/plot/plotutil.py

* update `ua` variable declaration in line_intersect_grid to trap for "inf" scenarios when line intersects a single closing point of the polygon 
* update PlotCrossSection, update line buffering method to reduce the likelihood of collinear line/polygon edge intersection

update(line_intersect_grid, PlotCrossSection): fix cell artifact and collinear intersection issues

---

flopy/plot/crosssection.py

* update to check n points instead of n cells intersected

fix(PlotCrossSection): update number of points check

---

README.md
setup.cfg

- specify compatible OS and Python3 versions in `setup.cfg`
- fix/update `README.md` badges
- fix broken Anaconda badge
- add Anaconda badges for platform & latest release
- add PyPI badges for status and supported Python versions

docs: add classifiers to setup.cfg, fix/update readme badges

---

flopy/discretization/unstructuredgrid.py
flopy/discretization/vertexgrid.py
flopy/export/vtk.py

* updates to UnstructuredGrid and VertexGrid verts property. Rotate and translate verts based on modelgrid offsets. These have been updated for consistency in behavior with StructuredGrid
Closes #1466 
Closes #1595

Updates(vtk): updates for errant interpolation in point_scalar routines

---

DISCLAIMER.md
README.md
docs/PyPI_release.md
scripts/make-release.py

Added a few FloPy related references and updated the Questions section in README.md

doc: Update to disclaimer

---

.github/workflows/release.yml

Auto-generated changelog wasn't prepended to `docs/version_changes.md` correctly, fix it

fix(ci): fix changelog prepend step

---

flopy/pakbase.py

fix bug in pakbase: defining number of parameters per stress period
close #1661

fix(modflow/pakbase) issue 1661

---

flopy/plot/styles.py

* add fontsize argument to graph_legend_title
* add fontsize and title_fontsize kwargs to graph_legend

update(styles): add graph_legend fontsize parameters

---

flopy/mf6/utils/binarygrid_util.py

* update docstrings for `.ia`, `.ja`, `.iavert`, and `.javert` to include more detailed descriptions and example usage

update(MfGrdFile): update docstrings in MfGrdFile

---

.readthedocs.yml
binder/environment.yml
binder/postBuild
etc/environment.yml
pyproject.toml

Update environment.yml to include imageio for pyvista. Update binder files to use current modflow executables release.

docs: refactor readthedocs yaml file

---

.docs/conf.py
.github/workflows/rtd.yml

fix repo owner refs `w-bonelli` -> `modflowpy`, leftover from testing #1794

docs: fix repo owner refs

---

.docs/Notebooks/mf6_parallel_model_splitting_example.py
autotest/test_model_splitter.py
flopy/mf6/utils/model_splitter.py

* Added advanced package weighting for metis array generation
* Added code to consider consider LAK package information during metis splitting
* Update reconstruct_array to assert all arrays are of a consistent shape, either ncpl or nnodes
* Added JSON based save_node_mapping() and load_node_mapping() methods
* Minor bug fixes
* Added additional tests for optimize_splitting_mask() method and JSON save and load methods

updates(Mf6Splitter): Feature updates and bugfixes

---

autotest/test_mf6.py
autotest/test_model_splitter.py
flopy/mf6/data/mffileaccess.py
flopy/utils/datafile.py

Add tests for structured and vertex grid models with external binary files.

fix(mf6): fix external binary files for vertex grids

---

scripts/update_version.py

Support an optional label appended to version strings, allows adding "+" to the version string in `develop` to indicate preliminary/non-release status

ci: support optional version label in update_version.py

---

.github/workflows/rtd.yml
autotest/test_mf6.py
flopy/mf6/data/mffileaccess.py
flopy/utils/binaryfile.py
flopy/utils/datafile.py

fix(binary): fix binary header information

---

CITATION.cff
README.md

* update cff file with Hughes et al. (2023) as the preferred reference and Bakker et al (2016) as a reference

readme: update flopy citation with Hughes and others (2023)

---

.docs/conf.py
.docs/main.rst
.github/workflows/rtd.yml
pyproject.toml

- `nbsphinx` gallery rendering is broken (at least for flopy) with `sphinx` >= 7.2, pin to 7.1.2 until fixed upstream
- remove unused `pydata-sphinx-theme` dependency from `pyproject.toml` (currently `sphinx-rtd-theme` is used)
- remove unused `nbsphinx-link` dependency from `pyproject.toml` and extension from `.docs/conf.py`
- minor refactoring for clarity of intent in `.docs/conf.py`
- update `main.rst` version string

docs: miscellaneous fixes/cleanup

---

.docs/prolog.rst
README.md
binder/postBuild
scripts/update_version.py

The `mybinder.org` federation lost Google sponsorship earlier this year and has been unreliable since then
* https://discourse.jupyter.org/t/mybinder-org-reducing-capacity-unstable/19163
* https://blog.jupyter.org/mybinder-org-reducing-capacity-c93ccfc6413f

docs(binder): remove configuration, links, badges

---

.github/workflows/benchmark.yml
.github/workflows/commit.yml
.github/workflows/examples.yml
.github/workflows/mf6.yml
.github/workflows/optional.yml
.github/workflows/regression.yml
.github/workflows/release.yml
.github/workflows/rtd.yml
autotest/pytest.ini

* followup to #1961
* configure once in `pytest.ini` instead of `--color=yes` on every invocation

ci: toggle colorful test output in pytest.ini

---

autotest/test_modpathfile.py

* see #1977 
* test pathline export to shapefile with user-defined fields
* test with/without automatic field name truncation
* maybe worth warning if flopy truncates a field name?

test(modpathfile): test shapefile export with custom fields

---

.github/workflows/mf6.yml

* forgot the repo ownership change in #1985

ci: fix awvwgk/setup-fortran -> fortran-lang/setup-fortran

---

autotest/test_model_splitter.py

* followup to #2034
* mark with `requires_pkg("pymetis")`
* run `black`/`isort`

test(MF6Splitter): mark test_idomain_none requiring pymetis

---

flopy/mbase.py

refactor(mbase): append not prepend flopy bindir to PATH

---

.docs/Notebooks/mf6_data_tutorial08.py
autotest/regression/test_mf6.py
flopy/mf6/data/mfdata.py
flopy/mf6/data/mfdataarray.py
flopy/mf6/data/mfdatalist.py
flopy/mf6/data/mfdataplist.py
flopy/mf6/data/mfdatascalar.py
flopy/mf6/mfmodel.py
flopy/mf6/mfpackage.py
flopy/mf6/mfsimbase.py
flopy/mf6/utils/model_splitter.py

* "binary" and "base_name" parameters added to set_all_data_external
* added documentation

feat(set all data external options): additional parameters added

---

DEVELOPER.md
pyproject.toml

* add `dev` composite group to install all optional dependencies at once
* update `DEVELOPER.md` to demonstrate

refactor(pyproject.toml): add dev dependency group

---

autotest/test_get_modflow.py
flopy/utils/get_modflow.py

* until ARM mac distributions supported from all three repositories?
* #2110 was premature

chore(get-modflow): revert 4c5e2ee for now

---

etc/environment.yml
pyproject.toml

https://github.com/pytest-dev/pytest/releases/tag/8.1.0 broke some plugins and was yanked

chore(dependencies): restrict yanked pytest version 8.1.0

---

flopy/plot/plotutil.py

* accidentally broken with switch to ruff
* fixes optional dependency ci tests

test(plotutil): fix syntax causing test failures

---

autotest/test_export.py
flopy/export/vtk.py

* support PRT pathline format
* support dataframe or recarray
* support merged or separate paths
* attach layer array to exported points
* motivated by https://github.com/MODFLOW-USGS/modflow6-examples/pull/161

feat(vtk): improve vtk pathline export

---

flopy/mf6/coordinates/modeldimensions.py
flopy/mf6/coordinates/modelgrid.py
flopy/mf6/data/mfstructure.py
flopy/mf6/mfmodel.py
flopy/mf6/utils/mfenums.py

Changed DISL name to DISV1D to be consistent with ongoing surface water modeling work in MODFLOW 6

feat(disv1d): rename DISL to DISV1D

---

pyproject.toml

* avoid https://github.com/zeromq/pyzmq/issues/1907

fix(dependencies): pin pyzmq >= 25.1.2 for arm macs

---

autotest/regression/test_mf6.py
flopy/mf6/data/mfdatalist.py
flopy/mf6/mfpackage.py

Empty stress period 1 transient data is now retained and used to create empty stress period block (#1091)

fix(empty transient data): Empty first stress period block (#1091)

---

flopy/mf6/coordinates/modeldimensions.py
flopy/mf6/coordinates/modelgrid.py
flopy/mf6/mfmodel.py
flopy/mf6/utils/mfenums.py

* Introduce new 2d grid type
* Purpose is to support creation of new SWF model data sets
* Not formally tested yet in autotest
* Plotting in 2d needs work and testing as does other export capabilities

feat(disv2d): introduce support for a 2D vertex grid (for overland flow)

---

flopy/utils/gridintersect.py

improve performance _vtx_grid_to_geoms_cellids()
Fixes #2152.

fix(#2152): improve gridintersect geometry creation for vertex grids

---

autotest/test_particledata.py
flopy/modpath/mp7particledata.py

* add flopy support for https://github.com/MODFLOW-USGS/modflow6/pull/1756
* determines whether to return local z coordinates
* useful to set release elevation w.r.t. water table
* minor docstring improvements

feat(mp7particledata): add localz option for PRT PRP conversions

---

.github/workflows/rtd.yml
DEVELOPER.md
autotest/conftest.py
etc/environment.yml

* import snapshot fixtures from `modflow-devtools` and remove them from `conftest.py`

test(snapshots): use devtools snapshot fixtures

---

flopy/export/vtk.py

fix the key of __transient_vector

---

autotest/test_gridintersect.py

This PR addresses the following issue: https://github.com/modflowpy/flopy/issues/2214

test(gridintersect): clarify intersection of line with grid

---

.github/workflows/commit.yml
autotest/test_seawat.py
flopy/seawat/swt.py

fix(swt): pass load_only down to Mt3dms.load()

---

.github/workflows/rtd.yml
flopy/mf6/data/mfdataarray.py
pyproject.toml

This lets us trigger the RTD build at will, which will allow fixing problems like #2253 without pushing commits

ci(rtd): add workflow_dispatch trigger to rtd.yml

---

.docs/Notebooks/seawat_henry_example.py
flopy/mf6/data/mfdataarray.py
pyproject.toml

https://github.com/modflowpy/flopy/discussions/2252#discussioncomment-9938765

docs(examples): move swt henry example to mt3d/swt section

---

.github/workflows/rtd.yml

ci(rtd): add ref input for rtd build

---

.github/workflows/rtd.yml

ci(rtd): fix sha detection for manual runs

---

.docs/md/get_modflow.md

Warn about https://github.com/modflowpy/flopy/issues/2274

docs(get-modflow): add note on mac/venv bindir discovery

---

autotest/test_mf6.py
flopy/mf6/mfmodel.py

fix(modelgrid): fix missing coord info if disv

---

.github/workflows/benchmark.yml
.github/workflows/commit.yml
.github/workflows/examples.yml
DEVELOPER.md
README.md
etc/environment.yml
pyproject.toml

Drop support for python 3.8.
python 3.13 does not support VTK yet.

Fixate python to 3.9 - 3.12

---

DEVELOPER.md

This PR adds some tips to the developer doc for test debugging in VS Code.

docs(DEVELOPER.md): added tips for interactive test debugging in VS Code

---

.gitignore

chore: add uv lockfile to .gitignore

---

.github/workflows/benchmark.yml
.github/workflows/codegen.yml
.github/workflows/commit.yml
.github/workflows/examples.yml
.github/workflows/optional.yml
DEVELOPER.md
README.md
pyproject.toml

chore: drop python 3.9

---

autotest/test_binaryfile.py
autotest/test_cellbudgetfile.py
flopy/utils/binaryfile/__init__.py

#2473 flushed out some bad kper/kstp/totim/pertim values in the reversed headers, and some sloppy tests. Also remove unused utility functions.
The reported error still needs a fix in followup.

fix(binaryfile): fix head/budget reversal methods

---

.docs/Notebooks/mf6_complex_model_example.py
autotest/regression/test_mf6.py
flopy/mf6/data/mfdatastorage.py
flopy/mf6/data/mfdatautil.py
flopy/mf6/data/mffileaccess.py

Address some mishandling of EVT list input optional fields:
- #2057
- #2353

fix(evt): optional field mishandling
